### ISSUE TITLE
problem with reservation 

### ISSUE THREAD

**Issue by dosli** [bgo-bioimagerie/platformmanager#100]
Hello. 
I'm working at the ImPACcell platform. I added a new user lperrot, but the person concerned is not able to reserve any equippement. Could you please help me to fix this problem?

**Comment by osallou** [comment]
did you give required access to this person ?

what is the scenario/error exacty?

**Comment by dosli** [comment]
I chose Role : Utilisateur and Date de fin de contrat : 30/06/2019. She has an access to the agenda, the "+" sign is visible but when she tries to validate the reservation nothing happens. Is it possible that there is a conflict of e-mail adresse? She already exists in the system under her maiden name but i can not delete it (user name lbachelot).

**Comment by osallou** [comment]
Do you have a working user id to compare with for this platform?

Le jeu. 6 sept. 2018 à 14:31, Dominika Sliwa <notifications@github.com> a
écrit :

**Comment by dosli** [comment]
yes, for example hleclair

**Comment by osallou** [comment]
seems your user has no associated client.
reservation form , I suppose, does not propose any value in client field, for this person.
If no client is defined, it supposes client is the person itself. However no client is defined with this user id either.

With your id, or hleclair, we can see some related clients.

I do not know how works the software, but it seems that, to do a reservation, a user need to be associated to a client (even if the client is himself).

I see in your config, that client menu is disabled.

**Comment by dosli** [comment]
It works!!! Thanks a lot

**Comment by osallou** [comment]
fine
