### ISSUE TITLE
plateform-Manager  inaccessible

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#102]
Bonjour,

Pour des raisons inconnues le logiciel plateform-Manager est inaccessible depuis ce matin. La page qui s'ouvre porte le message suivant:
It seems like there is an issue accessing this service
We're doing our best to solve this issue, please retry later on.

If the problem persists, please do not hesitate to contact us at support@genouest.org

You can check our web status here
Pascale H2P2

**Comment by abretaud** [comment]
Bonjour,
Il y a eu un problème technique sur le serveur cette nuit. On travaille à la remise en ligne.

**Comment by abretaud** [comment]
pfm.genouest.org est de nouveau opérationel
