### ISSUE TITLE
modifier un utilisateur sur H2P2

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#105]
Bonjour, 
Nous désirons modifier les coordonnées d'un utilisateur ( adresse mail) pour  Sophie Rose, 
mais nous n'y arrivons pas.
Merci pour votre  aide 
Pascale

**Comment by osallou** [comment]
je ne vois pas de menu pour effectuer cette opération en effet, il ne semble pas possible de modifier un utilisateur.

il semble que le seul moyen soit de créer un nouvel utilisateur.
il faudrait modifier le logiciel pour ajouter cette fonctionalité me semble-t-il plutot essentielle.

**Comment by osallou** [comment]
@Pbellaud 
en revanche, dans les préférences de l'utilisateur (lorsqu'il est connecté), ds "Mon compte" => "Information", il semble possible de modifier l'email. Est ce Sophie Rose a essayé de le faire par ce biais?
