### ISSUE TITLE
une date du calendrier en erreur 502 

### ISSUE THREAD

**Issue by magalieFeyeux** [bgo-bioimagerie/platformmanager#107]
Bonjour,
Une date (lundi 12 novembre) sur le calendrier pour une seule ressource d'un domaine fait une erreur 502 quand j'essaye d'y accéder.
Cordialement
Magalie

**Comment by osallou** [comment]
bonjour,
qu'essayez vous de faire exactement? Réserver une ressource sur une date antérieure ?
Quelle plateforme/resource?

**Comment by magalieFeyeux** [comment]
je note sur le calendrier mes temps de travail pour chaque projet. Je fais de l'analyse d'image pour la plateforme MicroPICell.
Le domaine est personnel et la ressource est moi-même.
le problème survient aussi bien si je demande l'affichage de cette date en particulier ou de la semaine complète

**Comment by osallou** [comment]
je ne vois pas de plateforme intitulée MicroPICell sur notre site, vous êtes hébergée sur pfm.genouest.org ?

**Comment by chdiot** [comment]
La plate-forme est effectivement hébergée à Nantes.

**Comment by osallou** [comment]
il faut voir cela avec eux alors, désolé

**Comment by magalieFeyeux** [comment]
désolé de vous avoir dérangé.
Je sais que la migration est prévu, nous sommes en attente d'information pour le ldap, il me semble.
