### ISSUE TITLE
Devis

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#108]
Bonjour, 
Lorsque j'édite un nouveau devis dans PFManager pour H2P2, 
Ex : Samson Michel, le devis s'edite bien en PDF, mais il n'y a pas de tarif 

![image](https://user-images.githubusercontent.com/39952219/49002085-dce4c480-f15e-11e8-97aa-db137c3caca8.png)
Est ce possible de résoudre le problème 
Merci

**Comment by osallou** [comment]
il semble qu'il y ait un bug ds la gestion des devis.
@abretaud , on dirait que les devis n'utilisent pas le bon champ (Modules/quote/Controller/QuotelistController.php):

    $unitprice = $modelServicesPrices->getPrice($item['id_content'], $info['id_belonging']);

devrait être à priori:

    $unitprice = $modelServicesPrices->getPrice($item['id_content'], $info['id_pricing']);

avec comme patch ds Modules/quote/Model/Quote.php (getAllInfo):

            if (count($resps) > 0) {
                $data["address"] = $modelClient->getAddressInvoice($resps[0]["id"]);
                $data["id_belonging"] = $resps[0]["id"]; 
            + $data["id_pricing"] = $resps[0]["pricing"];

en effet, il cherche le "price" à partir de l'identifiant du responsable, et non de sa catégorie de pricing

Avec cette modif, en test, cela a l'air bon. A valider côté prod? (à jour ds code du serveur de pfm dev)

**Comment by osallou** [comment]
le problème semble bien effecvtif ds la gestion des devis de toutes les plateformes.

**Comment by osallou** [comment]
@abretaud  La table SePrice  réfère id_belonging et id_service pour avoir un *price* mais le tarif est associé à un service et une catégorie d'utilisateur (académique, etc...), pas à des utilisateurs.... :-(

**Comment by osallou** [comment]
@abretaud  j'ai pushé une branche fix_quote_108 comme proposition de fix

**Comment by abretaud** [comment]
yep @osallou je regarde ça tout à l'heure, on réunionne là... Bon voyage !

**Comment by abretaud** [comment]
J'ai appliqué le patch sur pfm.genouest.org, ça semble marcher
@Pbellaud est-ce qu'il serait possible de confirmer que c'est corrigé ?

**Comment by abretaud** [comment]
@Pbellaud est-ce que c'est ok pour ce bug ?
