### ISSUE TITLE
Informations sociéte

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#111]
Bonjour, 
Lorsque je vais dans compte clients / puis informations société pour H2P2, 
les informations sont remplies et ne peuvent pas se supprimer  
![image](https://user-images.githubusercontent.com/39952219/49067640-e9cbeb80-f224-11e8-8d81-14ef12b1230f.png)
Je vous remercie 
Pascale

**Comment by abretaud** [comment]
@Pbellaud tu essayes de vider certains champs c'est ça ?
Je ne comprends pas bien à quoi correspondent ces infos, à quelle société est-ce sensé correspondre ? H2P2 ?

**Comment by gaetanHerve** [comment]
Changes won't be taken into account by the app. Should be simple to solve. Also, what does this form stand for. It doesn't seem to have impact on invoices for example
