### ISSUE TITLE
platform training - pb upload images

### ISSUE THREAD

**Issue by mnivard** [bgo-bioimagerie/platformmanager#112]
Hello,
platform manager training ne prend pas les images et les fichiers (carroussel, logos des espaces, et modele de facture ainsi que téléverser des img) . j'ai déjà eu ce pb sur l'ipr et c'était un pb de upload. 
il y a l'Issue #96 qui ressemble également à la même chose.
A++
Mariette

**Comment by mnivard** [comment]
Hello,
Thanks you
It's ok but it's the same pb with the carroussel ?

**Comment by abretaud** [comment]
Fixed in https://github.com/bgo-bioimagerie/platformmanager/commit/74c5e643d38821ede175a39d9911a285c058148d !
Is it ok now?

**Comment by mnivard** [comment]
sorry je continue même problème dans facture/invoices, il ne prend pas les modèles de documents ni les images.

**Comment by abretaud** [comment]
c'est p'tet réglé, ou pas, tu peux retester ?

**Comment by mnivard** [comment]
salut,
c'est ok pour les images dans invoices/factures
pour la partie modele a telecharger ca ne l'affiche pas mais ca a l'air de le prendre .
je vais creuser c'est peut -être côté utilisateur la suite
merci :-)
