### ISSUE TITLE
Booking fails silently when no client account affiliation

### ISSUE THREAD

**Issue by abretaud** [bgo-bioimagerie/platformmanager#115]
When a user tries to book something in the calendar, if the user is not affiliated to a client account, the booking fails silently = the user is redirected to the submission form, but no error message explains the problem. The bug is located around https://github.com/bgo-bioimagerie/platformmanager/blob/master/Modules/booking/Controller/BookingdefaultController.php#L230 but error management is obscure

**Comment by osallou** [comment]
Should an inaffiliated user be able to login?

**Comment by abretaud** [comment]
It depends on the platform: some platforms don't ask users to pay, so they usually don't affiliate them for billing... It should be configurable I guess.

**Comment by OlivierCollin** [comment]
I guess yes if he wants to access ta a facility that do not charge or do not need to train the user on its equipment.

**Comment by OlivierCollin** [comment]
Bug confirmed. I created a client account for myself and I am now able to book some equipement.
