### ISSUE TITLE
Création nouvel utilisateur

### ISSUE THREAD

**Issue by griponp** [bgo-bioimagerie/platformmanager#116]
Une question sans doute triviale mais en créant un nouvel utilisateur je me rend compte qu'il n'est pas possible de lui attribuer un mot de passe provisoire. Par contre le mot de passe est réclamé pour sa connexion. Que faire?

**Comment by abretaud** [comment]
Le mot de passe est envoyé automatiquement à l'adresse email de l'utilisateur
