### ISSUE TITLE
No more email notification when unbooking

### ISSUE THREAD

**Issue by xavpinson** [bgo-bioimagerie/platformmanager#117]
When unbooking a system, the user has the choice of sending a notification by email to the other users of the system. This no longer seem to work, no one gets the email.

**Comment by xavpinson** [comment]
Any idea? :)

**Comment by OlivierCollin** [comment]
I did a reservation and monitored the mail server. No mail is sent when deleting a reservation. We need to investigate further in the pfm code.

**Comment by osallou** [comment]
reservation and un-reservation email are defined in plaform configuration

**Comment by OlivierCollin** [comment]
Great ! It worked ! I tried on the Arche facility and now I am spamming everybody ;-) 
Thanks for pointing this out !

**Comment by OlivierCollin** [comment]
@xavpinson 
Of which facility where you talking about ?

**Comment by xavpinson** [comment]
Sorry, I should have been more specific. It is on the MRic photonics facility.

**Comment by OlivierCollin** [comment]
Below is the configuration for MRic photonics

![image](https://user-images.githubusercontent.com/18054721/52130744-4b507200-263b-11e9-97e0-115947a86cfd.png)

I can test by booking an equipment and cancelling just afterwards but I am worried about the fact that every user will receive an email.... 
Do I have your authorization to do this ?

**Comment by OlivierCollin** [comment]
Thanks !

This is strange, if I book an equipment on Arche. The cancellation interface looks like this 

![image](https://user-images.githubusercontent.com/18054721/52133237-3aa2fa80-2641-11e9-82f0-14d8f20dbe70.png)

On MRic photonics, I do not have the "Save" and "suppress" buttons ?

![image](https://user-images.githubusercontent.com/18054721/52133448-a1281880-2641-11e9-9ace-14b5cf7369e9.png)

Weird....

**Comment by OlivierCollin** [comment]
I am now receiving unbooking emails for the fast-flim. 
(The Fast-FLIM has been freed from 2019-03-13 09:00 to 2019-03-13 11:00)

Can this case be closed ? 

Meilleurs regards, 
Olivier

**Comment by xavpinson** [comment]
Hello,
I am digging up this issue as I got new elements from Rennes 1 DSI. I am quoting below a service ticket I created to try and solve the problem (full exchange in the attached pdf). 

> Bonjour,
Les mails en provenance du serveur de Genouest transitent en effet par le service anti-spam de Renater avant d'être délivrés dans les boites aux lettres des personnels de Rennes 1.
Dans le code source du mail j'ai repéré :
To: undisclosed-recipients:;
From: Root User <root@localhost>
Ce mail est donc bloqué par le service anti-spam de Renater parce que les champs From: et To: ne contiennent pas d'emails valident.
Il faut donc affiner la configuration de l'application qui génère ces mails pour que vous puissiez les recevoir.
O. Germes.
[ticket DSI.pdf](https://github.com/bgo-bioimagerie/platformmanager/files/4203987/ticket.DSI.pdf)


Is it possible to configure platform-manager to avoid blocking by renater filter?

Thanks a lot.

Xavier

**Comment by osallou** [comment]
thanks for analysis

I am looking at code/config, seems an error somewhere as config explicitly set *from*
Regarding *to* , recipients are hidden (bcc: ) which should not be an issue by itself, so I gonna focus on *from* for the moment.

**Comment by osallou** [comment]
Comment on code:

email is sent using user email and space name (real mail and display name)

address root@localhost is the default address used by PHPMailer

**Comment by osallou** [comment]
Comment on code:

Looks like PHPMailer sees the From empty and the To not set (has only bcc fields).
For to, use undisclosed-recipients as default, should be fine.

Question is about From , is it empty (user email)?

**Comment by osallou** [comment]
@xavpinson I made a fix on From, could you try it? and check at from/subject
I expect To not to be a pb. If still an issue, will try to modify the To too.

**Comment by xavpinson** [comment]
It looks like it's working.
Many thanks!

**Comment by osallou** [comment]
is subject line ok (with [ spacename ] ) ?

**Comment by xavpinson** [comment]
In my test I got "[MRic Photonics]Confocal Olympus has been freed" as subject line. It seems ok but I am wondering if it should not be my name instead of MRic Photonics. I will try with a user and let you know.

**Comment by xavpinson** [comment]
I just had a user to try and the subject line is still "[MRic Photonics]XXX has been freed"

**Comment by osallou** [comment]
we put space name, originating user email seems not available in code at mail sending step.
this was part of the issue, originally the From was the user email, but seems it is empty. This is a bug, but would need much more debug/fix.

**Comment by xavpinson** [comment]
OK. It is anyway a big improvement in the current state. Thanks again.
