### ISSUE TITLE
Pb de connexion à mon compte H2P2

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#118]
![image](https://user-images.githubusercontent.com/39952219/51822523-df89a480-22dc-11e9-979d-9a9af9986ee3.png)
![image](https://user-images.githubusercontent.com/39952219/51822538-f4663800-22dc-11e9-8b30-ae57c4bdefd3.png)
Bonjour, 
Nous avons un problème de connection à notre compte, ca nous met un message d'erreur  c'est le même problème pour les administrateurs et pour les utilisateurs

Merci 
Pascale

**Comment by abretaud** [comment]
Bonjour,
De notre côté on arrive bien à accéder à pfm et à h2p2, est-ce que vous avez toujours le problème ?
