### ISSUE TITLE
Pb new utilisateur

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#119]
Nous avons enregistré un nouvel utilisateur jeudi  pour H2P2: Sauzay Chloé, mais elle n'a pas reçu de mail pour son identifiant et son mot de passe, nous lui avons donné une autorisation sur le vibratome, elle ne peut donc pas s'enregistrer.
Merci 
Pascale

**Comment by osallou** [comment]
closing, no info....
