### ISSUE TITLE
Pr connexion

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#120]
Nous avons 2 utilisateurs : Soizic Jamin et Nicolas Vu qui ne peuvent pas  s'enregistrer en MAD sur H2P2 
Merci 
Pascale

**Comment by abretaud** [comment]
Est-ce qu'il y a une erreur particulière ou non ? Que se passe-t-il quand ils essayent de s'enregistrer ?

**Comment by gaetanHerve** [comment]
Update: Nicolas vu has booking accesses (MAD), Soizik Jamin is no longer member of H2P2 space
