### ISSUE TITLE
ptfm-training

### ISSUE THREAD

**Issue by mnivard** [bgo-bioimagerie/platformmanager#122]
Hello,
I have a problem when I try to change the image of space , I take a new image , ptfm write the good past of new file but when I click on "Valider" . There is no change after
![image](https://user-images.githubusercontent.com/10153480/52473102-450b4a00-2b95-11e9-99cd-ca9b753abd8d.png)

**Comment by abretaud** [comment]
Is it solved?

**Comment by mnivard** [comment]
Yes in fact it takes times, 
I just have to wait a little :-)
