### ISSUE TITLE
THEMIS : pb home page 

### ISSUE THREAD

**Issue by ludivinerault** [bgo-bioimagerie/platformmanager#123]
Hello,

I want to start today to configure Platform-Manager for THEMIS (ScanMAT) on Training platform (https://pfm-training.genouest.org/comhome/11).

I activate the module Com and I validate Yes in order to use the news page as homepage. Now, when I want to go to the page of THEMIS, I have this page (Capture). I don't have any more access to the tools and "Configuration" tool to modify this configuration.
How can I change this ?
Can you change this yourself ?

Thanks and have a nice afternoon,

Ludivine Rault
![capture](https://user-images.githubusercontent.com/46990826/52795563-51e6dc80-3072-11e9-8681-8a668379c9ab.png)

**Comment by mnivard** [comment]
**hello, same pb for emmanuelle and me ,

I test and in fact if you want to see your text in first and have the modules under it's possible but you have to say no for put your com' page to your welcome page.**

"Bonjour Mariette,

Je suis entrain de tester plateform-manager et j'ai une petite question.
En effet après avoir modifier dans "communication" le message d'accueil, je reviens systématiquement sur cet écran ci quand je clique sur S2Wave: 


Je n'ai plus accès au différents outils de configurations...Est-ce normal? Que faut-il faire pour y avoir de nouveau accès."

**Comment by osallou** [comment]
pb fixed
it is possible to access the *hidden* menu directly:

https://pfm-training.genouest.org/comconfig/X  with X = the id of the current *space* (11 in above screenshot)

**Comment by ludivinerault** [comment]
Thanks for the information.

Ludivine
