### ISSUE TITLE
PEGASE

### ISSUE THREAD

**Issue by chdiot** [bgo-bioimagerie/platformmanager#125]
Hi, it's Christian, playing with PEGASE1 test.
How to add this picture for UMR PEGASE?
![image](https://user-images.githubusercontent.com/39738033/61720091-799b4880-ad66-11e9-8b24-586b64bb41f0.png)

Just to test

**Comment by OlivierCollin** [comment]
Hi, it's Olivier, slowly melting... 

If you go the "space" menu, you should be able to insert your image as a logo. 
However, I am not sure if there are any restrictions about the size since your image is larger than high. 

![image](https://user-images.githubusercontent.com/18054721/61720641-73f23280-ad67-11e9-9d31-380c13ca0ccc.png)

**Comment by chdiot** [comment]
Hmmm, it seems I can't access this "Modifier espace" menu.

**Comment by OlivierCollin** [comment]
Oh.... 
However you have an admin status for this space. 
![image](https://user-images.githubusercontent.com/18054721/61721715-37bfd180-ad69-11e9-8d25-a6c1be33e190.png)

I was able to insert the image and, as I suspected, the result is ugly because of the resizing ;-)

**Comment by chdiot** [comment]
Very ugly :D

**Comment by chdiot** [comment]
But dfinitively not have access to the menu :/

**Comment by OlivierCollin** [comment]
OK, I will check with @mnivard if she has experienced the same behaviour and if there is some workaround available, otherwise we will report a bug.

**Comment by chdiot** [comment]
Thanks Olivier!

**Comment by mnivard** [comment]
Hello,
In fact this part is reserved to "super admin" so you can't change it but you can tell us and we change the image of your platform
:-)
Have a good day

**Comment by mnivard** [comment]
I just change a little your image, is it ok? 
If you want to change the text at the bottom we can also change it.
![Capture](https://user-images.githubusercontent.com/10153480/61773134-2ec81200-adf4-11e9-9756-dd4d4becd590.PNG)

**Comment by osallou** [comment]
space owners should have possibility to modify space image

if setting someone as "admin" in superadmin space manage, can owner modify this?

**Comment by mnivard** [comment]
for the moment , on pfm you have to be superadmin in order to change the image and title and description.
