### ISSUE TITLE
conversion système décimal en système horaire

### ISSUE THREAD

**Issue by pgripon** [bgo-bioimagerie/platformmanager#126]
Bonjour
Sur Platform manager le calendrier affiche les minutes dans le système décimal, ainsi 8h5 s'affiche au lieu de 8h30. Est-il possible de modifier les paramètres du calendrier pour que les horaires de réservation s'affichent par défaut dans le système horaire (8h30 et non pas 8h5)? De plus je me demande si ce bug dans l'affichage des horaires n'a pas de conséquences sur le calcul des temps d'utilisation.
Merci pour votre aide

**Comment by osallou** [comment]
bonjour, sur quelle plateforme observez vous cela ?

**Comment by pgripon** [comment]
Sur la plateforme CCL3

**Comment by osallou** [comment]
dans le calendrier de réservation ? Je n'observe rien de tel.
Je vois des réserations à 10h30 , 10h15, 14h30, etc...

**Comment by pgripon** [comment]
Absolument! Ce qui est troublant c'est quand on clique sur le calendrier pour faire une nouvelle réservation: si on clique sur le premier quart de 8h c'est 8h0 qui s'affiche pour le début de la réservation mais si on clique sur le 2ème quart c'est 8h25 qui s'affiche pour le debut de la réservation, si on clique sur le 3eme quart c'est 8h5 qui s'affiche et, curieusement, 9h15 pour le dernier quart!

**Comment by osallou** [comment]
j'arrive en effet à reproduire le pb de heures de résa quand on clique sur les *quarts*
En revanche, à l'affichage des réservations, tout s'affiche bien.
Peut-etre avez vous tenté une résa sur le 3e quart sans vérifier les horaires proposés, ce qui explique l'afficher de 8h5

**Comment by pgripon** [comment]
J'arrive toujours à créer les réservations souhaitées. Néanmoins ça ne fait pas très clean qu'il y ait de tels horaires farfelus qui s'affichent quand on clique sur un créneau horaire particulier. On peut même faire des réservations avec des horaires farfelus comme réserver de -3h à -2h . Par contre pour ce qui est des minutes les possibilités vont de 0 à 59 ce qui est rassurant

**Comment by osallou** [comment]
pour les négatifs sur les heures, c'est assez simple à corriger

pour les crénaux bizarres, il faut investiguer, c'est plus compliqué

**Comment by pgripon** [comment]
Pour ce qui est des heures il n'y a pas que le problème des heures négatives mais se pose  aussi celui des heures dépassant 24 de même qu'il me semble que les horaires d'ouverture de la plateforme ne sont pas pris en compte

**Comment by osallou** [comment]
les heures d'ouvertures doivent être controllés lorsque la demande est soumise. rien n'empeche l'utilisateur d'entrer des horaires plus larges, mais normalement ils seront rejetés

**Comment by osallou** [comment]
j'ai corrigé le pb des heures <0 ou >23

**Comment by osallou** [comment]
Note:
hours mngt fixed in commimt b652a9d12e725402e71bb4ae0c1d7d4ad10743d5

**Comment by pgripon** [comment]
Pour ce qui est des heures d'ouverture de la plateforme j'ai entré 8h-20h dans le module de configuration du calendrier or je peux faire des réservations à n'importe quelle heure, elles ne sont jamais refusées sauf si l'heure de fin de réservation est avant l'heure de début de réservation. De plus j'ai fixé la résolution du bloc de réservation à 15 min mais je peux faire une réservation de 3 min, elle n'est pas refusée mais transformée en réservation de 15 min, ce qui n'est pas très transparent.  Dans l'idéal vu que la résolution est de 15 min il faudrait qu'il ne soit possible de choisir dans le calendrier des minutes que les valeurs 0; 15; 30; 45 ce qui est de toutes façons ce que fait le logiciel.

**Comment by osallou** [comment]
il n'est pas possible de limiter dans l'interface la valeur des créneaux lors du choix des horaires (hors min et max). Il n'est pas possible non plus actuellement de le limiter aux heures d'ouvertures.

Du moins, cela demanderait d'important développements. En cas de développements futurs il est néanmoins possible de créer une feature request....

Pour rappel, nous n'avons pas pour charge de faire évoluer le logiciel. Nous sommes simplement hébergeur et même si nous corrigeons à l'occasion quelques bugs cela ne fait pas partie du "contrat" :-)

Je vais investiguer sur les "quart" de réservation, car cela est très trompeur.

**Comment by osallou** [comment]
@pgripon  j'ai corrigé le problème des quarts de réservation, on a bien les bons créneaux maintenant

**Comment by pgripon** [comment]
@osallou  J'ai jeté un coup d’œil, effectivement l'affichage suite au clic est maintenant parfait. Du coup il n'y aura plus de raisons de modifier manuellement la valeur affichée. Merci, c'est bien mieux.! :-) En mode manuel il y a toujours un décalage entre les horaires sélectionnés et les horaires effectivement réservés mais du coup ça n'a plus qu'une importance négligeable.
