### ISSUE TITLE
Install with NGINX

### ISSUE THREAD

**Issue by ppouchin** [bgo-bioimagerie/platformmanager#127]
Hello, 

I'd like to install a local instance in Clermont-Ferrand.
However, my servers use NGINX and I'd like to forego Apache, if possible.

I noticed that the .htaccess has some rewrite rules, but I'm not sure I got it right.
I once managed to install it, but it didn't work (if I recall correctly), and nowadays, when I try to start over, I can't populate the database...

**Comment by osallou** [comment]
you should be able to adapt rewrite rules in nginx, which basically rewrite path for non static files (images, css etc...), I don't know syntax however.

What is your database issue?

**Comment by ppouchin** [comment]
How could I check that?

**Comment by osallou** [comment]
No adblock etc.. in your broswer? Or your nginx config, but default config would not block that.
Could check in dev tools of browser the request sent after login, to see if some cookies are sent.

**Comment by ppouchin** [comment]
I created a Debian Buster VM with Apache/PHP/Mariadb and followed the instructions found here: http://bgo-bioimagerie.github.io/platformmanager/install.html

PHP version is 7.3 (>5). Mod_rewrite should be enabled and .htaccess files are enabled. 
But apparently, I cannot get it to work, even with Apache. It doesn't go past the login screen. 

If someone is willing to check if something is wrong, the VM is available here: 
https://galaxy.gred-clermont.fr/~pouchinp/Buster.zip

The web server should be accessible on port 8080 of the host. (SSH on port 2222.)

**Comment by osallou** [comment]
cannot download... (403 forbidden)

**Comment by ppouchin** [comment]
Sorry for that. It should be ok now.




On Mon, Sep 23, 2019 at 2:58 PM +0200, "Olivier Sallou" <notifications@github.com> wrote:












cannot download... (403 forbidden)



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.







cannot download... (403 forbidden)

**Comment by osallou** [comment]
I am investigating but definitly looks like a session/cookie issue. Login is "fine" and session is created. Though when redirected session is not found or invalid.
Wonder if related to PHP 7 config/setup issue. We are with older PHP versions.

**Comment by osallou** [comment]
@ppouchin I could fix the issue

Under /var/www/pfmanager you need to create a directory tmp with write access to www-data (for your vm, would be your apache/nginx user on other install and tmp dir would be in root pfmanager install dir)

Seems this directory is not created by default. It saves sessions here.

Doc need to be updated or script should create it at startup

**Comment by osallou** [comment]
Fixed doc  in commit e865878

**Comment by ppouchin** [comment]
Thank you! 
It now works with both Apache & Nginx. 
We will thus be able to try "platformmanager" to check if it fits our use cases.
From what we saw last year in MiFoBio, we were hopeful it would.
