### ISSUE TITLE
Pb csv pour les projets H2P2

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#128]
Bonjour, 
Lorque que l'on va dans prestation, que l'on ouvre un projet en cours(EX rebillard Amélie)
Lorsque l'on va dans suivi d’un projet et que l’on exporte celui ci en CSV, 
-la quantitéé se trouve dans la colonne prix 
-le prix pour le multiplex n’est pas bon, 
-le total HT est faux 
Par contre lorsque l’on fait facturer,  le bon tarif est fait
 

 

 

La

**Comment by osallou** [comment]
this bug will be in stand-by , waiting for someone available to work on this

**Comment by osallou** [comment]
@Pbellaud, j'ai jeté un oeil rapide sur l'export csv de ce projet.
Pour moi, la quantité est dans la bonne colonne, et le total est correct.
Pour le prix multiplex je ne sais pas car je ne suis pas allé voir le détail.

J'ai ouvert le csv ds libreoffice Calc en utilisant le ";" comme séparateur.

**Comment by osallou** [comment]
Les multiplex ont un type special dans les prestations (type = Prix) , les autres ont le type Quantité.
Dans l'export, dans ce cas précis (type=prix), le prix unitaire affiché correspond à la quantité choisie,et la quantité est mise à 1.
Je ne sais pas à quoi correspond vraiment ce type, mais c'est ainsi que fonctionne le logiciel.
