### ISSUE TITLE
changement adresse e-mail

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#131]
bonjour,
une utilisatrice ne parvient pas à se connecter parce qu'elle ne se souvient pas de son mot de passe et ne reçoit pas le mail si elle demande un changement de mot de passe. Elle a vérifié dans les spams. Est ce qu'il est possible pour vous d'intervenir dans la base de données pour changer son e-mail?
merci

**Comment by osallou** [comment]
merci d'envoyer son id et mail sur notre mail de support

**Comment by sdutertre** [comment]
est ce que tu peux me redonner le mail de support, STP.

**Comment by osallou** [comment]
support@genouest.org

**Comment by osallou** [comment]
email modifié
