### ISSUE TITLE
urgent - pb affichage page acceuil

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#133]
Bonjour,
en voulant tester les outils de communication de platform manager, j'ai demandé à mettre la page de com en page d'accueil. Grosse erreur! je n'ai plus du tout accès aux outils de gestion de platform manager ou de réservation. ma page d'accueil me met uniquement les outils de communication et je ne peux pas corriger cela. 
![PF](https://user-images.githubusercontent.com/19782757/73747543-f36daf00-4757-11ea-8ce8-7a1b780f325b.png)

**Comment by osallou** [comment]
il doit y avoir moyen d'accéder à la page de gestion en entrant directement la bonne url, si tu l'as dans ton historique de navigation.

**Comment by osallou** [comment]
si je me loggue, dans la config, dans "Utiliser la page d'actualité comme accueil de l'espace" pour Com, la valeur est à non

**Comment by sdutertre** [comment]
c'est bon. j'ai réussi à corriger le problème en allant directement à l'adresse .../comconfig/1

**Comment by sdutertre** [comment]
merci pour ta réactivité. J'ai eu un petit moment de panique :)
