### ISSUE TITLE
Platform manager offline?

### ISSUE THREAD

**Issue by xavpinson** [bgo-bioimagerie/platformmanager#134]
Hello,

We are currently unable to access platform-manager. We are getting an error page "It seems like there is an issue accessing this service".
Thanks for your help. 

Xavier

**Comment by OlivierCollin** [comment]
We are experiencing some network problems having major impacts on our infrastructure. 
The crisis seems to be over and the GenOuest team is restarting progressively the different services.

**Comment by OlivierCollin** [comment]
PFM is back online. 
Let us know if you notice weird things... 

Best regards, 
Olivier

**Comment by xavpinson** [comment]
Great, thanks! :)
