### ISSUE TITLE
Collective emails

### ISSUE THREAD

**Issue by xavpinson** [bgo-bioimagerie/platformmanager#135]
Hello,
This concerns the email/courriel function of platform-manager.
Currently, we are able to send collective emails to the all users of a resource, of a domain or to all. This last option sends an email to all the user of all the platforms and we would like to be able to send emails to all the users of MRic-Photonics.

Is it doable to have an option to only send emails to all the usersq of a given platform?

Thanks a lot for your help,

Xavier

**Comment by osallou** [comment]
this is indeed a **must have** .....
and I think it should not be an option but replace the "send to all users" by "send to all the platform users"

by the way, there are also lots of undelivered email (pb to send to all with old users).....

Now, about feasibility, this needs some development. I will investigate about impact.
If it is a "small" patch, will do. Else it is out of scope for us (though in theory even small patches are out of scope....)

**Comment by osallou** [comment]
**warning** should check that a space owner cannot send email to **all** users but only users of the platform
