### ISSUE TITLE
erreur email 

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#136]
Bonjour,
au cours de la création d'un utilisateur, une erreur s'est glissée dans le mail (il manque le s de rennes). Je ne peut plus changer le mail et du coup l'utilisateur n'a pas reçu son mot de passe. Est ce qu'il y a moyen de corriger cette coquille. 
Numero d'identifiant : 1146
merci

**Comment by osallou** [comment]
je peux voir pour changes l'email dans la database, mais le mot de passe ne sera pas renvoyé.
Mais j'imagines qu'il peut faire un reset de mot de passe après coup

**Comment by osallou** [comment]
c'est modifié en base de données

**Comment by osallou** [comment]
j'ai lancé le "reset", il devrait avoir reçu par email un nouveau mot de passe

**Comment by osallou** [comment]
@sdutertre est ce ok?
