### ISSUE TITLE
erreur dans la facturation

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#139]
Bonjour,

nous avons des problèmes pour le décompte des heures pour la facturation. Une utilisatrice #899 était dans un premier temps relié au compte "Tramier". Elle a changé d'équipe et est maintenant relié au compte client "salbert". Des heures sont tout le temps facturées à son ancien compte client (son profil est correct). Je peux vous envoyer les pdf des factures en message. Si je calcule les statistiques de réservation de cette personne, toutes les heures réservées sortent et je pense que les heures réservées et annulées ne sont pas enlevées des statistiques. 
Merci pour votre aide
Stéphanie

**Comment by osallou** [comment]
Quelles heures sont facturees sur l'ancien compte?
Merci d'envoyer les factures sur notre email de support

**Comment by osallou** [comment]
en regardant les reservations de cet utilisateur, ils ont tous une facture, sauf bien sur les reservations annulées.

quelle facture est problématique sur l'ancient compte client?
Je vois bien une facture à priori liée (id facture=1803, générée le 25/05), générée le mm jour pour le vieux compte et le nouveau compte client (id facture=1804, générée le 25/05 aussi).

La facture pour l'ancien compte concerne des reservations du 08 au 25 janvier.
