### ISSUE TITLE
supression d'un compte utilisateur

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#141]
Bonjour,
par erreur, nous avons créer deux comptes utilisateur pour une même personne (#1169 et #1171). Cela ne semble pas poser de problèmes de conflit mais je préfère que vous supprimiez le compte utilisateur #1169.
merci
Stéphanie (BIOSIT/PF MRic-photonics)

**Comment by osallou** [comment]
c'est fait
