### ISSUE TITLE
Template invoices

### ISSUE THREAD

**Issue by PhilippeH44** [bgo-bioimagerie/platformmanager#143]
Bonjour et bonne année à tous.
Ici MicroPICell à Nantes. Nous utilisons PM depuis le début et nous en sommes très content.
Mais aujourd'hui j'ai besoin de votre aide concernant le modèle de facturation. 

Chemin :
->configuration  ->invoices  ->modèle de facture HTML-PDF

Impossible de charger un nouveau modèle. Ni en PHP, ni en HTML.

Le upload se passe bien mais le modèle reste l'initial.
Pouvez -vous nous aider?
Merci d'avance

**Comment by osallou** [comment]
de quelle plateforme s'agit-il je ne vois pas de micropicell

**Comment by OlivierCollin** [comment]
C'est une autre instance sur Nantes. D'ailleurs, je crois qu'il s'agit d'une autre version de Platform Manager

**Comment by PerrineGilloteaux** [comment]
Bonjour Olivier et Olivier (et bonne année!) , c'est bien la meme version , on a refait le déploiement depuis le git Hub sur un serveur à Nantes, comme convenu en 2019 avec Olivier Colin et Biogenouest, de manière a synchroniser les versions, simplifier la gestion et alléger votre serveur. C'est Jean-Francois Guillaume de la SFR sur Bird qui s'occupe de faire les mise à jour. Pour rephraser la question de Philippe: est-ce que vous pouvez reproduire le probleme sur votre instance? i.e uploader un nouveau modele de facture, par exemple en changeant l'adresse email?   Si oui, bug dans le code, soit non pas de souci chez vous, pb peut-etre de config des droits d'acces chez nous, si vous nous pointez le code, et l'emplacement eventuel d'un log d'erreur on verra avec Jean-Francois.

**Comment by osallou** [comment]
faut qu'on essaye sur notre instance de test

**Comment by PhilippeH44** [comment]
Bonjour, 
avez-vous pu reproduire notre problème sur votre instance?
Merci

**Comment by osallou** [comment]
c'est ds la todo list... ;-)

**Comment by osallou** [comment]
* j'ai fait un test basique (invoiceedit) pour voir le pdf de la facture
* j'ai téléchargé le template actuel , je l'ai modifié et uploadé
* je regarde à nouveau le pdf, et mes modifs apparaissent

**Comment by PerrineGilloteaux** [comment]
@osallou  merci de ce test! pouvez vous juste confirmer la version déployée sur votre instance?

**Comment by osallou** [comment]
Aucune idee, c est notre version de test, logiquement c est la derniere version du code. @abretaud ?

**Comment by PerrineGilloteaux** [comment]
Bonjour, pour info @PhilippeH44 a posé la question de la migration vers la nouvelle version car effectivement nous en avons une ancienne, voici les infos si ca peut vous etre utile : Bonjour Jean-François, @hulin-p a posé la question à Sylvain Prigent, le développeur de l'application, voici sa réponse:

Je n'ai pas suivi les évolutions de Platform-Manager depuis avril 2018, mais en regardant le dépôt GitHub, les changements ne semblent concerner que du « bug fix  »

Pour faire les mises à jours de Platform Manager, il y a un mécanisme de mise à jour de la base de données lors de chaque mise à jour en appellent l'url « coreupdate ». 
Donc pour faire une mise à jour, il faut:
	1- remplacer le code sur le serveur par la nouvelle version du code
        2- faire la mise à jour de la base de données en appelant « coreupdate ». Si je me rappelle bien, il doit y avoir un bouton dans l'interface admin du module core pour appeler cette url.
Normalement, il n'y a pas besoin de faire la mises à jour de la base de données pour les commit d'après mai 2018 car il n'y a plus eu de grosses mises à jour.


Par contre effectivement, il faut le faire lors du passage à chaque nouvelle version. 
Comme je n'utilisais pas les tags de versions (car des évolutions trop nombreuses) le seul moyen de trouver la version que vous avez est de retrouver le numéro de commit. Normalement lors de l'installation nous avions utilisé Git donc avec un peu de chance vous pouvez retrouver l'ID du commit (ou sinon avec la date des fichiers sur le serveur vs dates de commit sur GitHub), et ensuite faire les mises à jour avec les commit suivants.

Le point critique est une mise à jour que j'avais fait début 2018 (https://github.com/sylvainprigent/platformmanager/commit/73cc200d18db80131d92bf52ca8b262f587374a7) qui permettait d'avoir un identifiant de facturation unique pour un utilisateur (cad partagé par plusieurs plateformes).  Ce sont les modules « client » et « users » qui remplace le module « ecosystem ». Pour cette mise à jour il devait y avoir un script dédié pour recopier les données de « ecosystem » vers les nouveaux modules. En parcourant le GitHub, je pense que c'est ce patch: Modules/users/Model/UsersPatch.php. je ne sais plus si il est appelé automatiquement avec coreupdate ou s'il faut l'appeler manuellement.

En espérant que ces informations puissent aider.

a+
Sylvain




Salut Sylvain,

j'espère que tu portes bien et que tout va bien pour toi.

Je te contacte pour un renseignement concernant Platform Manager.

Je sais que tu ne t'occupes plus de cela mais nous sommes dans l'impasse et tu es le seul qui pourrait nous sauver.

L'instance de Nantes n'a a priori jamais mis à jour depuis environ 3 ans. On ne sait pas trouver le numéro de version de notre instance.

La personne qui s'occupe de Platform Manager à Nantes n'arrive pas à installer la dernière version car il y a un trop grand écart entre notre version et la version disponible sur Github.

Penses-tu qu'il y a une solution pour mettre à jour notre instance malgré notre retard de version?

L'autre solution serait d'écraser notre vieille version pour installer une instance toute neuve, mais nous avons du mal à anticiper la perte de données voire des databases. On a un peu peur!

Merci Sylvain pour ton aide si tu a le temps.

En espérant te revoir bientôt

Philippe
