### ISSUE TITLE
[roles] Setting user role to inactive within a space

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#167]
When  selecting "inactive" in the list of roles in user access page within a space (http://{host}/coreaccessuseredit/{space_id}/{user_id}), it doesn't impact is_active data for the selected user in  core_users table in database.
Therefore, a user is always active.

**Comment by osallou** [comment]
User can be inactive at user level, or inactive at space level.

In user config for a space, inactive should update his role, but not user object itself, so this is correct.

User will be set as inactive by admin or after a period of inactivity

**Comment by gaetanHerve** [comment]
Ok. So the confusion may come from the fact that selecting "Inactive" in the sidebar of users module will display users inactive at the user level, not at space level. But I suppose what we really want to do is display active/inactive users based on their role in space, not on their is_active property...

**Comment by osallou** [comment]
We should, in any case, see only space users in space user module.

Inactive users should be space level inactive users.

If user is inactive, should be a superadmin issue.

**Comment by osallou** [comment]
looking at code for corespaceaccess usersinactif , inactive users are users with status=0 in the space (inactive), and will show only users with a core_users.is_active=1 and core_users.validated=1

**Comment by osallou** [comment]
so if user is inactive at global level, he won't appear anymore

**Comment by osallou** [comment]
but when user is inactive *global*, it is expected to be removed from spaces, so that's fine

**Comment by gaetanHerve** [comment]
yes, I think we can close this issue then
