### ISSUE TITLE
menu board - limited

### ISSUE THREAD

**Issue by mnivard** [bgo-bioimagerie/platformmanager#168]
désolé je le fais en francais
en super admin 
au fur et a mesure que l'on ajoute des menu/sous/menu/item /espace
le menu s'élargit vers le bas 
lorsque que c'est le cas c'est bloquant pour accéder aux config d'espace qui se trouve en dessous et donc non accessible
je vous fais un imprim ecran sur le training pour vous montrer
![Capture](https://user-images.githubusercontent.com/10153480/122216269-7bb3a680-ceac-11eb-8fc0-061df96b919b.JPG)

**Comment by mnivard** [comment]
donc sur l'imprim ecran si je veux ajouter un menu je ne peux plus car le bouton ajouter en sous le menu :-)

**Comment by osallou** [comment]
Css issue
