### ISSUE TITLE
Mail: from should be space name related

### ISSUE THREAD

**Issue by osallou** [bgo-bioimagerie/platformmanager#172]
The from name in mail should relate to space name when sent from a space context , else defaults to platform manager (current value)

The from email should be:

* mail_from in superadmin context
* space support email in space context if space defines one
* else xxx+spaceshortname@domain in space context, the xxx and domain coming from *mail_from* global config (test@pfm.org transforms to test+spacex@pfm.org for example)

**Comment by osallou** [comment]
Framework email manage this

Check all email calls to use this

**Comment by osallou** [comment]
Linked to #170

**Comment by gaetanHerve** [comment]
@osallou  solved with #188 ?

**Comment by osallou** [comment]
Should be
