### ISSUE TITLE
[db fetch] warnings thrown when fetching data

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#183]
**Several tries to access to 1st index of variables which value is false**
Doesn't generate bugs. Cases handled in controllers.

Example case :
We want to create a new module :
* we access to module configuration menu (url = {host}/{module_name}config/{id_space})
* then, in dev mode, warnings are thrown : "trying to access array offset on value of type bool"

The cause is that, in model classes, some functions try to access to $anArray[0] even if $anArray = false.
In the following example, if we haven't configure the module yet ($url stands for module name), there is no matching data in database, then $req = false and $req[0] throws a warning :

*in Modules/core/Model/CoreSpace.php line 196*
```
public function getSpaceMenusColor($id_space, $url) {
        $sql = "SELECT color FROM core_space_menus WHERE id_space=? AND url=?";
        $req = $this->runRequest($sql, array($id_space, $url))->fetch();
        return $req[0];
    }
```

**Comment by osallou** [comment]
Do not appear in prod mode, but should be fixed anyway
