### ISSUE TITLE
[Modules] Impossible to deactivate module / save modifications on some module settings

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#193]
* When trying to deactivate a module passing by space Admin configuration / edit and setting module to inactive, module is still visible
* In this same screen, some modifications in are not taken into account when saving it

**Comment by osallou** [comment]
Space menus seem to be selected with:

    SELECT * FROM core_space_menus WHERE id_space=? AND user_role<=?

When set to inactive, user_role is set to 0. Maybe query should be user_role > 0 AND user_role<=?

**Comment by osallou** [comment]
Yeap, php8 breaking change

https://www.php.net/manual/en/migration80.incompatible.php

**Comment by osallou** [comment]
So need to check in other places...

**Comment by gaetanHerve** [comment]
So it works well when specifying user_role > 0 AND user_role<=? in CoreSpace->getSpaceMenus(), that solves the menu deactivation issue.
But the modification of module settings (same pages, but different treatments) still won't work.
In fact, it concerns CoreConfig.php, which can add new parameter lines in core_config table but is unable to fetch these new parameters. I'm looking forward to it.

**Comment by gaetanHerve** [comment]
Even if this works, each time user displays or updates a setting, request SELECT * FROM core_spaces WHERE id=? is launched several times. It is due to multiple calls to loadParams() function by others from the same class (CoreConfig.php). We could rationalize that (another issue ?)

**Comment by osallou** [comment]
Don t think so. Should be checked, but i think it is called in different config (space config itself, but also access control etc.. )

**Comment by osallou** [comment]
As long as "edit" op works, we can just an other issie low prio, just to check
