### ISSUE TITLE
[Client pfm2] Can't create client

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#194]
When trying to create a new client, when submitting the 1st form (this action normally redirects to "address invoice" form) :
* in dev mode, warning messages appear
* client is not recorded in database

_warning messages:_

Warning: Trying to access array offset on value of type bool in /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php on line 95

Warning: Trying to access array offset on value of type bool in /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php on line 96

Warning: Trying to access array offset on value of type bool in /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php on line 97

Warning: Trying to access array offset on value of type bool in /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php on line 98

Warning: Trying to access array offset on value of type bool in /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php on line 99

Warning: Trying to access array offset on value of type bool in /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php on line 101

Warning: Trying to access array offset on value of type bool in /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php on line 102

Warning: Cannot modify header information - headers already sent by (output started at /var/www/platformmanager/Modules/clients/Controller/ClientslistController.php:95) in /var/www/platformmanager/Framework/Controller.php on line 132

**Comment by osallou** [comment]
Warnngs due to unitialized object in form, acczpted but not cool...

Message error with redirect is i think due to a redirect with missing *return* after (found issue in other places)

For object not saved, don t know, but there may be an sql error log on server side

**Comment by osallou** [comment]
@gaetanHerve it works on current version? (Is issue related to php upgrade)

**Comment by osallou** [comment]
In Model/ClClient.php, the set method  tests ($id == 0) but for new clients, $id is empty string, should test:

    if(!$id) { ...

Furthermore, at creation in editAction (ClientslistController), if client does not exists, form is setup with a null object ( $client = $this->clientModel->get($id); )

Same for clientModel->get($id) , the get method checks for $id==0 instead of !$id

**Comment by osallou** [comment]
cf issue #195 with tentative branch code fix_php8_comparison

This affects in several places get et set. I propose to merge this branch if you're fine with this, will fix client issue.

**Comment by gaetanHerve** [comment]
I'm totally fine with this. I let you do the merge.

**Comment by osallou** [comment]
Merge, i let you merge pfm2 branch in your branch to benefit from changes and see if there are other client issue. Else you can close this issue.

**Comment by osallou** [comment]
Creation should work and warnings should disappear
