### ISSUE TITLE
[Date formats / I18N] variable date formats

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#200]
There are some issues regarding to the date format relatively to the language.
* if language === "fr", dates should always be formatted like "dd/mm/yyyy"
* if language === "en" dates should always be formatted like "yyyy-mm-dd"
Some errors could occur from this rule not being systematically followed.

**Comment by osallou** [comment]
format expected on UI side, and translator dateToEn should be used to format *all* dates to YYY-MM-DD

**Comment by gaetanHerve** [comment]
Yes, I should have specified "on UI side".

The principal issue came from the fact that in this case (which I found out it can happen in the actual app) :
* user language is set to "en",
* date is in french format ("dd/mm/yyyy"),
dateToEn() doesn't reformat date to english format.

This case is solved with MR #190 but we should nevertheless check if date formats are correct on UI side to avoid potential anomalies.

**Comment by OlivierCollin** [comment]
Just a naive comment. 
I see you mentioning french and english date format. 
The Platform Manager system does not use the ISO 8601 date format ?

**Comment by osallou** [comment]
So naive... of course not, too simple.
Why not a timestamp, would be too universal and less fun

;-)

**Comment by osallou** [comment]
And do not expect timezone support
