### ISSUE TITLE
[Modules configuration] Some modules names can be edited, some others can't

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#220]
When accessing to a module configuration, for some modules, the *name* field doesn't display (*e.g.* in *com* and *resources* modules)

**Comment by osallou** [comment]
Won t be milestone 20, frozen.
Will be 2.1

**Comment by gaetanHerve** [comment]
Behaviour ok to me : it's useful that some module names can't be changed (i.e. invoices or resources). It helps to keep the same words for the main concepts.
