### ISSUE TITLE
[UI][Flash messages] Some flash messages displaying on the wrong screens 

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#224]
Happens (only?) when a screen wont display (eventually when a bug occurs) and  $_SESSION["message"]  has already been set.
Since  $_SESSION["message"] is normally unset by the view, if the view is not generated, flash message won't be unset until being called by another view => can cause some confusions on the user side.

We should find a way to avoid that (try / catches when generating views with an unset for  $_SESSION["message"] inside the catch? => could be set generically in the framework).

**Comment by osallou** [comment]
Setting in render method an unset of session message would clear it in all cases, after page render of course.

**Comment by gaetanHerve** [comment]
Moments flash messages won't display (to be completed as we meet the cases):
- after client creation or user-to-client association
- ...

**Comment by gaetanHerve** [comment]
Seems to be solved (I've not seen this type of problem recently)
