### ISSUE TITLE
[pfm2][Services][Fix security] Should services types be common to all spaces?

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#227]
Like other model classes, SeServiceType.php was modified in PR fix_security_196 in order to integrate space ids.
But it appears that the data is not thought to be created, updated nor deleted by users (no interface for that). Sylvain only planned to have 6 fixed types so that services can use it.

Needs to be solved before upgrade 2.1.

```
public function createDefault($id_space) {
        $this->add($id_space, "Quantity", "Quantité");
        $this->add($id_space, "Time minutes", "Temps en minutes");
        $this->add($id_space, "Time hours", "Temps en heures");
        $this->add($id_space, "Price", "Prix");
        $this->add($id_space, "Half day", "Demi journée");
        $this->add($id_space, "Journée", "Journée");
    }
```
Unless we want to make it editable by users, I think we should remove the $id_space parameter from this class and add lines in db at creation (_cf._ code block above) only if it doesn't exist. I'll keep that opened waiting for further advice.

**Comment by osallou** [comment]
Service types should anyway be linked to a space (for possible later
updates, debugging etc...)



Le ven. 23 juil. 2021 à 10:39, gaetanHerve ***@***.***> a
écrit :

**Comment by osallou** [comment]
If not created in db at all, id space could indeed be removed from params.

(But what is purpose of service type if not in db?)

Le ven. 23 juil. 2021 à 10:39, gaetanHerve ***@***.***> a
écrit :

**Comment by gaetanHerve** [comment]
I suppose (I'm gonna investigate on that next week, I have the intuition there could be some use case complexity behind that) it has something to deal with services invoicing. So a service would have to have a service type amongst a limited list of fixed choices. Could be some sort of "static" table in db though.

**Comment by osallou** [comment]
But if fixed and not editable, why in db? Why not just in code?

Id space could indeed be removed from modem methods if list is not space related.

CreateDefault method is called at install/upgrade time

**Comment by osallou** [comment]
In serviceinstall, i see that createdefault() is commented, so not created at install/upgrade....


We need to see where service types are created and their usage

**Comment by osallou** [comment]
Seems i commented createdefault in servicesinstall  as it is not commented in master branch, an error i suppose, it should be uncommented
And id_space can be removed from servicetype model and calls
