### ISSUE TITLE
Erreur sur la facturation - v2.0

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#245]
Bonjour,
je viens de tester la facturation sur la version 2.0 et j'ai ce message qui apparait:
Error: count(): Argument #1 ($var) must be of type Countable|array, int given
J'ai le même message si je fais "facturer tout" ou "facturer un responsable".
merci
Stéphanie

**Comment by osallou** [comment]
Ok, je vais regarder cela
On a deja eu le pb ailleurs.

La version de php utilisee est plus exigeante que la precedente, qui laissait passer des erreurs, mais olus maintenant....

**Comment by osallou** [comment]
Peux tu preciser sur quelle page/bouton cela arrive?

**Comment by osallou** [comment]
@sdutertre corrigé et mis en prod

**Comment by sdutertre** [comment]
super merci.
