### ISSUE TITLE
Invalid type for year

### ISSUE THREAD

**Issue by osallou** [bgo-bioimagerie/platformmanager#260]
TypeError: mktime(): Argument #6 ($year) must be of type ?int, string given File "/Modules/booking/Controller/BookingController.php", line 396, in mktime $dateBegin = mktime(0, 0, 0, $dateArray[1], $dateArray[2], $dateArray[0]); File "/Modules/booking/Controller/BookingController.php", line 396, in BookingController::dayareaAction $dateBegin = mktime(0, 0, 0, $dateArray[1], $dateArray[2], $dateArray[0]); File "/Framework/Controller.php", line 59, in Controller::runAction call_user_func_array(array($this, $actionName), $args); File "/Modules/core/Controller/CoresecureController.php", line 120, in CoresecureController::runAction parent::runAction($module, $action, $args); File "/Framework/Router.php", line 149, in Router::runAction $controller->runAction($urlInfo["pathInfo"]["module"], $action, $args); ... (2 additional frame(s) were not displayed) 

Request

URLhttp://pfm.genouest.org/bookingdayarea/1
Method GET
Query path=bookingdayarea%2F1

**Comment by gaetanHerve** [comment]
In several cases, mktime() is called with invalid arguments. It appears it often has to deal with the absence of default values. cf #297
