### ISSUE TITLE
[EMAIL][SUPPORT] Receiving emails at Genouest support when users request to join a new space

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#265]
I've noticed that we receive emails at support when users request to join Arche, MRic and H2P2 spaces.

In configuration, "smtp_from" is set to our support email address. It is used in ''Email::notifyAdminsByEmail()''. By default in this case, sender is CC of the email.

Consequently, receive unnecessary emails at support. Is that intentional ?

**Comment by osallou** [comment]
Yes and no, will be fixed next release

By default, superadmin user is added as admin of space, consequently he receices emails

Next release will remove superadmin from space admins

**Comment by osallou** [comment]
If origin is platform itself, and not a space manager/admin, there is no reason to cc the sender.
Cc to sender is not an option?
