### ISSUE TITLE
[Booking settings] Scheduling options won't save

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#270]
When trying to set specific days or hours for an area by selecting it in booking settings > scheduling, clicking "save" hasn't any effect.

**Comment by osallou** [comment]
Not a sql issue? What are log errors?

**Comment by gaetanHerve** [comment]
Sorry, I hadn't seen your comment before. I just pushed a fix. That was mainly an sql issue linked to a confusion beetween "resource area" id and bkScheduling id. I tried to clarify that. It's working on MR #271.
