### ISSUE TITLE
[flash messages] Replace use of  local flash messages by use of general flash integrated in Modules/layout.php

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#276]
Fixing some issues, I had to add error messages to editAction.php or indexAction.php files (for example) in different modules.
It's tedious and unharmonised. We should factorize it.

**Comment by osallou** [comment]
General layout supports a flash object in render

[ ..., "flash" => [ "class"="warning", "msg"=> "blabla"]

Display flash msg with bootstrap level on top of page
