### ISSUE TITLE
remove users from "compte client"

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#279]
Bonjour,

Je viens de détecter un bug (platform MRic-photonics, BIOSIT). Quand je veux mettre à jour un compte client et lui enlever des utilisateurs, j'ai ce message d'erreur:
Unknown named parameter $id

Stéphanie

**Comment by osallou** [comment]
c'est déjà corrigé ;-)
on attends que pfm soit "libre" en prod pour faire la mise à jour

**Comment by osallou** [comment]
la prod a été mise à jour

**Comment by osallou** [comment]
merged commit 0ddb17bfae7aac7e20352830d05b598fc96a83df

**Comment by sdutertre** [comment]
Bonjour,
est ce que cela signifie que cela marche maintenant sur ma version? J'ai toujours le message d'erreur à l'instant.

**Comment by osallou** [comment]
hum, cela a été corrigé mais il semble y avoir un probleme de "build", je regarde çà

**Comment by osallou** [comment]
@sdutertre  

ok, il fallait forcer le rechargement des "routes" après l'install, cela a été corrigé, cela devrait être bon maintenant

**Comment by sdutertre** [comment]
j'ai pas tout compris mais cela marche maintenant.
merci

**Comment by osallou** [comment]
Pas besoin de tout comprendre ;-)
Mais je prefere expliquer le pb pour tracer ce qui ne va pas
