### ISSUE TITLE
[PFM homepage] create a common generic homepage ?

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#294]
Bonjour,
depuis hier, quand on se connecte à l'adresse habituelle (https://pfm.genouest.org/) on est redirigé vers la page "Creaah".
Cela nécessite une manip supplémentaire qui est d'aller dans l'onglet menu et choisir biosit
Stéphanie

**Comment by osallou** [comment]
@gaetanHerve tu jettes un oeil ? Je soupconne un utilisateur admin qui a changé des "defaults"

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,

C'est "normal". C'est un défaut d'ergonomie qui a toujours été présent: tout le monde est dirigé sur une même page à l'accès à Platform-Manager. Jusqu'à présent il s'agissait du menu Biosit mais j'ai créé hier un nouveau menu pour le Creaah, qui est passé en "1er menu".
Il faudrait dans l'idéal que chacun⋅e puisse définir son menu d'accueil ou que l'on ajoute une page d'accueil répertoriant les différents menus. (j'en profite pour renommer l'issue en ce sens).

Dans l'immédiat, j'ai repassé Biosit en 1er (plus pertinent car beaucoup d'utilisateur⋅rice⋅s).
