### ISSUE TITLE
[UI] Add progress bars

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#307]
Some processes take a large amount of time (up to 30 minutes when generating global balance statistics for a space with many clients and reservations).
We should display progress bars (page independent?)  while processing.

partly solved with PR #547 
will be completed with PR #551

**Comment by osallou** [comment]
should be background task and check for file generation status, displaying current status (and refresh)

**Comment by gaetanHerve** [comment]
Not needed anymore since asynv stats, async invoice and pagination where added
