### ISSUE TITLE
Facturation prestation H2P2

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#329]
![image](https://user-images.githubusercontent.com/39952219/136811846-663244ed-c0cc-4f57-89f1-6f18a48533fd.png)

**Comment by osallou** [comment]
quel est le pb??

**Comment by gaetanHerve** [comment]
Cause trouvée dans ServicesinvoiceprojectController::generatePDFInvoice() (~ line 423)
```
if($quantity == 1){
   $quantity = "";
    $unitPrice = "";
}
```
??? reste à comprendre pourquoi c'est là...
