### ISSUE TITLE
H2P2

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#332]
Pour un utilisateur, Florence Jouan , 
elle a perdue toutes ses habilitations et lorsqu'elle veut réserver,
 elle a accès  à qq équipements mais tous ceux pour lesquels elle était habilitée
 ( un seul scanner sur les deux- pas d'accès microtome, macroscopie...)
![image](https://user-images.githubusercontent.com/39952219/136936767-0c7e30e6-33f4-4bf2-8f78-6ddb621be9a7.png)

Merci

**Comment by osallou** [comment]
bonjour,
si elle a perdu ses habilitations, une opération quelconque sur son compte a dû être effectuée avant.
A-t-elle quitté l'espace ? modification du user ?

**Comment by osallou** [comment]
ok, il semble que ce soit un pb de migration de la base de donnée

pour gaetan:
 bk_authorization.resource_id est lié à re_category et non re_info....
il faut voir comment corriger cela

**Comment by sdutertre** [comment]
merci
