### ISSUE TITLE
[projects] Improve project management tools

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#373]
...along with stocks management => too specific

**Comment by osallou** [comment]
* project can be public (can be viewed by user/customer) or private (space managers only)
* project have tasks (not for invoices) and services (for invoices). A service can be linked to one or many tasks.
* task can be public (user/customer can view them) or private
* a task is  something to do (start/closed date, assignee, due-date)
* a task can have comments
* a comment (simple text) can be public or private
* public task can be assigned to a user, in this case user can edit task status and add comments
