### ISSUE TITLE
[BUG] creation d'un nouveau compte utilisateur

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#396]
Bonjour,
 je viens de créer un nouveau compte utilisateur (platform manager Mric-photonics) mais je ne retrouve pas la trace de ce nouveau compte (pas dans compte en attente d'activation, ni dans utilisateurs actifs ou inactifs). 
Et en fait, je viens de me rendre compte que la base de données utilisateurs est vide. Les deux problèmes sont sans doute liés.

**Comment by osallou** [comment]
il semble y avoir un pb en effet

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,

Après une première vérification, les utilisateurs ne sont pas perdus, c'est un problème d'affichage de la liste dans le menu users (idem pour les autres espaces).
On regarde ça.

**Comment by osallou** [comment]
ok, les users apparaissent à nouveau, pb suite à la derniere mise à jour (oubli de maj de la db)

**Comment by osallou** [comment]
pour le user, je ne sais pas si il a pu etre créé en revanche

**Comment by osallou** [comment]
je vois qq ds les pending d'aujourd'hui

**Comment by osallou** [comment]
Note for devs:  after upgrade, a repair--bug 371 was needed.... (cf changelog)

**Comment by sdutertre** [comment]
C'est bon. Je la retrouve dans les comptes en attente d'activation.
merci

**Comment by sdutertre** [comment]
Désolé, elle était dans les comptes en attente d'activation mais en l'activant je l'ai de nouveau perdue (pas de traces dans les users actifs ou inactifs).

**Comment by osallou** [comment]
je vois dans la basele user associé à l'espace, je cherche pourquoi il n'apparait pas

**Comment by osallou** [comment]
@sdutertre le pb est corrigé sur l'instance, il nous reste à corriger "proprement"

**Comment by osallou** [comment]
fixed in 2.1.9 and 2.2 #e1d04792e6a16fbf69a7645e55c7fbf71470a843

**Comment by osallou** [comment]
@sdutertre nous avons des pb avec notre gateway mail (rien a voir avec pfm c est un pb global), donc l utilisateur ne recevra pas encore le mail avec son mot de passe.
Il faudrait donc que tu lui envoies directement.

**Comment by sdutertre** [comment]
par contre, je n'ai pas du tout accès aux mots de passe créés

**Comment by osallou** [comment]
Ca c est normal... mais c est toi qui l a choisit ;-)

Si tu ne t en rappelle pas je oeux esssayer de trouver le mail en question (il n est pas perdu, juste bloque sur serveur de mail)

**Comment by osallou** [comment]
Je lui forwarde le mail directement
