### ISSUE TITLE
[DOC] Manage booking of interdependant resources

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#404]
Use case raised by Marion Chorin (Ecochim):

"Nous souhaitons utiliser pour la facturation les relevés automatiques selon les ressources qui ont été réservées dans le calendrier de réservation.
Nous ne facturons pas au type d'appareil utilisé ("mise à disposition" mais à l'analyse effectuée avec l'appareil, donc sur 1 seul appareil, plusieurs analyses différentes peuvent être effectuées. Ainsi, pour pouvoir facturer chaque analyse, nos "Resssources" correspondent à nos analyses, et nos "Catégories" sont les appareils, ce qui est parfait puisque les visas d'habilitation sont donnés par Catégories.
Le souci, c'est que dans le calendrier de réservation,  deux personnes peuvent réserver 2 analyses différentes au même moment sur le même appareil.
Ce que nous aimerions donc, c'est que lorsqu'une ressource est réservée, cela bloque le créneau pour toutes les autres ressources de la même catégorie..."

Having a booking blocking an entire category or other resources could be too specific. We should brainstorm on this issue.

**Comment by osallou** [comment]
idea: resource with price = 0 , and consumables = different types of analyse that could be included (choice of consumable)

**Comment by osallou** [comment]
Cree un calendar par resource (ici une analyse est une resource). Et choisir un mm calendar pour les resources qui utilisent le mm materiel.


Cela permettrait aussi par exemple d avoir une resource ouverte le matin et une autre l ap midi, par exemple.

**Comment by gaetanHerve** [comment]
Or really create an option to declare that all the other resources of a category are blocked when a single resource is booked in this category. Suppose to have a view by category in calendar.

**Comment by osallou** [comment]
Not a view, if checked, current view will have to display accordingly.

User should not have to go to a different virw

**Comment by gaetanHerve** [comment]
I agree. I meant "to view which slots are booked in this category". We can use the current calendar views for that.

**Comment by osallou** [comment]
Using quantities could/should be good option

defining multiple optional quantities (though could add some options to select at least one) with setting them as *is invoice unit*

**BUT** quantities should have an optional pricing , and invoice should compute resource pricing + quantities prices and optional min (default 0)/max values. 

Quantities pricing should also define is pricing is time dependent or fixed price (just take (and use night/weekend different rules?)

In above use case, could define 1 resource, pricing free and multiple optional quantities each with different prices.

prices should not be directly linked to resources, but independent, and resource/quantities/... would then link to a pricing with different rules (apply night/we, fixed or time dependent, ...)

invoice compute pricing or resource and all elements having a pricing

**Comment by osallou** [comment]
services and booking resources would just link to a pricing,  not specific to each module

for migration/upgrade, would need to create pricing objects based on current resource or service mappings

**Comment by gaetanHerve** [comment]
It is possible to solve this use case by using packages !
- 1 equipment is described by 1 category (for which we can set booking authorisations).
- Inside this category, only 1 resource is created (to block the schedule) => so we avoid the case of several reservations for the same equipment
- From this resource, we create as many packages as there are analysis => a package is described by its name, duration and resource it's based on. A package has its own prices.

**Comment by gaetanHerve** [comment]
Screenshots:

1/ create packages in booking settings > packages

![pckg_1](https://user-images.githubusercontent.com/48911130/153418804-c811f3ad-98cc-44b8-ba59-1ea65679dc5c.png)

2/ Set packages prices in Invoices > booking > Prices

![pckg_2](https://user-images.githubusercontent.com/48911130/153419026-c692057d-1913-467f-a258-2eb9164d55d7.png)

3/ Packages are available when booking the attached resource

![pckg_3](https://user-images.githubusercontent.com/48911130/153419121-4e071807-5f8d-4dd9-a58c-a4021aa0e1a4.png)

4/ If selected in reservations, packages are used in booking invoices

![pckg_4](https://user-images.githubusercontent.com/48911130/153419324-b58ce9a9-5e03-43ff-8339-a349dd9956af.png)

**Comment by gaetanHerve** [comment]
Retour de Marion Chorin :
"les forfaits ne résolvent pas notre problème car ils "figent" la durée... Or lorsque les utilisateurs réservent, en fonction du nombre d'échantillons qu'ils vont analyser, ils vont moduler la durée de leur réservation.... De plus, il faudrait que les utilisateurs n'aient pas le choix de cocher "forfait", sinon, ils risquent de ne pas le faire et dans ce cas, ils ne seront pas facturés automatiquement et nous devrons rechercher toutes les infos pour savoir qui a fait quelles analyses pour faire la facturation manuellement."

**Comment by gaetanHerve** [comment]
Pistes de résolution :
- Nous pourrions permettre de rendre la sélection d'un forfait obligatoire (sur le principe de ce qui existe déjà pour les quantités)
- La durée pourrait être indexée sur la quantité (au choix de l'admin et si la quantité est obligatoire)
- l'admin pourrait choisir que la facturation d'un forfait se fasse en fonction de la quantité (est-ce déjà le cas quand une quantité est settée à is_invoicing_unit = yes ? je teste)

**Comment by osallou** [comment]
Une pr en attente permet de forcer l usage des forfaits, mais si la duree fixe est un pb, cela ne resoud pas la question

Il faut ds ce cas gerer des calendar par resource, et pas pas area (du moins calandar area par defaut et optionellement mettre un calendar sur des ressources).
Les ressources utilisant le mm calendar viendront se superposer et il ne sera pas possible de reserver 2 resources sur le mm creneau, contrairement a l area

**Comment by gaetanHerve** [comment]
> 

c'est peut-être en effet le plus évident fonctionnellement. Mais ça implique de revoir la structure du module Booking...

**Comment by osallou** [comment]
ds un premier temps, avec les mm horaires, on pourrait avoir une option du calndar "share calendar between resources".
Dans ce cas, les resources d'une mm area pourront utiliser les mm créneaux

impact:
* option ds scheduling
* isConflict et isConflictP , si l'option est mise, alors on ne check pas sur la resource, mais sur les resources ds l'area
* booking calendar, il faut montrer toutes les resa de l'area pas uniquement celle de la resource (ou désactiver les vues day/week/month et ne garder que les dayarea/weekarea)

**Comment by gaetanHerve** [comment]
Can probably be closed after PR #564 being merged
