### ISSUE TITLE
[BUG] petits constats bugs

### ISSUE THREAD

**Issue by mnivard** [bgo-bioimagerie/platformmanager#415]
Salut à vous, 
voici une petite liste de petits trucs bugs
a+
Mariette

**bug**
- catalog --> pas de retour possible sur l'espace 
- booking config --> pas de possibilité de supprimer un champ ajouté manuellement "supprimer l'ajout d'un champ ne fonctionne pas quand il reste qu'une ligne"
- le mail de validation de compte arrive avant la validation du compte par l'utilisateur
- images sur la dalle de visu espace ne s'affiche pas malgré la config faite

**If using a Saas install (GenOuest for example)**
genouest / osur ou ecobio

**Comment by gaetanHerve** [comment]
> Salut à vous, voici une petite liste de petits trucs bugs a+ Mariette
> 
> **bug**
> 
>     * catalog --> pas de retour possible sur l'espace => cf #305 
> 
>     * booking config --> pas de possibilité de supprimer un champ ajouté manuellement "supprimer l'ajout d'un champ ne fonctionne pas quand il reste qu'une ligne"
> 
>     * le mail de validation de compte arrive avant la validation du compte par l'utilisateur => fixed by #409 
> 
>     * images sur la dalle de visu espace ne s'affiche pas malgré la config faite => cf #359 
> 
> 
> **If using a Saas install (GenOuest for example)** genouest / osur ou ecobio

**Comment by osallou** [comment]
Pour les retours au menu, il n y a pas que catalog, et d autres renvoient au mauvais endroits.
Nous sommes en train de reprendre tout le code pour corriger cela et bien d autres pb.... 

Juste une petite centaine de fichiers a modifier...

**Comment by osallou** [comment]
Pour booking config, je cree une isspour booking config j ai cree issue #432
