### ISSUE TITLE
Améliorations 

### ISSUE THREAD

**Issue by mnivard** [bgo-bioimagerie/platformmanager#416]
hello, 

quelques avancées qui seraient cool

- au lieu d'appeler le menu "MENU" l'appeler STRUCTURES
- au lieu que l'on arrive sur BIOSIT par défaut faire une page avec les dalles des structures du "MENU" ce serait joli et faciliterai les nouveaux utilisateurs 
- lorsque l'on met le lien dans un intranet par ex, lien direct de la plateforme concernée ca renvoie sur la page connexion , c'est logique mais ensuite ça renvoie sur la première page donc biosit actuellement et non le lien de la plateforme demandée
- un petit plus pour le mode super admin " pouvoir cocher une liste d'utilisateur et leur donner a tous d'un coup l'accès a un espace"
- exemple tout les utilisateurs "ECOBIO" ont le droit d'accéder a "OSUR" ca éviterai 150 validations manuelles :-)

voilà voilà j’arrête de vous embêter ;-)
a+
Mariette

**Comment by gaetanHerve** [comment]
Salut Mariette,

- Oui, "STRUCTURES" sera beaucoup plus explicite
- Tel qu'en cours de développement, l'utilisateur⋅rice arrive sur une page d'accueil présentant ses espaces favoris : 

![pfm_escpacesfavoris](https://user-images.githubusercontent.com/48911130/143463428-039bece7-e034-4e10-9238-d96d2b5480e0.png)

- la possibilité de sélectionner de plusieurs éléments à la fois pour y appliquer une même action => @osallou ,  avec la PR #400 et ton travail sur les vues, tu as peut-être commencé à aborder le sujet...

Pas de problème Mariette, tu es toujours la bienvenue ici :).

**Comment by gaetanHerve** [comment]
Tout est résolu, excepté la sélection multiple d'éléments pour effectuer une même action. Ce dernier point est référencé dans l'issue #363
