### ISSUE TITLE
[BUG] demande d'inscription à l'espace ressources communes de Biosit

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#450]
Bonjour,

Nous avons depuis quelques jours de nombreuses demandes d'accès à l'espace "ressources communes". Cette espace est dans le menu Biosit mais on a des demandes qui semblent venir de personnes hors biosit. Je me pose la question de l'affichage de cet espace dans un autre menu.
Stéphanie

**Comment by sdutertre** [comment]
Je crois que j'ai un début d'explication. Les gens qui se connectent à PFM tombent en premier sur BIOSIT (c'est bien cela?). Il y a un espace "ressources communes" et ils demandent un accès à cet espace sans forcément voir qu'ils ne sont pas dans leur unité mais dans Biosit. J'ai modifié le descriptif de l'espace en précisant bien que c'est la salle et la voiture Biosit (ce n'était pas précisé).

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,
Il doit s'agir d'une confusion de la part des utilisateur⋅ice⋅s.
ECOBIO a notamment un espace "équipements communs" et a pris le soin de rajouter "ECOBIO" à l'intitulé de l'espace.
S'il s'agit bien de cela, le problème réside principalement dans le fait que BIOSIT est la structure sur laquelle tout le monde tombe par défaut lors de sa connexion à PFM. Ce point est résolu dans la prochaine mise à jour, qui arrive dans les prochains jours (page d'accueil montrant les différentes structures, possibilité de rechercher un espace par son nom, liste de favoris...).

**Comment by gaetanHerve** [comment]
Oui, c'est bien ça :)

**Comment by gaetanHerve** [comment]
Ah, non, en fait la confusion vient plus probablement de la création de compte !

![creerCompte_espaces](https://user-images.githubusercontent.com/48911130/145799820-d3271735-4af4-4968-a69e-2b18598eef8e.png)

La structure/unité n'est pas précisée. Il faut qu'on rajoute ça !

**Comment by sdutertre** [comment]
Est ce que je peux aussi changer le titre de mon espace en "ressources communes Biosit" par exemple?

**Comment by sdutertre** [comment]
je l'ai fait sur le titre de l'espace. Je ne sais pas si cela sera reporté au niveau de l'inscription.

**Comment by gaetanHerve** [comment]
Oui, c'est bien reporté. J'intègre le fix le faisant automatiquement pour la mise à jour

**Comment by gaetanHerve** [comment]
Du coup ça fera doublon dans les espaces listés à la création de compte ("ressources communes Biosit - Biosit"). Tu pourras retirer "Biosit" du nom de l'espace quand on aura fait la mise à jour

**Comment by sdutertre** [comment]
ok.
