### ISSUE TITLE
Bugg et Miscellaneous

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#457]
Bonjour,

Un bug (?), et quelques observations.

1 - BUG ? **Ressource Restreinte et sous visa réservable par tous**
Il y a peut être une faille sur la réservation de ressource soumises à habilitation.

J'ai crée un espace ECOBIO/Démonstration_Admin caché pour mes tests pour reproduire ce que j'ai observé sur les espaces réguliers.

Compte Admin :
Ressource Réservable 1 = Domaine Non Restreint / Catégorie Non soumise à Visa
Ressource Réservable 2 = Domaine Non Restreint / Catégorie Soumise à Visa
Ressource Réservable 3 = Domaine Restreint / Catégorie Soumise à Visa
Ressource Réservable 4 = Domaine Restreint / Catégorie Non soumise à Visa
Ressource Réservable 5 = Domaine Non Restreint / Catégorie Non soumise à Visa

Compte Test : 
Utilisateur - avec Visa pour Ressource Réservable 2
Donc le compte Test ne peut normalement réservé que les Ressources 1 - 2 et 5.
Sur le calendrier, le planning avec mon compte Test me montre bien les 3 ressources auquel j'ai accès.
  
Quand je clic sur un créneau pour réserver avec mon compte test : j'ai le menu déroulant qui me permet de réserver TOUTES les ressources.
Je peux réserver la Ressource 3 Domaine Restreint / Catégorie Soumise à Visa.
Une fois validée, elle n'apparait pas sur le planning du compte Test mais elle apparait bien sur le planning du compte Admin.
Et cerise sur le planning,  il n'y a aucune informations d'indiquée sur la réservation, le compte Admin ne peut ni l'annuler, ni la modifier.

2 - ** Habilitation**
Une fois que j'ai accordé à mon compte Testeur une habilitation, je ne peux pas lui enlever.
Est ce que ce serait envisageable dans l'avenir de pouvoir le faire?

3 - **Compte/Compte Client**
Pour ECOBIO je valide des comptes pour les différentes plateformes et même si c'est sensé être exceptionnelle la manip : 

Accepter la demande / Appliquer Statut / Retour sur page BIOSIT (!) / Retour sur ECOBIO / Utilisateurs / Chercher l'utilisateur rentré / Finir par cliquer sur le "comptes clients" des 10 personnes actives / Appliquer le compte client / Retour Biosit (!) / ...

Est un peu laborieux au jour le jour. 
Surtout là je n'ai que 10 personnes, mais ça se remplis vite.

Ce serait bien de pouvoir, soit appliquer un compte client quand on accepte une personne, soit appliquer un compte client à différentes personnes. Si 5 personnes me disent qu'elles sont sur un Projet "toto" ce serait pratique de ne pas avoir à les rechercher à la main.
Et surtout devoir rechercher la personne rentrée, c'est plus facile quand c'est exceptionnel, là j'ai rentré 113 personnes et valider 113 comptes clients sur un espace, il se peut que certains soient passé par les mailles et je n'ai pas de moyen "simple" de vérifier

4 - **Calendrier Mensuel**
J'ai eu des retours de personnes qui me disaient ne pas pourvoir réserver, malgré le fait que tout soit ok de mon côté, juste parce qu'ils étaient en vue calendaire "mois" et il se trouve que dans cette configuration, on n'a pas la possibilité de réserver. Est ce que ce sera prévu de pouvoir réserver par ce calendrier à l'avenir ?

5 - **Page d'accueil des Unités**
J'ai bien compris que certaines redirections étaient revues et j'en profite pour dire que quand on doit passer d'un espace à un autre, je 
trouve que ce serait pratique de pouvoir revenir sur la page d'accueil de l'unité sans avoir à repasser par le menu déroulant.
Je suis sur l'espace 1 je veux aller sur l'espace 6, plutôt que de faire "Menus -> Ecobio" et cliquer sur l'espace 6, directement cliquer sur 
un lien "ECOBIO" .

6 - **Admin/Gestionnaires**
J'ai du mettre tout mes Gestionnaires en Admin pour qu'ils puissent paramétrer pas mal de chose.
Malgré la demande d’envois lors de la réservation je n'ai pas le mail qui arrive même en remettant la personne le statut de "Gestionnaire"
En tant qu'Admin par contre on reçoit bien les mails de toutes les demandes de tous les espaces pour mon cas.
Est ce que ce serait possible de refaire un point sur ce qui est envoyé à qui et est ce que ce serait possible de dire si oui ou non on veut recevoir les messages?
Et aussi voir un peu ce qui est accordé aux Gestionnaires et aux Admin?

7 - **Réservation sur une plage**
Je n'arrive pas à faire une réservation sur une plage ex : Jour 1 à 4.
La réservation ne se fera que sur le jour 1, je vais devoir refaire 3 autres réservations pour avoir ma plage de 4 jours.
Je peux dire que ça a été nerveusement compliqué de reporter les calendriers.
Pareil les réservations récurrentes posaient un soucis mais je n'ai pas revérifié, donc je ferais un autre message si soucis.

C'est tout pour mes observations.
Merci d'avoir lu jusqu'au bout.
Bonne journée,

Agnès

**Comment by gaetanHerve** [comment]
Bonjour Agnès,
Merci pour ces précieux retours. Ça fait beaucoup de choses. Je commence par répondre aux 2 premiers points.

1 - **Ressource Restreinte et sous visa réservable par tous**
En effet, on était passé à côté. On applique le correctif à la prochaine release (livraison aujourd'hui et mise en production début de semaine prochaine).

2 - **Habilitations**
Il est possible de retirer une habilitation, mais le chemin n'est vraiment pas intuitif (je crois que ça n'est pas pour rien, mais question à étudier): dans les habilitations d'un⋅e utilisateur⋅ice, il faut cliquer sur *historique* puis éditer la ou les habilitations pour cet⋅te utilisateur⋅ice et cette ressource pour passer le champ *Est actif* à *non*.

Réponse à venir pour les points suivants (sachons garder un peu de suspense :))

**Comment by AGareil** [comment]
Bonjour Gaetan,
Super ! 
Je note pour l'habilitation, effectivement ce n'est pas intuitif :)
A bientôt,

**Comment by gaetanHerve** [comment]
Quelques détails supplémentaires à propos du 1 - **Ressource Restreinte et sous visa réservable par tous**:

- Pour afficher les informations de la réservation sur la vue calendrier, il faut d'abord gérer les "Options d'affichage des réservations" tout en bas de la page de configuration du module Calendrier (dans le module "Configuration"). Certaines informations indiquées peuvent être erronées tant que tu n'as pas fait "save". C'est le cas pour plusieurs autres paramètres à différents endroits de l'appli. Nous n'avons pas encore pris le temps de corriger cela.

- Le fait que tu ne puisses pas supprimer la réservation en tant qu'admin est étonnant... Je n'ai pas réussi à reproduire le bug. As-tu essayé après avoir rafraîchi la page (on ne sait jamais) ?

**Comment by gaetanHerve** [comment]
point 3 - **Compte/Compte Client**

En effet, la procédure est fastidieuse. On pourrait songer à ajouter le champ "compte client" (voire regrouper "Accès", "Habilitations" et "Comptes Clients") à la page de saisie du statut ("Accès"), histoire d'avoir un unique formulaire à compléter au moment où on accepte un nouveau compte utilisateur. Je crée une issue dédiée à ce sujet.

P.S. dans la version qui arrive la semaine prochaine, plus de retour à la page de Biosit, c'est déjà ça.

**Comment by gaetanHerve** [comment]
point 4 - **Calendrier Mensuel**

On s'est déjà posé la question mais ça ne nous avait pas semblé utile de pouvoir réserver depuis la vue mois.
Mais, si les utilisateur⋅ice⋅s on l'impression de ne pas pouvoir réserver, cela en fait un problème à régler.

**Comment by AGareil** [comment]
Je n'ai pas réussi à reproduire le bug de réservation théoriquement impossible sur une machine sans habilitation depuis la dernière MAJ car le champs "Ressource" n'est plus un champs à menu déroulant mais bien bloqué sur la ressource réservé, ce qui es génial !
Donc je n'ai pas pu retester le fait de retirer ce type de résa car impossible à refaire.

Par contre, je ne peux plus faire aucune réservation aujourd'hui, donc j'imagine que c'est du à la dernière MAJ je retesterais si je peux reproduire le bug quand ça reviendra à la normal pour être sûre.

Bon courage et bonnes fêtes de fin d'année (je suis en vacances ce soir, les tests attendront 2022 maintenant :))

**Comment by osallou** [comment]
slt,
il y a eu qq soucis sur les résa mais les pb ont été résolus hier normalement, aujourd'hui cela devrait marcher.
Pb en tant que user ou manager ? peux-tu donner pls d'infos?

**Comment by osallou** [comment]
sur le "principe" , ds un espace de test, j'arrive bien à réserver. Les soucis qu'on a eu précédement était des pb de droits, mais ils ont été corrigés.

**Comment by AGareil** [comment]
Sur Ecobio, j'ai un espace crée par Mariette qui devait être un espace de réservation de salles, mais pour l'instant il n'est pas utilisé (car nous n'avons pas encore des salles ECOBIO dispo).
Donc je l'utilise soit pour montrer aux personnels que je "forme" sur PFM comment ça marche sans toucher chez eux, soit pour tester des choses que je ne connais pas encore (telle que la facturation ou ces histoires de Visa et Domaine restreint).
C'est ça que j'appelle mon espace de test.

D'ailleurs, il est bien mit en Statut "Privé" mais il apparait malgré tout dans la liste des tuiles dispo dans la structure ECOBIO.

J'ai 2 utilisateurs dessus : agareil : Admin et abulski : Utilisatrice avec visa pour la ressource 3 .

Là je peux réserver ce que je veux avec mon compte admin (agareil), mais j'ai juste la couleur que j'ai désigné pour le statut réservé qui apparait sur le planning, sans les informations de qui a réservé ou les info minimum. Ca c'est peut être moi qui ai oublié de configurer ce que voulais voir apparaitre, par défaut ça me marquait au moins le nom, mais je ne m'épanche pas trop, il faut que je revois ça.

Par contre mon compte utilisateur (abulski) ne peux pas faire de réservation, j'ai le message d'erreur : "Vous n'êtes pas autorisé à créer/modifier de réservations pour cette ressource"
J'ai fait le test avec un compte utilisateur actif sur "Véhicules de service" ou "MICRO"  toujours sous ECOBIO, j'ai le même message, je ne suis "[...] pas autorisé à créer/modifier de réservations pour cette ressource"

Donc personne à Ecobio ne peux utiliser nos plannings, ce n'est pas que sur mon espace "Démontration Admin"

**Comment by AGareil** [comment]
C'est exactement ça pour les infos dans la réservation,  j'étais passé à côté de ce paramétrage, donc c'est un bug côté humain, il est réparé ^^

**Comment by gaetanHerve** [comment]
C'est surtout d'abord un soucis de création de presets par PFM au moment de l'activation du module booking. Ça fait partie des choses à résoudre pour plus tard :)

**Comment by gaetanHerve** [comment]
Tout est résolu, excepté la sélection multiple d'éléments pour effectuer une même action (cf issue #363)
