### ISSUE TITLE
[Booking] Not being able to open a reservation from month view generates confusion

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#460]
cf #457 (*4 - Calendrier mensuel*)

Intuitively, I think about 3 different ways to solve that:
- Authorize reservation opening from month view
- Inform users that they must be in one of the other views to open a reservation
- redirect to day area view when users click on a blank day in month view (at the day on which user clicked)

Personally, I prefer the third option. Keeps it intuitive and probably simple to integrate in existing code.

**Comment by osallou** [comment]
3rd is "easy" is good I think
