### ISSUE TITLE
[BUG] impossibilté de réserver pour les utilisateurs PFM MRic Biosit

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#465]
Bonjour,
suite à la release, les utilisateurs ne peuvent plus créer de créneaux de réservation. Tout est ok jusqu'à la validation du créneau où un message apparait "vous n'êtes pas autorisé à créer/modifier de réservations pour cette ressource". 
Pour nous administrateurs, pas de problèmes pour réserver.
Stéphanie

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie. Merci pour ton retour. On regarde ça.

**Comment by osallou** [comment]
@sdutertre normalement c'est corrigé
