### ISSUE TITLE
[BUG] No booking possible

### ISSUE THREAD

**Issue by ahlegall** [bgo-bioimagerie/platformmanager#468]
OSUR Rennes Platform : can't make any booking...

ni moi ni mes collègues de l'OSUR ne pouvons faire de résa ce matin : les tableaux sont en mode Affichage uniquement...

**Comment by ahlegall** [comment]
Message : 
Error:
Division by zero

![image](https://user-images.githubusercontent.com/94834389/146761247-dfd4c8f7-241a-4851-a265-cd4b54fe58f2.png)

**Comment by osallou** [comment]
slt,
normalement c'est corrigé

**Comment by gaetanHerve** [comment]
Testé en prod => c'est OK
