### ISSUE TITLE
[self registration] user can create account sending request to space 0

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#472]
Happens selecting blank option in space selector in corecreateaccount.
Souldn't be able to do that

**Comment by osallou** [comment]
in form check of coreaccountcontrolller/indexAction you should add something like


            if( $form->getParameter("id_space") == 0) {
                $_SESSION["message"] = "Missing space access field";
                $this->redirect("corecreateaccount");
                return;
            }

**Comment by osallou** [comment]
or even check that select space id exists....

**Comment by osallou** [comment]
fixed in commit #b346e61eae34ebc47c8bf39963caed074d18ed7d

@gaetanHerve  I let you check

on email confirmation CoreaccountController/confirmAction, user account is validated.
If space id != 0 add to pending accounts
