### ISSUE TITLE
Partie Outils pour paramétrage

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#476]
Bonjour,

Sur les tuiles de plateforme déjà configurées avant la MAJ, en tant qu'Admin, j'ai bien les rangées Outils et Administration.
Sur les tuiles pas encore paramétrées (ex : ECOBIO Tuile MICRO) je n'ai pas la rangée "Outils" qui me permet d'activer les tuiles outils.

En cherchant dans la doc, je n'ai pas trouvé comment l'activer... S'il existe, je veux bien un indice pour être diriger sur le chapitre de doc qui l'indique.

Merci,

Agnès

**Comment by osallou** [comment]
on a eu qq soucis avec certains espaces,  qu'on a résolu.
Je vois une erreur sur ton espace , je regarde

**Comment by osallou** [comment]
c'est corrigé

**Comment by AGareil** [comment]
Merci !
