### ISSUE TITLE
[Clients] Adding a client account to a user won't display flash message

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#477]
Sur la structure "ECOBIO" tuile "Véhicules de service" il y a des utilisateurs qui étaient en attente d'activation.
Quand je clic sur Activer 
 - parfois j'ai le message vert sur fond vert :  "L'utilisateur a bien été ajouté au compte client" mais l'utilisateur est toujours dans les "Utilisateur en attente d'activation"
 - parfois j'ai "Activer : Nom Prénom " avec le menu déroulant du rôle une fois que j'ai validé cette fenêtre l'utilisateur a bien disparu des "Attente d'activation"
 
J'ai eu 5 personnes à rentrer et j'ai eu soit l'un soit l'autre.

**Comment by gaetanHerve** [comment]
Dans le 1er cas évoqué : cela vient d'un problème de gestion de l'affichage de nos messages. Lorsque tu as associé un utilisateur à un compte client, il ne s'est pas affiché (bug à corriger) et est "resté en mémoire" pour ne s'afficher qu'à la prochaine page affichant ce type de message (qui a été celle d'activation d'un compte utilisateur dans ton cas). Aussi, tu n'as pas eu accès au menu déroulant et au bouton de validation, ce pourquoi l'utilisateur est resté "en attente d'activation".
 
Le deuxième cas que tu évoques est le comportement normal de l'application.

**Comment by osallou** [comment]
@AGareil normalement c'est corrigé (mais c'est bien juste un souci d'affichage)

 merci de confirmer si tu as le temps, sinon   @gaetanHerve confirmera ;-)

**Comment by gaetanHerve** [comment]
Testé et OK !
