### ISSUE TITLE
[Antibodies] csv export headers / data mismatch

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#489]

**Comment by osallou** [comment]
qu'est ce qui ne va pas ? En regardant ça  l'air bon

**Comment by gaetanHerve** [comment]
Non, c'est ok. Certaines données sont insérées avec des virgules (ex : TGFß1,ß-2,ß-3 => N° 28 chez H2P2). J'avais laissé par défaut les virgules comme séparateur dans mon tableur et ça avait décalé certaines valeurs.
En revanche, le N° dans l'interface ne correspond pas au N° dans l'export en csv...
