### ISSUE TITLE
[BUG]login et adresse e-mail déjà référencé

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#507]
Bonjour,
sur la plate-forme Biosit/MRic-photonics, je souhaite créer un nouvel utilisateur mais cela me met login et adresse e-mail déjà référencé. Je n'ai personne à ce nom là dans les utilisateurs actifs, inactifs ou en attente d'activation. En échangeant avec cette personne, elle n'a pas de compte sur une autre plateforme de Biosit.
merci pour votre aide
Stéphanie

**Comment by osallou** [comment]
@sdutertre quel est le login?

Le login/email est general, pas lié à un espace. Donc si la personne a créé un compte, elle est reconnue et n a qu a rejoindre votre espace.

Le.login aurait pu etre pris par qq d autre, mais sur l email cela est etonnant.
A moins d un bug ds le check. Le login nous permettra de vérifier

**Comment by sdutertre** [comment]
le login est gdrillet.
En y réfléchissant ce matin, je pense qu'elle fait partie de l'unité MicMac. Elle a peut-être déjà un compte pour paltform manager.

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,

Elle a bien déjà un compte. Il lui suffit de cliquer sur "demander l'accès" sur la tuile de ton espace et elle rejoindra les comptes en attente d'activation dans ton module utilisateurs.

La possibilité d'ajouter un⋅e utilisateur⋅ice existant⋅e arrive avec la prochaine mise à jour

**Comment by sdutertre** [comment]
merci.
