### ISSUE TITLE
[BUG] mode d'affichage du calendrier de réservation

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#515]
Bonjour,
je viens de créer une nouvelle ressource "RIM" dans un nouveau domaine "RIM" (biosit/MRic/photonics). Si je veux le  mode d'affichage tous les jours de 8h à 24h pour ma nouvelle ressource, je vais dans l'onglet calendrier config pour changer ces paramètres mais la demande n'est pas prise en compte, il revient systématiquement à 8h-18h et du lundi au vendredi. 

Situation de départ: 
![image](https://user-images.githubusercontent.com/19782757/149328477-54602d4f-e5b4-4b7e-902e-05ccafc6000f.png)
Ce que je lui demande:
![image](https://user-images.githubusercontent.com/19782757/149328638-b14605a3-6810-47e1-8195-7bfc02278f89.png)
et ce qu'il m'affiche quand je valide:
![image](https://user-images.githubusercontent.com/19782757/149328761-34dc24ea-579e-430d-95d3-2fc3c7aa931a.png)

Stéphanie

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,

C'est surprenant, le problème existait effectivement mais a été résolu (cf  #449 )...
A priori, il y a soit :
- un problème de config de l'espace (il y a tellement de paramètres...)
- un bug côté logiciel

Dans les deux cas, en tant qu'utilisatrice, tu devrais être alertée du problème par pfm.
Je jette un œil.

**Comment by gaetanHerve** [comment]
Ok, ça ne fonctionne pas dans le cas des nouveaux domaines. Je corrige

**Comment by gaetanHerve** [comment]
@sdutertre le bug est résolu de notre côté. Il faudra encore attendre un peu qu'on fasse la mise à jour sur la prod

**Comment by gaetanHerve** [comment]
@sdutertre C'est résolu en prod !
