### ISSUE TITLE
[Booking] Email handling bugs when reservation is modified or cancelled

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#530]
Raised by Marion Chorin (Ecochim):

Bonjour,
Je reviens vers vous après qq semaines d'utilisation car nous avons identifié 2 "bugs" :
- Lorsqu'un utilisateur réserve par mégarde une ressource sur une période déjà réservée, il est bien informé que c'est impossible et est automatiquement redirigé sur le calendrier, il n'y a effectivement pas de réservation supplémentaire sur le calendrier mais par contre, les administrateurs reçoivent tout de même le mail indiquant que la ressource a été réservée.
- Dans les e-mails reçus par les administrateurs, il y a systématiquement "with periodicity" indiqué lorsque la réservation est ponctuelle et cela n'apparait plus lorsque la réservation est périodique.

Par ailleurs, nous avons éventuellement identifié qq remarques à vous soumettre :
- Lorsque l'on modifie une réservation, les administrateurs reçoivent un mail identique à une nouvelle réservation : nous n'avons donc pas l'information que la ressource a été libérée et qu'il s'agit en fait d'une modification.
- L'affichage du calendrier en semainier semble plus pratique (de notre point de vue uniquement!) : serait il possible de choisir la vue par défaut dans les paramètres?

Enfin, j'ai également qq soucis qui sont peut être liés à une mauvaise utilisation de ma part :
- Quand je libère une ressource, je reçois 2 emails en même temps "XXX has been freed" (peut être un en tant qu'administrateur et un en tant qu'utilisateur?) : savez vous que faire pour éviter cela?

**Comment by osallou** [comment]
pour la partie 2 mails, il y a un mail aux managers et un mail aux utilisateurs, qui sont séparés, donc on ne peut pas trop l'éviter.

**Comment by osallou** [comment]
pour la vue du calendrier par défaut, ce n'est pas ds les settings de l'ulisateur ? (il y a une partie booking dedans)

**Comment by gaetanHerve** [comment]
> pour la vue du calendrier par défaut, ce n'est pas ds les settings de l'ulisateur ? (il y a une partie booking dedans)

Oui, je re-teste, mais en principe c'est fonctionnel. Je suis en train de répondre à Marion

**Comment by osallou** [comment]
Le contenu de l'email (periodic ou non) ainsi que l'info (nouvelle resa / modification) ont été fixés
L'envoi de mail si booking invalid également

Prochaine release 2.3
