### ISSUE TITLE
[Booking] Cancellation emails still being sent to inactive user

### ISSUE THREAD

**Issue by xavpinson** [bgo-bioimagerie/platformmanager#531]
A former user notified me she was still receiving emails for cancelled slots on the MRic Photonics facility (Ressource: Confocal SP8 in her case) even after I switched her status to "Inactive".
Is this normal behaviour and if not is there an easy fix?
Thanks!
Xavier

**Comment by osallou** [comment]
bonjour,
en effet, il semble qu'il prenne les users inactifs ds un espace. Cela va etre corrigé.
Une solution, selon le cas, est simplement de le supprimer de l'espace, il n'aura plus de mail alors.

En effet, si il est inactif, a-t-il tjs une raison d'etre ds votre espace ?

Quoiqu'il en soit nous allons corriger ce cas

**Comment by xavpinson** [comment]
Bonjour Olivier,
A priori nous n'avons pas la possibilité de supprimer les utilisateurs de l'espace.
Merci pour la correction!

**Comment by osallou** [comment]
@gaetanHerve il y a bien moyen normalement? A quel endroit?

**Comment by osallou** [comment]
@xavpinson ce sera corrigé dd la release prevue a la fin du mois

**Comment by gaetanHerve** [comment]
Cela fonctionne sur mon environnement de developpement. Module utilisateurs>accès de l'utilisateur>supprimer (ou equivalent, le bouton rouge en tout cas). Cela le supprime de l'espace. Mais peut-être qu'il s'agit ici d'un cas particulier...

**Comment by xavpinson** [comment]
Effectivement je vois le bouton "supprimer" mais ça me donne Error 403: permission denied.

**Comment by osallou** [comment]
en effet, petit "bug", il faut etre super admin, or l'admin de l'espace devrait pouvoir le faire, on va corriger cela aussi

**Comment by osallou** [comment]
note for dev:

      public function userdeleteAction($id_space, $id_user) {
          $this->checkAuthorization(CoreStatus::$ADMIN);

should be:

      $this->checkSpaceAdmin($id_space, $_SESSION["id_user"]);
