### ISSUE TITLE
[BUG] accès à platform manager avec son téléphone

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#539]
Bonjour,
on ne peut plus accéder à platform manager avec son téléphone (impossible de rentrer son login pour se connecter).
merci
Stephanie

**Comment by osallou** [comment]
en effet

note pour dev:

sur navigateur, en mode "mobile" , cela marche, dur de debugguer

**Comment by gaetanHerve** [comment]
peut-être variable en fonction du navigateur, de l'os et de la surcouche...

**Comment by gaetanHerve** [comment]
@sdutertre Sur mon navigateur, basé sur Chrome, il y a une option "version pour ordinateur'. En l'activant, je peux saisir mes identifiants

**Comment by osallou** [comment]
oui, mais pas sur tel... j'ai essayé

**Comment by gaetanHerve** [comment]
ah, par contre les modules au sein des espaces n'apparaissent pas

**Comment by sdutertre** [comment]
testé avec Safari (OS), j'ai pas cette option.

**Comment by gaetanHerve** [comment]
tu peux peut-être essayer ça : 
https://www.howtogeek.com/435173/how-to-view-a-desktop-site-on-mobile-safari/

**Comment by osallou** [comment]
c'est corrigé, et patché en prod

**Comment by sdutertre** [comment]
Merci Gaëtan pour le lien vers le site. Effectivement cela marche et merci à tous les deux pour la correction.
