### ISSUE TITLE
[BUG] problème d'affichage sous safari (ordinateur)

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#541]
Bonjour,
je ne sais pas si c'est lié au bug d'hier (affichage sur mobile) mais une utilisatrice m'a rapporté des problèmes d'affichage de platform manager avec safari (pas de souci avec firefox). impossible d'accéder à l'espace Mric
version safari : v12.1.2 (14607.3.9)

je joins une capture de son écran:
![IMG_3818](https://user-images.githubusercontent.com/19782757/151377020-daccf6c6-8158-4bd2-a06f-ec9c6f97ac9e.jpg)

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,
Ce n'est a priori pas lié au fix d'hier, non. Difficile d'examiner ce qu'il se passe sans un safari sous la main...

**Comment by osallou** [comment]
Il est possible que le javascript soit desactivé dans son navigateur.

Il faudrait avoir les logs de la console de son navigateur

On va essayer sur safari de notre coté lais cela peut dependre de la version de son navigateur

**Comment by osallou** [comment]
c'est bien un pb de navigateur, trop vieux à priorij'ai corrigé qq trucs en prod pour vérifier et en adaptant cela passe, mais oblige à faire du "vieux" code....

**Comment by osallou** [comment]
@gaetanHerve j'ai pushé 7dd425a7b5d914e9ae4d5ad99b6d92c7be6a5d61
qui enlève du javascript les appels du genre myvar?.  pour supporter de plus vieux navigateurs.
Reste l'usage de [....xxx] , plutôt casse pied à remplacer...

**Comment by osallou** [comment]
le [..xx] ie destructing semble bien supporté de de plus vieilles versions (https://caniuse.com/?search=destructuring)

**Comment by osallou** [comment]
alors que le chainage (?.) à partir de safari 13. La modif faite devrait donc suffir pour la plupart
