### ISSUE TITLE
[Paging] If page > 1, edition popup windows won't display

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#552]
example: https://pfm.genouest.org/bookingprices/18, clicking on edit button  for a resource will display the popup on first page but not on following pages.
Displaying 100 entries on the same page or using search input won't give access to edition popup for resources initially in pages > 1.
So, as it is set by default to display entries 10 by 10, only the 10 first displayed entries are editable, whatever the path.

**Comment by osallou** [comment]
fixed in commit 9a5b172072bae9acf84cc8f2924b4daca077708c
