### ISSUE TITLE
Status button and default page bugs

### ISSUE THREAD

**Issue by xavpinson** [bgo-bioimagerie/platformmanager#557]
Hi,

I'd like to report a couple of issues with the new version of platform-manager within the MRic photonics space:

- status of some systems (FastFLIM and Spinning Em-CCD here) on orange or red and impossible to switch back to green (see attached picture)

![image](https://user-images.githubusercontent.com/39724941/152382134-de677347-0836-4989-a092-7203ccd02564.png)

- When a booking is confirmed on a system it always goes back to the default page instead of showing the page where the booking has been made (which would be more convenient)

Thanks for your help!

Xavier

**Comment by osallou** [comment]
how are managed "status/colors" ?

Regarding redirection we will have a look.

**Comment by xavpinson** [comment]
> how are managed "status/colors" ?

By clicking on the status button (the green/orange/red spot) we can access the history of the concerned system status and change it. It looks here like it is considering the first on the liste instead of the last one.


> Regarding redirection we will have a look.
Thanks!

**Comment by osallou** [comment]
which one could I try to change ?  on my local test environement, it works fine

**Comment by osallou** [comment]
ok, seems pb occurs with areas. Status is correct on day or week view

**Comment by osallou** [comment]
it is fixed in production

**Comment by osallou** [comment]
commit d488cf5b6627384ffcf164dbc9ce1b9fffca30a1
