### ISSUE TITLE
[DOC] demande d'accès - document users add method for private spaces

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#561]
Bonjour,
Je me fais le relai de la plateforme Arche biosit. Un utilisateur déjà dans l'espace MicMac ne peut pas demander l'accès à Arche. Il ne voit pas le bouton vert demander l'accès ( et il n'est pas référencé dans les utilisateurs de Arche ni dans les nouvelles demandes).
Son login rpinon
Une idée?
merci
Stéphanie

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,

C'est normal, Arche est en mode "privé". Le bouton "rejoindre" n'est donc pas visible (depuis toute dernière version).
Dans ce cas, il faut soit:
- passer l'espace en publique, dans le module configuration. Tout⋅e⋅s les utilisateur⋅rice⋅s avec un compte PFM pourront alors demander l'accès.
- "ajouter un compte existant" dans "ajouter utilisateur", module utilisateurs et y ajouter rpinon. C'est nouveau aussi.

**Comment by sdutertre** [comment]
Merci pour ces infos et top le bouton ajouter un compte existant

**Comment by gaetanHerve** [comment]
Pas de quoi. Merci :)
