### ISSUE TITLE
[BUG] Editing users

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#573]
**Describe the bug**
Quand on enregistre les utilisateurs, si il y a un erreur dans les coordonnées on ne peut plus modifier les informations.  

**To Reproduce**
1. Aller sur https://pfm.genouest.org/corespaceaccess/8
2. Pas d'option pour modifier les coordonnées des utilisateurs en cas d'erreur lors de l'enregistrement

**Expected behavior**
J'aimerai un bouton pour modifier les informations des utilisateurs

**Comment by osallou** [comment]
quelles coordonnées? ds "access" pour un utilisateur?

**Comment by osallou** [comment]
name/firstname/email ?

**Comment by osallou** [comment]
l'utilisateur peut les modifier ds https://pfm.genouest.org/usersmyaccount
par principe, un utilisateur n'étant pas lié à un espace en particulier, seul l'utilisateur a accès en modification à ses données

**Comment by GevH2P2** [comment]
Il s'agit de O'Connor Keith qui m'a dit qu'il n'a pas reçu de mail pour ouvrir son compte plateforme manager. Il pense avoir fait une faute de frappe. Il peut rien modifier à partir de son espace car il n'a pas accès à son espace.
Je pense les droits super admin est une bonne idée.

**Comment by gaetanHerve** [comment]
ok, j'ai "k.oconnnor38" arobase "nuigalway.ie" (on ne peut pas afficher d'adresse email ici il me semble).
Je suppose que la coquille est le 3eme "n" dans "oconnnor38". C'est bien ça ?

**Comment by gaetanHerve** [comment]
@GevH2P2 j'ai retiré le 'n' surnuméraire de "oconnor38" dans l'adresse mail. Cela résout le problème ?

**Comment by GevH2P2** [comment]
Bonjour, 
J'ai vu la personne et il n'a toujours pas reçu de mail. Il a vérifié les spams aussi, toujours rien.

**Comment by gaetanHerve** [comment]
Bonjour,
Ah, oui c'est normal. Le mail contenant le mot de passe est envoyé à la création du compte, mais pas renvoyé ensuite.
Je lui renvoie directement un mail avec un mot de passe provisoire, qu'il pourra modifier une fois connecté.

**Comment by GevH2P2** [comment]
Très bien. Merci ! 
J'encourage l'idée que le personnelle de la plateforme aie un accès super admin pour modifier les coordonées quand y a un changement des infos etc. Un peu comme quand on crée un compte client, on a la maint pour modifier les coordonnées des responsables, pourquoi pas les utilisateur. ça nous permettra de gagner du temps, ne pas faire un ticket quand y a un problème. 
Cordialement

**Comment by gaetanHerve** [comment]
Pas de souci.

A propos de l'accès super admin :
Les privilèges super admin permettent de contrôler également les autres plateformes, mettre le site en maintenance, etc... Il n'est pas souhaitable que chaque admin de plateforme puisse le faire.

Étant donné que les utilisateur⋅ice⋅s peuvent être membres de plusieurs plateformes avec un unique compte, il ne serait pas cohérent non plus que l'admin de l'une des plateformes dont est membre l'utilisateur⋅ice puisse modifier ses informations personnelles.
Un admin de plateforme peut en revanche modifier les informations liant le compte utilisateur à la plateforme qu'il gère.

Le principal semble être que faire une erreur de saisie au niveau de l'adresse mail à la création d'un compte empêche ensuite tout accès à Platform-Manager. Il y a des pistes de résolution à ce niveau-là.

**Comment by osallou** [comment]
il lui suffisait de faire, après modification de l'email, un "mot de passe oublié" et il aurait reçu un email avec le nouveau mot de passe, inutile que le gestionnaire/admin le fasse.

Pas d'accès super admin pour les raisons évoquées par gaetan, pour des raisons de sécurité et confidentialité (et plein d'autres raisons...)

De plus, il n'est pas nécessaire, dans la majorité des cas, de créer des comptes pour des utilisateurs, ils peuvent le faire eux-meme via la page de création de compte. Si ils se trompent ds leur email et ne recoivent rien, cela n'est pas grave, il suffit de répéter l'opération, le compte n'est pas créé tant qu'il n'a pas validé son email.

**Comment by GevH2P2** [comment]
Ok, on va essayer de faire ça avec les utilisateurs à venir et on va comment ça marche. Merci pour vos conseilles. 
Bonne journée !
