### ISSUE TITLE
[BUG] MAD date changing to "today" when booking

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#574]
**Describe the bug**
Exemple: Quand on veut réserver un créneaux sur MAD le 26/02/22, après avoir fait la réservation du créneau, l'agenda se mets automatiquement sur  "aujourd'hui" à place de rester sur le 26. 

**If using a Saas install (GenOuest for example)**
specify your space name

**To Reproduce**
1. Aller sur https://pfm.genouest.org/bookingdayarea/8?bk_curentDate=2022-02-22&bk_id_resource=&bk_id_area=&id_user=
2. Changer la date, réservez un créneau
3. Après la réservation l'agenda se mets sur "aujourd'hui" à la place de rester sur la date que j'étais

**Expected behavior**
Lorsque on se déplace sur l'agenda je voudrais qu'il reste sur la date voulu et que ça ne se met pas automatiquement sur aujourd'hui après chaque opération . Car si je voulais la date "aujourdhui" y a un bouton dédié à ça, je peux l'appuyer si j'ai besoin de revenir sur le planning du jour

**Comment by gaetanHerve** [comment]
C'est un défaut d'ergonomie que l'on nous a déjà remonté il y a peu. Nous avons prévu de le corriger (effectif pour vous début mars a priori)
@osallou , résolu en dev dans la PR #558 ?

**Comment by GevH2P2** [comment]
Merci pour votre réponse. Tenez nous informé quand ça sera corrigé. 

Cordialement
