### ISSUE TITLE
[BUG] losing info when edition antobody information

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#577]
**Describe the bug**
Quand je suis sur l'onglet anticorps, quand je choisi un anticorps, puis je veux editer pour modifier ou completer des info sur le protocole toutes les infos que j'ai noté auparavant disparaissent. Je vous montre en images: 
Sur https://pfm.genouest.org/anticorpsedit/8/1162  j'ai choisi cet anticorps pour voir les protocoles associés
https://user-images.githubusercontent.com/89006804/155541806-2082985b-3285-4ada-90e9-08b626705217.png
Dans la partie Tissus je clique edit pour modifier une info. Après avoir cliqué tout les infos que j'ai noté disparaissent (voir photo)
https://user-images.githubusercontent.com/89006804/155543370-aab52dfe-a8cc-4767-93a9-13aac593208f.png
Par contre si j'annule l'editing les infos restent. 

Merci d'avance pour votre aide

**Comment by osallou** [comment]
bonjour,
il semble simplement que votre session ait expirée, il suffit de vous relogguer.

En revanche, cela traduit un bug sur les droits d'accès, la page ne devrait pas etre accessible si vous n'etes pas loggué (ce qui va être corrigé)

**Comment by osallou** [comment]
fix by commit 1a8977370ef0569d99633e4ead9f3b01266d3832
