### ISSUE TITLE
[BUG] les réservations ne se font plus correctement

### ISSUE THREAD

**Issue by nadegemarec** [bgo-bioimagerie/platformmanager#591]
**Describe the bug**
Nous observons un problème avec la périodicité. Nous voudrions réserver l'hyperion (domaine cytomètre de masse) du 23/02 a 11h30 au 01/03 à 13h et çà ne fonctionne pas.
Sur la visualisation on ne voit rien apparaitre et sur les autres visualisations il y a une réservation uniquement le 23/02 
jusque 23h59
**If using a Saas install (GenOuest for example)**
Hyperion

**To Reproduce**
1. Go to 'https://...'

**Expected behavior**

**Additional context**
La visualisation semainier ne permet plus de tout voir en un coup d’œil, trop de cases horaires c'est très très dommage

**Comment by osallou** [comment]
et du 23/02 au 01/03 ? des dates "passées" , c'est bien ce que vous vouliez?

**Comment by osallou** [comment]
il semble que seule la première journée et la dernière journée de résa apparaise, mais pas les journées "au milieu", on regarde pour corriger cela

**Comment by osallou** [comment]
@nadegemarec j'ai appliqué un patch, la visu semble correcte maintenant, vous confirmez?

**Comment by nadegemarec** [comment]
> vous essayer de réserver sur une périodicité journalière?
> 
> concernant le nombre de case horaires trop important, comment souhaiteriez-vous voir les choses ? (si moins de cases, il n'est pas possible de réserver sur un créneau spécifique...)

Bonjour,
Je vous remercie d'avoir réparer le bug.
Concernant l'affichage en semainier, c'était très bien comme c'était avant c'est à dire on voyait les créneaux réservés et non pas les libres.
Est-ce que ce serait possible de le remettre dans cet état ?
Merci,
Nadège

**Comment by osallou** [comment]
en mode semaine, la vue était identique
en mode semaine area, la vue précédente affichait les créneaux réservés et une croix pour réserver.. Du coup, si on cliquait sur la croix pour réserver, on tombait uniquement sur les débuts d'heure et sur l'heure d'ouverture, mm si le créneaux était déjà pris.

Mais nous pourrions ajouter une option d'affichage pour ne voir que les créneaux réservés.
