### ISSUE TITLE
lib cleanup / upgrade

### ISSUE THREAD

**Issue by osallou** [bgo-bioimagerie/platformmanager#592]
* switch vuejs to vue 3 (the default now), may impact code, and install via npm (impact on layout lib loading)
* see if gantt can be replaced
* look at ckeditor in code, and see if can be updated (used by  textAreaScript() for textarea form it seems

**Comment by gaetanHerve** [comment]
- ckEditor upgraded with PR #661
- vuejs upgraded and gantt replaced with PR #649
