### ISSUE TITLE
[BUG] Durée de réservation, modification, formulaire

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#594]
Bonjour,

Je rejoins un peu le bug #591.

Un utilisateur voulais reserver un véhicule à partir de 7h du matin le 24 mars jusqu'à 16h le 25 mars.
Impossible de demander la résérvation sur deux jours lors de la résérvation initiale, juste le jour 1 est résérvé.

Donc j'ai réservé la journée du 24 et ensuite j'ai voulu reservé de 7h à 16h le 25 sauf que je n'ai pas la possibilité de réserver en mettant des heures (de **h** à **h**) mais on me demande une durée en minutes.... Pour les résérvations de demi journée c'est pas évident, c'est une configuration du formulaire? Je n'ai pas trouvé où ça pouvait être.

Je réserve la journée entière alors que ce n'est pas la demande initiale et en voulant modifier ce fameux 25 mars, je vois que là un formulaire avec de **h** à **h** apparait.
Je mets les horaires voulu, enregistre... et la résérvation reste de 7h00 à 19h00.

Merci,

Agnès

**Comment by osallou** [comment]
slt, pour le 591, c'était un "simple" problème d'affichage. Le détail de la résa était ok, mais qd la résa s'étalait sur plus de 2 jours, on ne voyait que le premier et dernier jour. Ce qui a été corrigé.
Qd on regarde le détail de la résa, pour 2 jours ou plus, est-ce que les données sont bonnes ?

Pour réserver de telle à telle heure vs une durée, cela est lié à la configuration, ds booking settings / scheduling, tu as 2 champs:

* The user specifies: on précise l'heure de fin, ou la duréee
* Default booking scale: la durée, en heures ou minutes

**Comment by osallou** [comment]
si tu as un identifiant de résa (url) je peux essayer de modifier moi mm pour voir si il y a pb (car en test local je n'ai pas de soucis pour réserver sur 2 jours en précisant la durée ou les heures)

**Comment by AGareil** [comment]
Ok merci, j'ai modifié le formulaire, je ne rencontre plus aucun des soucis constatés.
Je peux résérver les deux jours de suite et je peux aussi correctement résérver la plage que je veux.
Même la modification marche.

Donc c'est juste le formulaire de départ qui n'était pas bon, c'est un bug de ma part :)
