### ISSUE TITLE
[BUG] problème d'affichage de la période facturée sur le doc pdf généré

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#600]
Bonjour,

au niveau de la facturation des "bookings", j'ai demandé à faire le relevé des réservations pour la période 1/10/21 au 28/2/22. 
Au niveau de la page récapitulative des relevés à envoyer (https://pfm.genouest.org/invoices/1/0/) , il me met bien dans la colonne info  pour chaque facture "Bookings: 2021-10-01 => 2022-02-28" 
Par contre, dans le pdf généré (doc que j'envoie), j'ai "Bookings: 2021-09-01 => 2022-02-28"
Cela peut générer des incompréhensions de la part des personnes facturées.
Est ce que j'ai bien un relevé pour la bonne période?

Stéphanie

**Comment by osallou** [comment]
Nous allons regarder.
Il faudrait avoir le details des reservations concernees ds la facture pour verifier

**Comment by osallou** [comment]
un test local présente bien les bonnes dates

**Comment by osallou** [comment]
par contre toutes les invoices ont le mm numéro, -0000 , ce n'est pas normal

**Comment by osallou** [comment]
@sdutertre j'ai corrigé un pb en base de donnée, les factures devraient avoir maintenant (nouvelles factures) un numéro correct (-0001, -0002 , etc...)
Je ne sais pas si cela est lié ou non au pb de date, mais déjà cela est à corriger.

Je te propose de les effacer et de les regénérer.
Comme le numéro de l'invoice est utilisé et qu'ils avaient tous le mm, je suppose que cela a eu des effets de bord

**Comment by sdutertre** [comment]
Super,
j'ai refait une facture et effectivement j'ai un numéro correct et une période correcte.
J'en profite, est ce que tu crois que sur ce pdf on peut avoir la date de période plutôt en format date française (jj/mm/aa). C'est un détail mais cela serait plus lisible

**Comment by osallou** [comment]
à priori, dans le template tu peux utiliser:

{{invoiceInfo.period_begin|date('d/m/Y')}} et {{invoiceInfo.period_end|date('d/m/Y')}}  , à la place de invoiceInfo.title

**Comment by sdutertre** [comment]
J'ai essayé 
j'ai maintenant les deux dates début et fin mais il me manque un peu d'explication autour
idéalement avant j'avais "MAD: période du jj/mm/aa au jj/mm/aa"
maintenant j'ai "jj/mm/aa jj/mm/aa"
Je ne sais pas comment ajouter du texte autour de ces deux dates dans le template

**Comment by osallou** [comment]
qq chose du genre:

    <p>MAD: {{invoiceInfo.period_begin|date('d/m/Y')}} - {{invoiceInfo.period_end|date('d/m/Y')}}</p>


<p>...</p> pour mettre un paragraphe de texte
Les {{..}} sont pour des variables
Le texte, après, tu le mets comme tu veux

**Comment by sdutertre** [comment]
parfait. merci
