### ISSUE TITLE
colonne tableau agenda de réservation[BUG]

### ISSUE THREAD

**Issue by Rviel** [bgo-bioimagerie/platformmanager#602]
Bonjour,

Est il possible d'enlever les colonnes dans le l'agenda de réservation?

**Comment by osallou** [comment]
quelles colonnes?

**Comment by osallou** [comment]
@Rviel  ?

**Comment by gaetanHerve** [comment]
@Rviel 
Roselyne,
Est-ce que le problème existe toujours ? Si oui, pourrais-tu nous le définir ?
Merci,
Gaëtan

**Comment by gaetanHerve** [comment]
Merci Roselyne. Je clos cette issue.
