### ISSUE TITLE
Tableau de prestation et suivi de projet

### ISSUE THREAD

**Issue by Rviel** [bgo-bioimagerie/platformmanager#603]
plateforme H2P2,

Est il possible d'avoir un seul tableau pour les projets en cours, idem pour le suivi d'un projet ?

**Comment by osallou** [comment]
que voulez vous dire par un seul tableau ?

Dans la page des projets en cours (servicesprojectsopened/x) il n'y a qu'un tableau, idem ds le suivi (servicesprojectfollowup/x/y)

**Comment by osallou** [comment]
@Rviel si vous voulez parler d'afficher tout sur la page, au lieu d'utiliser la pagination dans les tableaux, il est possible d'afficher jusqu'à 100 élements. Ce n'est pas suffisant?

**Comment by gaetanHerve** [comment]
solved with PR #726
