### ISSUE TITLE
[booking settings] in some cases, it's impossible to delete lines from formadd

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#610]
in sup infos, packages and quantities. At least when related resources where deleted
related to #608

**Comment by osallou** [comment]
Logic, as related resource does not exists...
So related to other issue about resource deletion

**Comment by gaetanHerve** [comment]
yeah, but I was wondering if it was an issue that could also be handled in formadd script. Maybe the same behaviour can be found not only on resources...

**Comment by gaetanHerve** [comment]
This behaviour is linked to the fact we use id_packages, id_quantities, etc... and not id in the tables => there are some duplicated  package_ids in space 18 (ecochim) for example. Removing not all elements with the same package_id will result in not removing any of these elements.

**Comment by gaetanHerve** [comment]
ok, it's normal that bk_packages can have the same id_package, so it is possible to have several resources in the same package.

But, since:
- selecting a package when making a reservation won't create a reservation for the other resources shared by this package
- price for a resource / package is not linked to other resources / package prices for the same package

What is the meaning of having several resources related to a same package  ?

**Comment by gaetanHerve** [comment]
And, it should be possible to delete a line in booking packages without having to delete all other lines related to this same package
