### ISSUE TITLE
Can not select Color with helpdesk 

### ISSUE THREAD

**Issue by ofilangi** [bgo-bioimagerie/platformmanager#614]

**Comment by osallou** [comment]
you mean the color in module configuration for the left menu?

**Comment by ofilangi** [comment]
in the configuration we can not select a new color

**Comment by osallou** [comment]
I tested locally and, in module config, we can configure color, and it an be modified

**Comment by gaetanHerve** [comment]
It's strange. We where in visio, Olivier (ofilangi) was trying to set the menu color. The result of the color choice via the color picker interface (looked like it was on chrome or chromium) wasn't taken into account.
I tried just now in P2M2 space in prod (with chromium) in helpdeskconfig and it worked.

Maybe a browser bug ?

@ofilangi your helpdesk module is now in a magnificent green. Could you try to change it again ?

**Comment by ofilangi** [comment]
@gaetanHerve it's ok now ! 
thanks !!
