### ISSUE TITLE
[BUG] Client-user attribution problème when creating new project

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#625]
**Describe the bug**
Quand je veux créer un nouveau projet il faut choisir un compte client ainsi que compte utilisateur. Le compte client c'est BIOTRIAL ,une boite privée, l'utilisateur c'est moi et mes collègues, car cette boite n'a pas ses propres utilisateurs et c'est nous qui faisons les manips pour eux. Quand je mets moi en tant que utilisateur, Il change le compte client BIOTRIAL et mets mon responsable en tant que client. Par contre après avoir validé le projet, je change le client en BIOTRIAL et ça marche. Il faudrait que ça n'impose pas un compte client et qu'on ai la main. 

**To Reproduce**
1. Aller sur  https://pfm.genouest.org/servicesprojectedit/8/0

**Expected behavior**
Je veux pas que le compte client change automatiquement quand je me mets en tant qu'utilisateur

**Comment by osallou** [comment]
Le choix du client est primordial et impactant, car c'est sur la base de ce choix que s'effectue la facturation
Le choix de l'utilisateur est moindre, et sert plus à savoir qui contacter etc.... Actuellement l'utilisateur est choisit forcément parmi les comptes du client.

Une possibilité pour ce genre de cas, est de vous rajouter dans le compte client. Vous pourrez alors choisir le compte client attendu et vous mettre en compte utilisateur.

Comme évolution, nous pourrions proposer, pour un client, la liste des comptes client + les responsables d'espaces.

**Comment by osallou** [comment]
@gaetanHerve  use case on project, for for orders too (select client then select optionally a user)

**Comment by GevH2P2** [comment]
Bonjour, 
Merci pour votre retour. Je trouve ça un peu embêtant car je vais avoir autant de comptes clients que de projets et j'en ai bcp. Plus mes collègues vont être obligé de faire la même chose car le même client peut avoir un projet aussi avec eux. Aussi ça va poser problème pour chaque réservation car à chaque réservation aller chercher le bon compte client dans la grande liste, L'Ideal serait d'avoir la main libre sur le choix de client pour les créations de nouveaux projets. 
Comme je vous ai dit aussi, après avoir validé le nouveau projet, je le réouvre et là je modifie le compte client et ça ne modifie pas le compte utilisateur. Là ça marche mais pas la première fois.

**Comment by osallou** [comment]
@GevH2P2   ds les projets/orders, on va modifier le comportement

* choisir un client (obligatoire, c'est la base pour la facturation, les stats, etc...)
* choisir *optionnellement* un user parmi les membres du client (personne directement lié à ce projet chez le client, ...)

Cela serait mieux?

**Comment by GevH2P2** [comment]
C'est sure que le choix de client est obligatoire, c'est dans nos intérêts de le choisir pour pouvoir facturer le projet.

Par contre quand vous dites "membre du client" c'est à dire pour chaque client nous devons nous rajouter à sont compte, puisque on a bcp de projets en fin compte on va se retrouver avec des dizaines de clients et tous mes collègues doivent le faire aussi. 
Pour moi et mes collègues l'idéal c'est de pouvoir choisir n'importe quel client sans être obligé de se rajouter comme membre de ce client, car on a bcp de clients et chacun de nous doit le faire pour chaque client. On voudrait avoir le droit de libre choix au moins du fait que nous sommes les administrateurs.

**Comment by osallou** [comment]
pas le peine de vous rajouter, vous laissez dans ce cas le champ user à vide

ou avez vous qd mm besoin de vous afficher en tant qu'utilisateur?

**Comment by gaetanHerve** [comment]
Je suis parti sur:
- la sélection de l'utilisateur rendue optionnelle (possibilité de laisser le champ vide)
- c'est désormais le choix du compte client qui détermine la liste des utilisateur⋅ice⋅s, et plus l'inverse. (mais, par conséquent, si on veut renseigner un⋅e utilisateur⋅ice, doit être relié⋅e au compte client)
- on conserve la nécessité de saisir un visa (eq. "manager in charge") => cela permet de conserver le rattachement à un manager / admin de l'espace sans avoir à le rattacher au client. Permet également de conserver l'info de la personne référente à la génération des fichiers statistiques

Les tests (auto et manuels) sur facturation et génération de stats pour un projet sans renseigner le champ "utilisateur" ne levent pas d'erreurs et affichent des résultats cohérents

@GevH2P2 cela répond bien à tes besoins ?

**Comment by GevH2P2** [comment]
ça me convient, par contre je viens de faire un test pour créer un projet avec un compte client et sans utilisateur, je n'arrive pas valider la création du projet car il demande un utilisateur.

**Comment by GevH2P2** [comment]
Ok ! Merci beaucoup pour votre aide. Je reteste et je vous tiens au courant !

**Comment by gaetanHerve** [comment]
On ne le mettra pas en production avant la semaine prochaine a priori. On t'avertira sur cette issue quand ça sera effectif

**Comment by osallou** [comment]
C est en cours de dev chez nous, ce n est pas sur le pfm de prod, donc inutile de tester.
On mettra la modif en ligne tres prochainement
