### ISSUE TITLE
[Booking][emails] De-reservation won't send emails anymore

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#628]

**Comment by osallou** [comment]
why?

**Comment by gaetanHerve** [comment]
I was going to investigate on that

**Comment by osallou** [comment]
emails were sent 'till recently at least....

Though, emails are sent to user:

* with a role in space
* people with a reservation after the dropped reservation

**Comment by gaetanHerve** [comment]
Marion from ecochim warned me about that. I first tested it and did not received email. But now I see emails are set to be send only in case of future bookings deletion

**Comment by gaetanHerve** [comment]
so it's working normally

**Comment by osallou** [comment]
maybe should check if managers are in copy (don't know if expected) and receive notif  in any case.

**Comment by gaetanHerve** [comment]
if options are set correctly, user who booked and managers receive the email. So, there's no issue here. I'm closing it
