### ISSUE TITLE
[BUG][pfm-training] 502 Proxy error when trying to access "Statistics dashboard" (grafana)

### ISSUE THREAD

**Issue by ecaruyer** [bgo-bioimagerie/platformmanager#632]
**Describe the bug**
The "Statistics dashboard" does not seem to work on pfm-training.

**If using a Saas install (GenOuest for example)**
Neurinfo

**To Reproduce**
1. Go to 'https://pfm-training.genouest.org/corespace/16'
2. Click on 'Statistics dashboard'
3. See error

**Expected behavior**
I believe we should access some kind of stats tools.

**Additional context**
N/A

**Comment by gaetanHerve** [comment]
Hi,
It's normal, Grafana is not installed on the pfm-training instance.
@osallou , maybe this would be nice to activate it on training so users could test it. Your opinion ?

**Comment by osallou** [comment]
We indeed could, but works with premium plans only

But for training we would give premium access

Will do that in near future

**Comment by osallou** [comment]
Regardings stats, there is anyway the stats module which can be activated to have basic stat reports

**Comment by ecaruyer** [comment]
Great, thanks for the quick reply! I'll give the stats module a try.
