### ISSUE TITLE
Id Reservation

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#634]
Bonjour,
Ce n'est pas un problème mais cela perturbe certains utilisateurs.
Avec la nouvelle interface de PFM lors d'une résérvation, la première ligne est "Id" et est grisée avec "0".
Certains utilisateurs sont revenus vers moi pour savoir à quoi ça correspondait et pourquoi c'était là malgré le fait que ça ne gène en rien les réservations.
Comme j'ai eu plusieures fois la question, je me permets de passer par là pour savoir quoi leur dire.
Merci,
--------------------
Hello,
This is not a problem but it confuses some users.
With the new PFM interface when making a reservation, the first line is "Id" and is grayed out with "0".
Some users have come back to me to find out what it was and why it was there despite the fact that it does not interfere with reservations.
As I had the question several times, I allow myself to go through it to know what to tell them.
Thanks,

Agnes

**Comment by osallou** [comment]
Slt,
Cela affiche l identifiant de la resa.
Pour une nouvelle resa, tant que pas sauvée, c est zero :-)

Le champ est grisé car non modifiable.

Cet id est necessaire en cas de pb, ou y  faire reference. C est juste une information. (Ou verifier qu on est sur la bonne resa)

Dans le cas d une nouvelle resa, il est vrai que nous pourrions cacher ce champ.

**Comment by AGareil** [comment]
Non mais on peut tout à fait avoir des champs "réservés" à l'administration, ça ne perturbe en rien l'utilisation du formulaire.
J'avais juste besoin de savoir quoi leur répondre parce que "j'imagine que c'est ... " ou "Ne vous en occupez pas" n'avaient pas l'air de marcher.
Merci d'avoir répondu aux inquiétudes des utilisateurs assidus d'ECOBIO ;)
