### ISSUE TITLE
Facturation code [BUG]

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#637]
**Describe the bug**
J'ai facturé le projet BIOT 22-05 (R04), j'ai pu générer un avis des sommes à payer avec N° relevé 2022-0064, mais quand je regard le suivi du projet j'ai pas le numéro de relevé devant les prestations que j'ai facturées. 

**To Reproduce**
Aller sur https://pfm.genouest.org/invoices/8
On voit le numéro de relevée 2022-0064 pour le projet BIOT 22-05 qui est déjà facturé
Aller sur https://pfm.genouest.org/servicesprojectfollowup/8/935
Sur la partie relevés on ne voit pas 2022-0064. 
Si je rajoute d'autres prestations et que je facture il va refacturer les choses qui ont été déjà facturées 

**Expected behavior**
On devait avoir le numéro de relevée devant les prestations

**Comment by osallou** [comment]
un test sur un projet, en local, montre bien l'id de l'invoice sur le service du projet. Il va falloir que nous essayons de reproduire le pb

**Comment by GevH2P2** [comment]
Ok, j'attends votre réponse.

Cordialement

**Comment by osallou** [comment]
@GevH2P2 le pb est résolu.

Il faut cependant détruire la facture en question et la regénérer, le numéro d'invoice devrait alors bien apparaitre

**Comment by GevH2P2** [comment]
Merci ! 
Je vous dis si le problème revient ^^
