### ISSUE TITLE
[BUG] Antibody protocol deleting problem

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#638]
**Describe the bug**
Quand je suis dans le menu d'Anticorps, je cherche un anticorps (exemple CD95, N° 1203) et j'essaye d'effacer un tissus qui est associé à l'anticorps, ça ne marche pas et ça me mets sur une page qui n'a aucune sens

**To Reproduce**
Aller sur le menu d'Anticorps https://pfm.genouest.org/antibodies/8
Chercher l'anticorps CD95 ou le numéro 1203
Cliquer sur l'anticorps CD95
Dans la partie "Tissus" cliquer sur effacer un protocole. À part le fait qu'il n'efface pas le protocole il nous mets sur une page d'anticorps sans aucune information avec des propriétaires qui n'ont pas rapport avec le CD95.

**Expected behavior**
Il faut qu'on puisse enlever des tissus, des propriétaires sans que ça beug

**Comment by osallou** [comment]
@gaetanHerve ca semble etre un pb d id encore qui ne reference pas la bonne chose

**Comment by osallou** [comment]
@GevH2P2 on regarde ca, merci pour la description precise du pb :-)
Le probleme devrait etre resolu assez rapidement je pense

**Comment by osallou** [comment]
@GevH2P2 pour faire un test, quel tissu puis-je essayer de supprimer?

**Comment by GevH2P2** [comment]
Bonjour Osallou, 
Vous pouvez effacer celui que vous voulez :)

**Comment by osallou** [comment]
ok, le pb est lié au fait qu'il y ait pls tables ds la mm page. La function confirmDelete est définie pour chaque table (delete tissue et deleteowner), et c'est le second qui est utilisé.
Il faut que la fonction javascript soit spécifique à chaque table

**Comment by GevH2P2** [comment]
Merci beaucoup d'avoir réglé le problème. 
Bonne journée !
