### ISSUE TITLE
[Antibodies] Menu Ac décalé / ergonomie images

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#641]
**Describe the bug**
Dans le menu anticorps les lignes sont en décalage. Regarder la capture d'écran

![image](https://user-images.githubusercontent.com/89006804/167654837-7aa5f8db-742b-4965-b183-c203fdc19ac6.png)

**To Reproduce**
Aller sur https://pfm.genouest.org/antibodies/8

**Expected behavior**
Les colonnes sont alignées

**Comment by GevH2P2** [comment]
Windows 10, google chrome

**Comment by osallou** [comment]
humm, sous windows10, chrome et firefox, je n'arrive pas non plus à reproduire. Une condition particulière (sélection d'anticorps, taille de la fenetre, ...)  ??? Cela apparait dès la page d'accueil antibodies pour tous?

@gaetanHerve  tu peux essayer de ton côté?

**Comment by GevH2P2** [comment]
Bonjour osallou, 
Oui effectivement c'est une question de zoom. Quand je suis à 110% les choses se mettent en place, par contre quand je suis à 100 ou moins ça se décale. Je ne sais pas si c'est normale ?

**Comment by gaetanHerve** [comment]
Bonjour @GevH2P2,
Le fait que le zoom modifie l'alignement nous donne un bon indice.
Je me mets sur un correctif

**Comment by GevH2P2** [comment]
Super ! Merci ! :)

**Comment by gaetanHerve** [comment]
@GevH2P2,  j'ai trouvé une solution au problème (pas encore effectif en production).
En revanche, j'ai l'impression qu'il y a un souci au niveau de l'ajout d'images à la catégorie tissus (1ere colonne de la rubrique tissus, celle qui n'a pas de titre en en-tête). Peut-être que cette fonctionnalité n'a jamais été complètement implémentée.
As-tu possibilité de tester l'ajout d'une image de ton côté afin de voir si elle est bien sauvegardée et si elle apparaît bien dans le tableau?

**Comment by gaetanHerve** [comment]
@GevH2P2 c'est en prod. En revanche, les miniatures (entre temps, on a vu que vous aviez bien des photos) doivent être plus petites qu'auparavant. On te laisse tester le résultat et nous dire si ça te convient.

**Comment by GevH2P2** [comment]
Alors  en zoom 100 ou moins ça marche, ça s'est réglé. merci !

 Je viens de tester avec une image de paysage ^^
![image](https://user-images.githubusercontent.com/89006804/167844278-2c594fb6-f6f6-4418-a191-8f100c52754c.png)

ça marche. Par contre l'image est grande, pour tout voir il faut utiliser le roulette de souris. Peut être c'est du à la résolution ? J'ai cherché une image sur google. Est-ce que on peut faire pour que l'image s'affiche dans une échelle pour être entièrement visible ? 
Quand je cherche un Ac (exemple Pimonidazol, numéro 1245), je trouve l'Ac et si je clique sur l'image elle s'affiche, par contre si je clique sur l'Ac, dans le menu d'Ac où je peux éditer des infos,  l'image ne s'affiche pas si je clique dessus, par contre on voit bien la miniature. 
Il manque pas mal d'images aux Ac car on n'a pas trop de temps de tout bien compléter, attribuer une image, mais ça reste un bon outille. 
Merci d'avance pour tout !

**Comment by gaetanHerve** [comment]
effectivement, le fait de pouvoir accéder à l'image en cliquant sur la miniature pourrait êttre possible depuis la page d'édition de l'ac. Ce serait assez logique.

Le fait que, si l'image est grande, il faille scroller est lié à des contraintes de taille de fenêtre (il y a une taille max). Cela pourrait nuire à l'interface de permettre à cette fenêtre d'être trop grande. Il est toujours possible de télécharger l'image (avec un click droit  > "save image as" ou équivalent. également possible en cliquant directement sur la miniature)

**Comment by osallou** [comment]
D'une manière générale, il faut faire attention à la taille des images chargées ds pfm (ou ailleurs....).
Il n'est pas idéal de mettre une image ds n'importe quel format/taille, mais bien de charger une image dans la résolution souhaitée (environ)

**Comment by gaetanHerve** [comment]
Autant continuer les échanges ici. on va peut-être attendre la prochaine mise à jour (semaine prochaine) pour intégrer l'image cliquable dans l'édition d'ac.
Pour la taille d'image, c'est en fonction de vos besoins. Disons qu'il est inutile de surcharger nos serveurs (et d'augmenter le temps de chargement côté utilisateur) avec une image de 4000 pixels de côté si du 1024 x 768 (ou plus petit) suffit.

**Comment by GevH2P2** [comment]
Bonjour, 
Désolé pour la réponse tardive. 
Voici l'autre problème: 
Dans onglet Utilisateurs ( https://pfm.genouest.org/corespaceuseredit/8/1112) ->Pelizzari Diana->Habilitations,  on n'a pas fait attention et on a mis 2 fois la même habilitation: "Scanner de lames"
Je voudrais pouvoir effacer les d'habilitations rajoutés par erreur 
Merci d'avance pour votre aide

**Comment by gaetanHerve** [comment]
Bonjour, 
ah, pardon, j'ai lu trop vite ton précédent message. Je pensais qu'il s'agissait d'un problème lié au premier.
Effectivement, il faudrait créer un nouveau ticket. Je répondrai sur le nouveau.

**Comment by osallou** [comment]
Vous devriez pouvoir enlever une des habilitations.

@gaetanHerve ?

**Comment by GevH2P2** [comment]
osallou j'ai essayé d'effacer l'habilitation pour la personne dont je parle mais ça ne marche pas. Le max de ce que je peux faire c'est mettre l'habilitation en non active mais elle ne disparait pas de la liste et j'ai peur qu'il aie un bug car la personne est habilitée mais il y a 2 fois la même habilitation ajouté par inattention

**Comment by gaetanHerve** [comment]
Ce que veut dire Olivier, c'est que l'on devrait ajouter la possibilité de supprimer une autorisation ajoutée par erreur. Ce n'est pas le cas actuellement

**Comment by gaetanHerve** [comment]
En revanche, pas d'inquiétude à avoir. Le fait d'avoir plusieurs habilitations pour 1 même  utilisateur / même ressource fait partie du comportement prévu. Certaines plateformes ont besoin de conserver une trace des différentes habilitations qui ont été données au cours du temps. Mais, en effet, ça n'est pas le cas de tout le monde, d'où l'intérêt d'ajouter la possibilité de supprimer une habilitation, pas seulement de la passer en inactive. Je rajoute cela à notre calendrier de dev.

**Comment by GevH2P2** [comment]
Désolé j'ai cru qu'il a réglé le problème ^^ 
Ok, merci d'avance pour le réglage de problème ^^
C'est tout pour moi pour l'instant :)

**Comment by osallou** [comment]
@gaetanHerve à fermer?

**Comment by GevH2P2** [comment]
Bonjour, 
Oui ! ^^
