### ISSUE TITLE
[BUG] Calendrier config/Info sup

### ISSUE THREAD

**Issue by micso-geh** [bgo-bioimagerie/platformmanager#642]
Bonjour à tous

**Describe the bug**
Dans calendrier config/Informations réservation j'ai ajouté une info supplémentaire pensant que cela m'aiderait pour la facturation. Cela n'est pas le cas et je voudrais donc supprimer cette info sup. Je coche la ligne, je coche supprimer puis valider, mais la ligne reste active. Que faire ?

Merci d'avance de votre aide.
Sophie

**Comment by gaetanHerve** [comment]
Bonjour Sophie,

Oui, c'est un bug de la version actuelle, déjà résolu dans la version de développement, mais pas sur l'environnement de production.
Le correctif passera avec la prochaine mise à jour, courant de semaine prochaine.

Cela peut-il attendre jusque-là pour toi ?
Gaëtan

**Comment by micso-geh** [comment]
Bonjour Gaëtan

Pas de problème pour attendre la prochaine mise à jour.
Bonne journée

Sophie
