### ISSUE TITLE
[BUG] envoi de mails

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#646]
Bonjour,
j'ai tenté d'envoyer un mail ce matin aux utilisateurs et j'ai une erreur au moment de l'envoi. 
Je suis désolée je n'ai pas noté l'erreur pour vous la retransmettre.
Stéphanie (Mric -Biosit)

**Comment by sdutertre** [comment]
le voilà
Message was not sent
' . 'Mailer error: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

**Comment by gaetanHerve** [comment]
Bonjour Stéphanie,
On a mis à jour la prod ce matin. On dirait un souci de config de notre côté. On regarde ça !

**Comment by sdutertre** [comment]
oui, j'ai vu. merci pour les modif d'ailleurs :)
Peut-être lié également, j'ai une utilisatrice qui demande une réinitialisation de son mot de passe et qui ne reçoit pas de mail.

**Comment by gaetanHerve** [comment]
de rien :). Oui, les 2 problèmes sont liés

**Comment by gaetanHerve** [comment]
@sdutertre , osallou a trouvé et résolu le problème. Ca devrait fonctionner maintenant

**Comment by sdutertre** [comment]
ça fonctionne pour les mails, merci
