### ISSUE TITLE
[Spaces] Can't create a new space

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#650]
{host}/spaceadminedit/0 returns an exception "space not found"
So it's impossible to create a new space

**Comment by osallou** [comment]
Broken in last release?

**Comment by gaetanHerve** [comment]
I think so. I take look into it

**Comment by osallou** [comment]
Should have stack trace in logs

**Comment by osallou** [comment]
Edit action starts with

        $this->checkSpaceAdmin($id_space, $_SESSION["id_user"]);

Maybe the issue when id space is zero.

If id is 0, then we should check we are superadmin, else use current check.

Something ilke

issuperadmin = ....
If id = 0
 If not issuperadmin
   Thrw exception  forbidden
Else
  If not issuperadmin and not space admin
     Throw exception forbidden

**Comment by osallou** [comment]
Or checkSpaceAdmin should check if we are superadmin first

**Comment by osallou** [comment]
Humm checkspaceadmin checks for admin status

        if ($userAppStatus > CoreStatus::$USER) { ...

**Comment by gaetanHerve** [comment]
can't get space if $id_space == 0 (our use case)

**Comment by osallou** [comment]
yes found it, should have if ($id_space)

**Comment by osallou** [comment]
need fix in master branch and cherry pick to develop
and update in prod

**Comment by gaetanHerve** [comment]
@osallou , I'll let you update me when you'll have been able to update in prod
