### ISSUE TITLE
[BUG] Same random phone for everyone in Week Area Calendar view

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#653]
Bonjour

**Describe the bug**
Dans le calendrier "Voiture" de la structure "ECOBIO"  avec la vue "Semainier / Week Area" sur quelques semaines, toutes les personnes ayant réservées ont le même numéro de téléphone.
Par exemple semaine du 6-12juin on a le portable d'un user qui s'affiche pour tous, la semaine du 20-26 juin on a le fixe d'un autre pareil la semaine du 27juin-03juillet.
Toutes les réservations ont été faites par des personnes différentes.
Dans le module Booking on l'affichage du téléphone est en mode "visible" car on a besoin de pouvoir contacter les gens qui prennent les voitures.
On a rajouté un champ obligatoire "téléphone" lors de la réservation aujourd'hui pour pallier à ce soucis.

**If using a Saas install (GenOuest for example)**
Structure ECOBIO - Calendrier Voiture

**To Reproduce**
1. Go to 'https://pfm.genouest.org/corespace/21'
2. Click on 'Calendrier'
3. Select view 'Semainier/Week Area'
4. Select week "6june-12 june" or "20june-26june" not all the week have the problem
5. See error

ex : V6 kangoo réservation le samedi 11 juin - Agnès Bulski (moi en mode user pas admin) j'ai mon numéro entré lors de la réservation qui s'affiche (02.23.23.67.72) ET le numéro de portable d'Axel Beringue qui n'a rien à voir avec ma réservation qui s'invite.

**Expected behavior**

Ne pas avoir un numéro de téléphone aléatoire qui apparaisse pour pouvoir joindre la bonne personne.

**Additional context**
Vision qu'on soit en admin ou user.

**Comment by osallou** [comment]
Je suppose qu il affiche le tel de ma premiere personne de la vue en question

**Comment by osallou** [comment]
qd je rearde les résa en question, le champ phone est vide

https://pfm.genouest.org/bookingeditreservation/21/r_109153?from=weekarea:2022-06-06::73::simple 

par exemple

Le Phone en question faut voir d'où il sort....

**Comment by osallou** [comment]
@AGareil il y a pls pb

L affichage du champ phone ds les settings est si l utilisateur a entré son tel dans son compte, rien a voir avec le champ ds la resa. Ce champ est cependant faux, on cherche pourquoi.

D ailleurs ds les settings tu devrais mettre managerd only, pas de raison que les autres users voitmebt cette information.

Ds la resa tu as defini un champ supplementaire phone, ce dernier apparait qd il est rempli. En revanche, bien qu il soit obligatoire, je vois plein de resa ou ce champ est vide. Il apparait bien pour qq resa

**Comment by osallou** [comment]
l'affichage est patché en prod

**Comment by osallou** [comment]
mais le "phone" dans la résa est mandatory, pourquoi la plupart des résa n'ont pas de tel ?
Le passage en mandatory est-il récent ? (des résa antérieurs avant que ça passe en mandatory?)

**Comment by AGareil** [comment]
Bonjour,
J'ai mis seulement ce matin le champs téléphone obligatoire, donc c'est normal que les anciennes résa ne l'aie pas de spécifié vu qu'au moment de la réservation le champ n'existait pas.

**Comment by AGareil** [comment]
Le téléphone pour la résa de voiture doit être visible de tous pour que les futurs conducteurs puissent contacter l'utilisateur actuel pour problème horaire par ex, ou inverse, qu'un utilisateur puisse prévenir le suivant qu'un problème sur la voiture a été identifié. 
C'est pour ça que dorénavant on met un numéro de téléphone obligatoire lors de la réservation (portable labo ou fixe labo d'ailleurs) vu que les gens n'ont pas joué le jeu de donner un téléphone donc la gestionnaire des voitures doit faire un jeu de piste pour retrouver chaque protagoniste à chaque problème et du coup ce fameux soucis d'un même numéro pour tous.

**Comment by osallou** [comment]
ok, pour la visibilité, c'est vous qui voyez :-)

et l'affichage est patché en prod

**Comment by AGareil** [comment]
Merci !
