### ISSUE TITLE
[BUG] Users not able to modify reservation

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#654]
**Describe the bug**

Les utilisateurs n'ont pas la possibilité de modifier/supprimer leur réservations.
Quel que soit le calendrier pour ECOBIO, là pour la suite je prends l'exemple du dernier calendrier crée car peu d'utilisateurs (SISAE), mais on a ça pour tous et surtout pour les voitures et c'est très handicapant.

Un utilisateur fait sa réservation, veut y revenir, un message d'erreur :
Error:
ERROR: You're not allowed to edit this reservation
Ce message arrive soit en allant directement chercher sa réservation sur le calendrier, soit en cliquant dans la liste des réservations disponible sur l'accueil. 

La modification est ouverte aux utilisateurs même si elle est débutée.
Booking/Restrictions/time (in hours) before a booking when a user cancel a reservation (-1 for no restrictions) : toutes à -1

En rédigeant le "ticket" je me rend compte qu'il y a un problème de fuseau horaire sur la définition de la réservation.
ex : Mariette a fait une réservation en tant qu'user sur ECOBIO / SISAE / Blue 1 - 1T pour aujourd'hui 09/06/2022 de 17h à 18h

Sur l'accueil on a : Bookings : 09/06/2022 **19:00:00**: ECOBIO Blue 1 - 1T [SISAE]
Sur le calendrier sa réservation est bien de **17h à 18h**
Quand je rentre sur sa résa en tant qu'admin les horaires sont bien 17h à 18h

**If using a Saas install (GenOuest for example)**
ECOBIO/SISAE (par exemple)

**To Reproduce**
1. Go to 'https://pfm.genouest.org/corespace/38'
2. Click on 'Impersonate Mariette Nivard - USER of SISAE'
3. Click on '09/06/2022 19:00:00: ECOBIO Blue1 - 1T [SISAE] (sur la page d'acceuil)

Ou passer par le calendrier SISAE :
1. Go to 'https://pfm.genouest.org/corespace/38'
2. Click on 'Impersonate Mariette Nivard - USER of SISAE'
3. Click on 'ECOBIO ' et 'SISAE'
4. Click on Calendrier 
5. Click on reservation ECOBIO Blue 1 - 1T - 17h
6. see error

**Expected behavior**
Que les utilisateurs puissent modifier leur réservations, sinon on va devoir engager une secrétaire car ça nous prend beaucoup de temps de le faire pour eux.

**Additional context**
Ras

**Comment by osallou** [comment]
Pb de conversion du timestamp en heure locale a priori, comparer avec les autres affichages

**Comment by osallou** [comment]
Case -1 was not handled...

**Comment by osallou** [comment]
pour l'affichage, un pb de UTC/GMT... comme ce n'est pas géré localement... ça pose qq soucis. On va forcer en UTC, à voir lors des chgts d'horaires

**Comment by osallou** [comment]
@AGareil j'ai patché en prod, tu peux vérifier ?

Ds le cas -1 our les restrictions, cela ne s'applique que si la résa n'est pas encore commencée

**Comment by AGareil** [comment]
Je peux modifié les résa sous compte user, parfait merci !
