### ISSUE TITLE
[BUG] Canceled reservations still in the home

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#655]
**Describe the bug**

Sur son accueil on a l'ensemble des réservations faites classés dans l'ordre chronologique de réservation.
Quand je fais une réservation, mais qu'elle est annulée, elle persiste quand même dans la liste.

**If using a Saas install (GenOuest for example)**
Bug pour tous, là je prend l'exemple ECOBIO/VOITURES

**To Reproduce**
1. Go to 'https://pfm.genouest.org/corespace/21'
2. Click on 'Impersonate Agnès Bulski'
3. Dans l'accueil il y a une réservation pour la V6 le 11/06/2022 à 14h (initialement de 12h à 17h)
4. Cette réservation a été annulée par l'admin agareil, elle n'existe plus sur le calendrier et pourtant elle est toujours présente dans ma liste

**Expected behavior**
Mettre à jour la liste des réservations actives?
C'est cosmétique mais ça permet d'avoir son journal de réservation à jour.

**Comment by osallou** [comment]
@gaetan, verifier la requete sur le deleted=0 ?

**Comment by osallou** [comment]
Ok, request did not check for the delete field

**Comment by osallou** [comment]
fixé mais pas encore en prod

**Comment by AGareil** [comment]
Ok merci pour toutes ces rapides corrections !
bonne journée
