### ISSUE TITLE
[Com] Allow to manage visibility on com articles and welcome message

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#660]
UC: If a space is public and space managers want to communicate (with com module) information toward members of their space only, they can't: external visitors can also access to this information.
A solution would be to add a visibility parameter on articles and welcome message

**Comment by osallou** [comment]
need #661 first, then add a space member only second message in com config, then display like the other one if space member.

no db schema impact, this is just a space param

**Comment by osallou** [comment]
@gaetanHerve à fermer non?
