### ISSUE TITLE
[BUG] Nous n'arrivons pas à nous connecter à PF Manager ce matin (19/07/22) est-ce que vous avez aussi ce soucis ?

### ISSUE THREAD

**Issue by nadegemarec** [bgo-bioimagerie/platformmanager#682]
**Describe the bug**

**If using a Saas install (GenOuest for example)**
specify your space name

**To Reproduce**
1. Go to 'https://...'

**Expected behavior**

**Additional context**

**Comment by osallou** [comment]
Bonjour, nous avons diffusé un mail a certaines personnes dont nous avions le mail.

En raison d un incident de climatisation, toute notre infrastructure a été arrêtée électriquement.
Nous attendons la réparation de la clim pour redémarrer les services, ce qui prendra un peu de temps. En espérant que l arrêt brutal de certaines machines n ait pas causé de dégats sur les bases de données etc.. (ce qui impliquerait des délais supplémentaires pour récupérer les sauvegardes).

Vous pouvez suivre genouest sur twitter pour les communications en cas d incidents importants (car dans de tel cas, nos serveurs de mail et de communication, etc... sont également indisponibles)

**Comment by gaetanHerve** [comment]
Service rétabli
