### ISSUE TITLE
[Booking] Could user edit resource in reservation form ?

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#684]
Issue raised by SIR Platform.

Current behaviour:
When accessing to reservation form from booking schedule view, resource is already set. Once in reservation form, resources select input is disabled (unless user is an admin or a manager). To choose another resource, user has to go back to booking schedule view, change selected resource, then click on a slot again to access to a reservation form for the chosen resource.
 
Suggested behaviour:
All authorised users should be able to change the selected resource in reservation form.

Constraints:
A user is generally not authorized to make a reservation for all resources, some parameters also depend on the selected resource. It will be necessary to dynamically refresh them when selecting another resource.

**Comment by osallou** [comment]
Humm add complexity on controls etc.. just vecause user selected wrong resource and just need to go back.

Changing resource in form would also possibly be on a time range not available

**Comment by gaetanHerve** [comment]
So it doesn't worth the shot for now... Too much controls to implement and it would make it non-intuitive to the user. Closing this issue.
