### ISSUE TITLE
[Booking] Add a default booking view option in booking configuration  

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#686]
Raised by SIR Platform.

UC: Space admins would like to set a default booking view for all their space users.

Solution:
Add a "default view" option in booking configuration page. This parameter would override user's default booking view parameter and user's last booking view used

**Comment by osallou** [comment]
Should not override user default view

If user define a view, it should be used...

Same for last view. If you select a view of your choice, you don t want to get an other one.

Default view in booking config should be used only when no other is defined
