### ISSUE TITLE
[Antibodies]Add column in antibody module

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#702]
*Hello, 
Nous aimerions pour la plateforme H2P2, 
Dans le module "Anticorps" nous souhaitons  rajouter une colonne "Réactivité"
dans le module anticorps, à côté de la colonne source , cette colonne doit être avec une écriture libre comme pour fournisseur
Merci 
Pascale

**If using a Saas install (GenOuest for example)**
specify your space name

**To Reproduce**
1. Go to 'https://...'

**Expected behavior**

**Additional context**

**Comment by gaetanHerve** [comment]
Merci pour l'issue Pascale :). 
Pour les prochaines, tu as possibilité de passer par "Open a blank issue" si le modèle proposé dans "Get started" ne convient pas

![open_issue](https://user-images.githubusercontent.com/48911130/187216462-06a9715e-7a26-49ef-85bd-69842701ed95.png)

**Comment by Pbellaud** [comment]
Bonjour, 
je ne vois pas la nouvelle colonne "Réactivité" qui devait être ajoutée dans Anticorps 
à droite de la colonne Source 

Merci 
Pascale 


De: "Olivier Sallou" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 12 Septembre 2022 14:07:26 
Objet: Re: [bgo-bioimagerie/platformmanager] [Antibodies]Add column in antibody module (Issue #702) 






Closed [ https://github.com/bgo-bioimagerie/platformmanager/issues/702 | #702 ] as completed via [ https://github.com/bgo-bioimagerie/platformmanager/commit/8c80b550d5340f5398289322483b7c8ff704fe95 | 8c80b55 ] .

**Comment by gaetanHerve** [comment]
Bonjour Pascale,
C'est normal, nous avons fait la release (figé le code pour pouvoir mettre à jour), mais pas encore mis à jour l'instance de production. Demain en principe. La nouvelle colonne est bien intégré à cette release.
Bonne journée,
Gaëtan

**Comment by Pbellaud** [comment]
Ok je n'avais pas compris 
On a remarqué en plus qq anomalies, mais il est peut être trop tard : 

1 : la recherche tissu cible (changer le nom par Espèce : car ça correspond à la colonne Espèce (dans tissu) 


- 


2-Si l'on fait la recherche :Statut : 3 seuls apparaissent alors qu'il y en a 8 d'enregistrés 

3-Importation Excel : 
on a systématiquement toute la liste des Ac, si on veut admettons : CD31, on a quand toute la liste 

4-Pb du texte sur les photos que l'on importe (on est limité en texte contrairement à avant) 

5-Pb d'alignement des lignes dans le tableau 
Ex : CD31 (N°191) au niveau des lignes : Xénogreffe devrait être sur la dernière ligne, il y a un décalage avec les photos 
[ https://pfm.genouest.org/anticorpsedit/8/3 | 191 ] 	[ https://pfm.genouest.org/anticorpsedit/8/3 | CD31 ] 	+4°C 	Abcam 	Rb 	ab28364 	Polyclonal 	GR3247742-11 	IgG 	

[ https://pfm.genouest.org/protocolsedit/8/41 | 104 O ] 

[ https://pfm.genouest.org/protocolsedit/8/41 | 104 O ] 

[ https://pfm.genouest.org/protocolsedit/8/41 | 104 O ] 

[ https://pfm.genouest.org/protocolsedit/8/122 | 17 F ] 	

1/100 

1/100 

1/100 

1-50 		

proto 464 







Xénogreffe Hum/Ms 

6-Lorsque l'on est sur le menu Ac, par defaut c'est le A qui est mis, il faudrait que ce soit le : Tous 


Voilà j'espère que c'est compréhensible et que ce n'est pas trop tard 
Merci 
Bonne soirée 
Pascale 



De: "gaetanHerve" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 12 Septembre 2022 16:21:38 
Objet: Re: [bgo-bioimagerie/platformmanager] [Antibodies]Add column in antibody module (Issue #702) 






Bonjour Pascale, 
C'est normal, nous avons fait la release (figé le code pour pouvoir mettre à jour), mais pas encore mis à jour l'instance de production. Demain en principe. La nouvelle colonne est bien intégré à cette release. 
Bonne journée, 
Gaëtan

**Comment by gaetanHerve** [comment]
@Pbellaud , c'est en effet trop tard pour la release de septembre. Je rajoute ça pour la prochaine release (octobre)

**Comment by Pbellaud** [comment]
Parfait 
Merci 
Bonne journée 
Pascale 



De: "gaetanHerve" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Lundi 12 Septembre 2022 17:03:53 
Objet: Re: [bgo-bioimagerie/platformmanager] [Antibodies]Add column in antibody module (Issue #702) 





[ https://github.com/Pbellaud | @Pbellaud ] , c'est en effet trop tard pour la release de septembre. Je rajoute ça pour la prochaine release (octobre)

**Comment by gaetanHerve** [comment]
@Pbellaud pour le point 1, la recherche par tissus cible recherche actuellement sur la colonne organe (dans tissus), et non sur la colonne espèce. Je remplace donc "tissu cible" par "organe", ou tu veux spécifiquement une recherche par espèce ?

**Comment by Pbellaud** [comment]
Ce qui m'intéresse c'est une recherche spécifique par espèce, 
Merci 
Pascale 



De: "gaetanHerve" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mercredi 14 Septembre 2022 14:42:04 
Objet: Re: [bgo-bioimagerie/platformmanager] [Antibodies]Add column in antibody module (Issue #702) 





[ https://github.com/Pbellaud | @Pbellaud ] pour le point 1, la recherche par tissus cible recherche actuellement sur la colonne organe (dans tissus), et non sur la colonne espèce. Je remplace donc "tissu cible" par "organe", ou tu veux spécifiquement une recherche par espèce ?

**Comment by gaetanHerve** [comment]
@Pbellaud je ne comprends pas très bien ce que tu veux dire par "4-Pb du texte sur les photos que l'on importe (on est limité en texte contrairement à avant)".
Je suppose que tu parles de la colonne "commentaires" de la partie tissus, qui est placée juste après la colonne où apparaissent les images des tissus ?

**Comment by Pbellaud** [comment]
Bonjour Gaetan, 
Je t'ai mis en pièce jointe la photo que jeux insérer et qu'il ne veut pas 
C'est dans tissu : image : choisisez un fichier 

Merci 
pascale 





De: "gaetanHerve" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Jeudi 22 Septembre 2022 15:08:32 
Objet: Re: [bgo-bioimagerie/platformmanager] [Antibodies]Add column in antibody module (Issue #702) 






[ https://github.com/Pbellaud | @Pbellaud ] je ne comprends pas très bien ce que tu veux dire par "4-Pb du texte sur les photos que l'on importe (on est limité en texte contrairement à avant)". 
Je suppose que tu parles de la colonne "commentaires" de la partie tissus, qui est placée juste après la colonne où apparaissent les images des tissus ?

**Comment by gaetanHerve** [comment]
@Pbellaud 

Bonjour Pascale,

Je n'ai pas accès à la pièce jointe (le passage par github la bloque manifestement).
Quand tu dis "il ne veut pas", PFM te renvoies le message d'erreur "invalid file name, must be alphanumeric: [0-9a-zA-Z\-_\.]+ " ?
Si oui, c'est que ton fichier contient des caractères non acceptés (on a ajouté ce comportement pour éviter certains bugs potentiels).
Il ne faut pas d'espaces, d'accents, etc... dans ton nom de fichier.

C'est bien ça le problème ?

**Comment by Pbellaud** [comment]
Oui c'est bien ça, je t'ai joint les 2 photos qui ne passait pas 
il faudrait que l'on puisse mettre un peu de caractères spéciaux, 
pour que la légende de la photo a du sens, 
tu peux regarder dans catalogue anticorps, les légendes que l'on aimerait mettre 
Merci 
Pascale 



De: "gaetanHerve" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 4 Octobre 2022 11:08:08 
Objet: Re: [bgo-bioimagerie/platformmanager] [Antibodies]Add column in antibody module (Issue #702) 





[ https://github.com/Pbellaud | @Pbellaud ] 

Bonjour Pascale, 

Je n'ai pas accès à la pièce jointe (le passage par github la bloque manifestement). 
Quand tu dis "il ne veut pas", PFM te renvoies le message d'erreur "invalid file name, must be alphanumeric: [0-9a-zA-Z-_.]+ " ? 
Si oui, c'est que ton fichier contient des caractères non acceptés (on a ajouté ce comportement pour éviter certains bugs potentiels). 
Il ne faut pas d'espaces, d'accents, etc... dans ton nom de fichier. 

C'est bien ça le problème ?

**Comment by osallou** [comment]
Legende et nom de fichier sont 2 choses differentes

Accents et espaces ds nom de fichiers sobt a proscrire (on peut mettre - ou _ a la place des espaces)

Qd on ajoute une photo, il y a un champ description  il n y a pas de restrictions dans ce champ.

**Comment by Pbellaud** [comment]
Ca marche, 
tu as un contrat jusqu'à quelle date ? 
Pascale 



De: "gaetanHerve" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 29 Août 2022 15:49:51 
Objet: Re: [bgo-bioimagerie/platformmanager] [BUG]Add column in antibody module (Issue #702) 





Merci pour l'issue Pascale :). 
Pour les prochaines, tu as possibilité de passer par "Open a blank issue" si le modèle proposé dans "Get started" ne convient pas 

[ https://user-images.githubusercontent.com/48911130/187216462-06a9715e-7a26-49ef-85bd-69842701ed95.png ]

**Comment by gaetanHerve** [comment]
Salut Pascale,
Je termine ce vendredi. C'était la dernière mise à jour (hors éventuels bug fixes liés à celle-ci) avant mon départ

**Comment by Pbellaud** [comment]
Salut Gaetan 
Merci pour les dernières mises à jour et pour toutes les améliorations que tu as faites, 
pour le moment pas de bug! 
Dommage que tu partes 
Bonne continuation à toi 
Pascale 




De: "gaetanHerve" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 11 Octobre 2022 11:21:22 
Objet: Re: [bgo-bioimagerie/platformmanager] [Antibodies]Add column in antibody module (Issue #702) 





Salut Pascale, 
Je termine ce vendredi. C'était la dernière mise à jour (hors éventuels bug fixes liés à celle-ci) avant mon départ

**Comment by gaetanHerve** [comment]
Merci Pascale :).
Bonne continuation à toi également !
Gaëtan
