### ISSUE TITLE
[Bookings] Users can access to their reservations even if not authorised

### ISSUE THREAD

**Issue by gaetanHerve** [bgo-bioimagerie/platformmanager#711]
On welcome page, the user's reservations summary gives access to reservations without passing through the BookingdefaultController::canUserEditReservation check.
In UC where space managers want to forbid access to reservation edition for some ressources, users still can edit / delete it

**Comment by osallou** [comment]
welcome page shows user reservation and this is fine (it is their reservation....)
In any case, a user should be able to view his reservations....

where can we forbid user reservation edition ? In any case, if something forbid its edition, it should be checked in edit/delete controller itself (done at least i suppose on form submit).
