### ISSUE TITLE
[BUG] Ghost filed required

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#712]
_**Describe the bug**
A clear and concise description of what the bug is._

In the "MICRO" plateform in ECOBIO, we have a equiement named "PSMII" which require a field to book, but the field didn't exist in the form ans nobody can book this equipement anymore.

_**If using a Saas install (GenOuest for example)**
specify your space name_

ECOBIO > MICRO 

_**To Reproduce**
Steps to reproduce the behavior:_

1. Go to 'https://pfm.genouest.org/bookingweek/28?bk_curentDate=2022-09-19&bk_id_resource=442&bk_id_area=131&id_user=&view=simple)'
2. Scroll down to 'Domaine : PSMII'
3. Scroll down to 'Ressource : PSM BIOAIR S@fleflow'
4. Maque a reservation
5. Error : Field Indiquer le nature de vos écha mandatory

_**Expected behavior**
A clear and concise description of what you expected to happen._

I want to know where this field is, i didn't see it anywhere.
There was a required field but the field was : "Types d'échantillons et risques" , I swich it to "non mandatory" and now I totally disable any mandatory filed, but in both case, the error is still here.

_**Additional context**
Add any other context about the problem here._

I made a new equipement "PSM II" on the same Domaine, the same Category (named "PSM BIOAIR S@fleflow bis") and a file require, it work.
The Administrator prefer to debugg the old calendar, because there were some reservations on it.

It's like there was one day a field name "Indiquer le nature de vos échantillons" with a mistake ("le" nature) and it was too long for PFM and when the administrator change to "Types d'échantillons et risques"  PFM didn't manage to change the field correctly (?). 
And the field is now a epigenetic status for this equipement?

Or it's obvious somewhere in front of my nose but I didn't find it. 

Thanks for help.

**Comment by gaetanHerve** [comment]
@AGareil ok, I take a look

**Comment by gaetanHerve** [comment]
@AGareil te souviens-tu à quelle date tu as supprimé le "Types d'échantillons et risques" en question ?

**Comment by gaetanHerve** [comment]
super, merci :)

**Comment by AGareil** [comment]
par contre je ne sais pas quand le champs "Indiquer le nature de vos écha" a été transformé en "Types d'échantillons et risques".
J'ai demandé vendredi à la gestionnaire si elle se souvenait d'avoir soit créé soit modifié un champs "Indiquer le nature de vos écha" ou ""Indiquer le nature de vos échantillons" mais elle ne m'a pour l'instant pas répondu.
La dernière réservation est au 8 septembre, donc je dirais entre le 8 et le 16 (?)

**Comment by osallou** [comment]
un "Indiquer le nature de vos ..." a été supprimé le 16 septembre à 8h23

**Comment by AGareil** [comment]
ok, ça correspond, quand j'ai regardé après le message de l'administrateur à 9h il y avait "Types d'échantillons et risques" pour tout les équipements en obligatoire.

**Comment by osallou** [comment]
on a trouvé la cause, on vérifie les possibles effet de bord et on corrige

**Comment by AGareil** [comment]
super ! merci

**Comment by AGareil** [comment]
il y a quelque chose à faire pour éviter de retomber sur ce soucis ou c'est un impondérable?

**Comment by osallou** [comment]
non, un effet de bord d'un fix récent

j'ai mis à jour en prod pour ne pas te bloquer, cela devrait fonctionner (merci de confirmer)

on va de notre coté faire un patch complet

**Comment by AGareil** [comment]
Ca marche, parfait.
Merci et bonne journée
