### ISSUE TITLE
Default addition of "q=" in the description of projects[BUG]

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#718]
Bonjour, 
Pour H2P2, 
dans l'outil prestations/projets en cours
Ex : compte clients/edit /projets en cours/ coulouarn/edit /suivi/description : il y "q= qui apparait 
et ça dans tous les projets
Merci 
Pascale

**Comment by osallou** [comment]
Ce q=x correspond aux quantités

Cela avait ete rajouté je crois, mais je ne sais plus trop pourquoi. Mais nous pouvons le supprimer.

**Comment by Pbellaud** [comment]
Pour nous ça peut être supprimé, car on en a pas vraiment l'utilité 



De: "Olivier Sallou" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Author" ***@***.***> 
Envoyé: Mercredi 28 Septembre 2022 10:30:33 
Objet: Re: [bgo-bioimagerie/platformmanager] Default addition of "q=" in the description of projects[BUG] (Issue #718) 





Ce q=x correspond aux quantités 

Cela avait ete rajouté je crois, mais je ne sais plus trop pourquoi. Mais nous pouvons le supprimer.

**Comment by osallou** [comment]
l'affichage a été un peu revu:

    service1 [q=2]

on garde la quantité car information utile pour certains

**Comment by Pbellaud** [comment]
Ca marche 
Merci 



De: "Olivier Sallou" ***@***.***> 
À: "bgo-bioimagerie" ***@***.***> 
Cc: "Pascale Bellaud" ***@***.***>, "Author" ***@***.***> 
Envoyé: Lundi 14 Novembre 2022 13:50:14 
Objet: Re: [bgo-bioimagerie/platformmanager] Default addition of "q=" in the description of projects[BUG] (Issue #718) 





l'affichage a été un peu revu: 
service1 [q=2] 


on garde la quantité car information utile pour certains
