### ISSUE TITLE
Bug in booking with package

### ISSUE THREAD

**Issue by micso-geh** [bgo-bioimagerie/platformmanager#719]
Bonjour

Dans la configuration du calendrier, j'ai obligé les utilisateurs à réserver avec un forfait. J'ai fait une réservation sur un équipement et cela fonctionne, il y a un menu déroulant avec mes différents forfaits. Par contre, quelque soit le forfait sélectionné, la réservation se valide uniquement avec le premier forfait. Pouvez-vous modifier cela ?

Bien cordialement
Sophie MC
EcogenO

**Comment by osallou** [comment]
@micso-geh le pb est résolu normalement. En revanche, mm si le "premier" forfait apparait sélectionné, ce n'est pas le cas (aucun ne l'est en fait). Il faut donc editer la resa et resauvegarder pour mettre à jour le package. Pour les nouvelles resa, ce sera "ok".

Le pb est lié à l'option pour forcer les packages. Lorsque le formulaire est soumis, un champ n'était pas envoyé

**Comment by osallou** [comment]
fixed in commit 3fb3cd919d34a65f431e2fd557b561f169edb798 , v2.8.3

**Comment by micso-geh** [comment]
Merci beaucoup pour la rapidité à résoudre le bug !
Bon we
Sophie
