### ISSUE TITLE
[BUG] affichage par defaut en résumé

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#720]
L'affichage du calendrier des ressources se fait maintenant par défaut en "résumé" mais plus en "détails". Ce mode d'affichage nous convenait mieux. On peut choisir ses préférences sur la vue par défaut (jour, jour domaine, semaine, mois), il serait intéressant de pouvoir aussi choisir si on veut le mode résumé ou détails.

**Comment by osallou** [comment]
il n'y a pas eu de chgts "récents" sur la vue par défaut du calendrier.

Le type de vue "par défaut" dépend de chacun, une préférence utilisateur serait effectivement bienvenue

**Comment by sdutertre** [comment]
Ce changement date d'il y a environ une quinzaine de jours

**Comment by sdutertre** [comment]
Je ne vois pas comment changer cette vue "resume vs détails" même en mode admin

**Comment by osallou** [comment]
c'est codé, mais pas encore en prod
