### ISSUE TITLE
[BUG] Multiple erreurs of navigation in plateforme manager

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#725]
Bonjour, 
J'ai quelques propositions et remarques sur la navigation sur plateforme manager pour la plateforme H2P2

1) Problème de crash dans l'onglet " Anticorps" quand on cherche un anticorps par nom, numéro etc.
Aller sur https://pfm.genouest.org/antibodies/8 
écrire "CD31" par exemple, cliquer sur un des résultats
cliquer marche arrière sur le navigateur pour revenir sur le résultat de la recherche 
Message d'erreur 

Par contre en cliquant sur l'onglet "anticorps", puis "tous" et si on cherche avec l'outil "search" cd31, on clique sur un des résultats puis marche arrière sur le navigateur on a pas de message d'erreur par contre on n'a plus les résultats de cd31 ce qui est embêtant. Je veux bien faire la recherche avec  l'outil "search" dans le manu de base si après avoir cherché un anticorps puis ayant fait marche arrière il se souvienne du résultat de ma dernière recherche .
(D'ailleurs est-ce que c'est possible de régler l'onglet "Anticorps" par défaut sur l'onglet "Tous" à la place de la lettre "A", on trouve ça plus pratique )

2) Possible de régler l'onglet "MAD" sur la visualisation "Calendrier" par défaut ?  

3) Quand on va sur onglet "Prestations" puis "suivi" on a un affichage par page, show 10 entries. On voudrais un affichage "Show All" par défaut svp car c'est pas du tout pratique par page

Pour l'instant c'est tout 

Merci d'avance pour votre

**Comment by gaetanHerve** [comment]
Bonjour @GevH2P2 ,

A propos d'Anticorps :

Il ne s'agit pas vraiment d'un crash. Étant donné que la recherche est un formulaire, le "retour arrière" après obtention des résultats ne peut pas fonctionner (comme c'est la cas de base pour n'importe quel formulaire web) et c'est normal.
En termes d'usage, l'idéal serait peut-être d'afficher la page de l'anticorps que tu sélectionne dans un nouvel onglet. Tu aurais comme ça toujours accès au résultat de ta recherche dans l'onglet initial.

Le choix du "A" par défaut est lié au temps de chargement de cette page (afficher tous les anticorps implique un très grand nombre de requêtes). Il sera est optimisé dans la mise à jour que nous allons passer d'ici le milieu de semaine, mais restera important.

A propos de MAD :

Oui, cela est possible [ici](https://pfm.genouest.org/bookingconfig/8) si tu es admin de l'espace dans "vue par défaut".
Sinon, tu peux également gérer tes préférences personnelles (qui sont prioritaires sur ce qui est choisi pour l'espace) [ici](https://pfm.genouest.org/Bookingusersettings).

A propos du suivi des prestations :
Le "10 entrées par page" est appliqué sur l'ensemble des tableaux de l'application (exception faite du module anticorps, qui fonctionne différemment), toujours pour éviter un trop grand nombre de requêtes serveur.
Il serait peu cohérent de faire une exception pour les prestations. Une solution serait peut-être de proposer dans la config d'espace de choisir pour chaque module combien de lignes doivent être affichées par page. A voir.

Sachant que, avec ma fin de contrat imminente, nous n'allons pas apporter de modification importante à PFM avant qu'un nouveau recrutement soit lancé.

Bonne journée,
Gaëtan

**Comment by gaetanHerve** [comment]
@GevH2P2, on a résolu les différents points (pas encore en prod):
- possibilité de choisir le nombre de lignes à afficher par tableau dans les préférences utilisateur (PR #726 )
- conservation de la recherche lorsque l'on fait retour arrière sur la liste des anticorps (PR #727 )
- par défaut, tous les anticorps sont affichés, non plus seulement les "A" (PR #728). Puisqu'il n'y a que vous à l'utiliser et que vous affichez "All" quoiqu'il arrive...

**Comment by GevH2P2** [comment]
Bonjour Gaetan, 
Merci pour les réponse
1) Ok pour la recherche de l'anticorps, en espérant que la mise à jour fonctionne et rend plus fluide la recherche 

2) je suis allé sur les réglages d'affichage d'MAD mais ça ne marche pas. Je veux "jour domaine" avec "Détails" qui donne cette affichage 
![image](https://user-images.githubusercontent.com/89006804/194888984-5f8c46fe-fcf0-44bc-9d2d-ebb7bf3c80b5.png)
J'ai testé tous les combinaisons mais j'ai toujours pas cette affichage. 

3) Ce qui concerne l'affichages dans suivi du nombre de prestations qui est fixé sur 10 c'est vraiment handicapant. ça me dérange pas d'avoir ça dans l'onglet projet en cours mais dans le suivi 10 onglets c'est pas possible,, surtout lorsqu'on rajoute une prestation qui doit être sur la page 3, il se met sur la page 1 car après n'importe quelle opération il s'initiale. Il faut paginer jusqu'à la page voulu pour rajouter une nouvelle prestation et puis initialisation. C'est vraiment insupportable pour travailler. 
Pour mois c'est priorité N° 1. Par ailleurs la page du suivi n'est pas très chargé, on peut pas comparé avec l'onglet Ac par exemple, si on mets afficher tous ça va pas ralentir.

**Comment by gaetanHerve** [comment]
- ah, pour le choix de l'affichage "détails" ou "résumé", ça arrive avec la mise à jour. Dans les préférence utilisateur également.

![booking_preferences](https://user-images.githubusercontent.com/48911130/194892926-3f3a28ad-86f2-42b3-8223-d8d1bd4fc1b3.png)

- pour le nombres de lignes dans les tableaux, idem

![core_preferences](https://user-images.githubusercontent.com/48911130/194893285-1b084479-ae27-4b26-b4f5-48a51bbf331c.png)

**Comment by GevH2P2** [comment]
Bonjour GaëtanHerve et Osallou. 
Merci beaucoup, ça a fonctionné ! ça va nous faciliter la vie. Merci !!!
