### ISSUE TITLE
[BUG] ABGRALL Sandra qui est attribuée à tous les projets  et on n'arrive pas à la supprimer, changer

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#738]
**Describe the bug**
Dans l'onglet "Prestations", quand on choisi un projet, ABGRALL Sandra est automatiquement attribuée en tant qu'utilisatrice. On n'arrive pas à la supprimer. J'ai essayé de mettre un autre utilisateur, ça ne marche pas non plus. 

Merci d'avance pour votre aide

**Comment by osallou** [comment]
bonjour,

Pour exemple/debug, quel projet sélectionnez-vous et quel client/user essayez-vous de lui attribuer?
Lorsque j'édite un de vos projets je vois bien des utilisateurs différents.

Abgrall correspond au premier utilisateur de la liste, et est visuellement sélectionné par défaut si aucun autre ne correspond.

**Comment by GevH2P2** [comment]
Bonjour osallou
Par exemple dans projets en cours je cherche le projet MixSc 22-03 où je vois l'utilisateur ABGRALL Sandra. Je clique "edit" , je me rajoute en tant qu'utilisateur et je supprime Sandra, je clique valider. La page s'actualise avec Sandra toujours en utilisatrice principale

**Comment by osallou** [comment]
dans le client actuel de ce projet, Mixscience, il n'y a aucun utilisateur. Pour remplir le champ principal "utilisateur", il faut que le client choisi ait au moins un utilisateur. L'utilisateur Sandra était le premier de la liste et donc sélectionné par défaut.
Si l'utilisateur principal du projet n'est pas dans la liste du bas, il est automatiquement rajouté, c'est pourquoi sandra revenait systématiquement. Il fallait d'abord corriger l'utilisateur principal.

J'ai ajouté un champ "vide", qui montre qu'il n 'y a pas d'utilisateur sélectionné.

A partir de là, j'ai pu également enlever Sandra de la liste des utilisateurs.

**Comment by GevH2P2** [comment]
Merci pour la correction et les explications
Pour éviter d'aller à chaque fois choisir "vide" en tant qu'utilisateur, peut on fixer le vide par défaut ?

**Comment by GevH2P2** [comment]
Aaaa ok ^^ 
Merci pour vos explications et votre aide 
Bonne journée !
