### ISSUE TITLE
[BUG]Date qui s'initialise automatiquement dans le calendrier

### ISSUE THREAD

**Issue by GevH2P2** [bgo-bioimagerie/platformmanager#739]
Bonjour, 
Encore moi ^^
Quand je vais sur MAD, je change la date, je fais une réservation, après cette opération il se mets sur "aujourd'hui". C'est embêtant car si j'ai plusieurs réservations dans les jours à venir je dois cliquer à chaque fois pour revenir sur la date voulu après chaque réservation. 
De tout façon si y a besoin de revenir sur aujourd'hui y a le bouton "aujourd'hui". 

Merci d'avance

**Comment by osallou** [comment]
bonjour,
en effet, petite régression graphique lors de la dernier mise à jour

c'est corrigé en prod, merci de confirmer qu'après une réservation, vous revenez bien au jour en question

**Comment by osallou** [comment]
fixed in commit 40c3bd0750752050d2ffd618c676a61d99661fc4, rel 2.9.2
