### ISSUE TITLE
liste des destinataires d'un mail

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#744]
Bonjour,
je souhaite envoyer un mail à tous les utilisateurs de la plateforme. Souvent j'envoie un mail mais en ne ciblant que les utilisateurs d'une ressource et cela fonctionne plutôt bien. Là, j'ai mis en destinataire "all" et j'ai l'impression que peu de personnes reçoivent le mail. Dans le mail que j'ai reçu il y a en destinataire "undisclosed recipients". Est ce que je peux avoir la liste des personnes destinataires de ce mail?
Stéphanie

**Comment by osallou** [comment]
La liste n est pas disponible en l etat.

All devrait envoyer a l ensemble des personnes ayant un acces a l espace

**Comment by sdutertre** [comment]
pour le dernier mail, je l'ai reçu mais pas Xavier, ni Marc. J'ai l'impression que personne ne le reçoit.

**Comment by sdutertre** [comment]
erreur, certains le reçoivent

**Comment by osallou** [comment]
Tous les utilisateurs actifs avec un role dans l espace devraient le recevoir.

Et a condition bien sur que leur mail soit a jour

**Comment by osallou** [comment]
je ne vois aucune erreur de mon côté

**Comment by sdutertre** [comment]
en y réfléchissant, j'ai l'impression que ce sont les personnes déclarées en gestionnaire qui n'ont pas reçu le message.

**Comment by osallou** [comment]
le all ne comprends pas en effet les managers, uniquement ceux qui ont un role utilisateur
