### ISSUE TITLE
Modifier le nom de contact sur la facture-Plateforme H2P2-Biosit

### ISSUE THREAD

**Issue by Rviel** [bgo-bioimagerie/platformmanager#753]
Bonjour,

Lorsque l'on génère une facture sur plateform Manager. La personne contact est encore Alain Fautrel ( parti en retraite) est il possible de modifier et de mettre Anthony SEBILLOT, Numéro de Tél : 02 23 23 33 83.

Merci

**Comment by osallou** [comment]
bonjour 
il suffit d'éditer votre template de facture

**Comment by osallou** [comment]
pas la facture, son template

dans configuration / invoices /  HTML - PDF Template edit   (https://pfm.genouest.org/invoicepdftemplate/8)

il faut récupérer le template, le modifier et le recharger (attention à ne pas "casser" le formattage du template, je conseille de garder une copie vant de le modifier)

**Comment by Rviel** [comment]
Oui j'avais été , mais je n'arrive pas à télécharger le ".twig"

**Comment by osallou** [comment]
Il faut les droits admin dans l espace

J ai essayé et j ai pu le telecharger tout a l heure

**Comment by Rviel** [comment]
Du coup vous le modifier ou j'attend d'être admin?
