### ISSUE TITLE
[account update]

### ISSUE THREAD

**Issue by tpecot** [bgo-bioimagerie/platformmanager#754]
Bonjour,

Je fais partie de Biosit et m'occupe du Guichet d'analyse d'images. Je viens de créer la plateforme FAIIA, j'aimerais donc mettre à jour platform-manager.
Il faudrait remplacer Guichet analyse d'images par FAIIA, modifier la description de la manière suivante :
FAIIA délivre une expertise pour la quantification et l'analyse d'images de microscopie.
Enfin, il faudrait ajouter le logo disponible ici :
https://filesender.renater.fr/?s=download&token=06e8b532-64aa-4811-8c6a-fc0d346b2bfe

Merci beaucoup !

**Comment by osallou** [comment]
Bonjour,
Les admin d espace peuvent modifier nom, description et logos de leurs espaces respectifs
