### ISSUE TITLE
désactivation de compte utilisateurs si pas de réservation

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#755]
Bonjour,

J'ai besoin de pouvoir désactiver les droits de réservation d'une ressource si la personne n'a pas réservé depuis plus d'un an par ex. Je sais que cette fonctionnalité a existé au départ de PFM mais elle ne marche plus pour moi ou je ne sais pas activer ce paramètre (faire passer une personne de l'état utilisateur actif à inactif automatiquement). Pour le moment, dans MRic personne ne passe en inactif.
Je suis sur PFM Biosit MRic.
merci
Stéphanie

**Comment by osallou** [comment]
Dans la configuration de l'espace, il y a 2 champs:

* Deactivate user account when: condition à évaluer
* On account expiration : action à réaliser si condition précédente remplie

Il faut avoir le role admin dans l'espace pour pouvoir agir sur ceci.

Une fois configuré selon vos besoins, dans la partie de gestion des utilisateurs, section "expiring" (https://pfm.genouest.org/corespaceaccess/1/user/expire) seront listés les utilisateurs remplissant les conditions.

Vous pouvez alors cliquer sur "Run" pour appliquer la condition  définie ds la config avec "On account expiration".

Dans la table des utilisateurs, vous aurez également un lien vers l'utilisateur où cas où vous voudriez agir manuellement sur un utilisateur plus précisement.

**Comment by osallou** [comment]
tant que le "run" n'est pas exécute, la page affiche uniquement les "candidats" à l'inactivation etc..

Après, cela dépend du choix à appliquer:

1) on choisit de le désactiver (status = inactive) et il conserve ses droits
2)  on choisit de le supprimer de l'espace, et il perd ses droits

**Comment by sdutertre** [comment]
ok. C'est plus clair.
Les comptes utilisateurs sont indépendants d'un espace à l'autre?
Ils passent automatiquement dans inactivation et ensuite il faut lancer "run" de temps en temps pour complètement les désactiver. Si ils sont dans l'onglet "inactivation", ils peuvent quand même réserver?

**Comment by osallou** [comment]
les espaces sont totalement indépendant les uns des autres

concernant l'onglet inactivation, il est juste informatif avant de cliquer sur run pour inactiver ou retirer l'utilisateur.

il est tjs utile de lancer le "run" régulièrement pour "faire le ménage" dans les comptes (2 fois par an serait déjà bien)

**Comment by sdutertre** [comment]
du coup, c'est bizarre. Est ce que tu peux regarder pour l'utilisateur #247. Pour moi, il n'est pas venu depuis plus d'un an mais est encore dans les actifs. Est ce que c'est parce qu'il est aussi "compte client"?

**Comment by osallou** [comment]
cas non géré initialement dans le code apparement, l'utilisateur ne s'est jamais loggué (en tout cas aucune trace dans la base de donnée), peut etre que dernier login date d'avant l'import des utilisateurs des différentes plateformes avant d'aller chez nous.

**Comment by osallou** [comment]
cas un peu spécial à gérer.... on ne peut pas expirer ceux qui ne se sont jamais loggués, car c'est "normal" pour un compte récent

**Comment by sdutertre** [comment]
logique

**Comment by osallou** [comment]
j'ai fait une modif, on voit le 247 dans la liste maintenant par exemple
