### ISSUE TITLE
[BUG] impossible to add resources to calendars

### ISSUE THREAD

**Issue by AGareil** [bgo-bioimagerie/platformmanager#758]
**Describe the bug**
It's impossible to add ressources on our calendars, we have a error message : Resource plan limit reached: 4

**If using a Saas install (GenOuest for example)**
PFM > ECOBIO
On all spaces

**To Reproduce**
1. [Go to 'https://...'](https://pfm.univ-rennes.fr/corespace/38)
2. Click on 'Ressources'
3. Click on 'Ressources +'
4. Fill the fields
5. Click on "Valider"
6. See error "Resource plan limit reached: 4"

**Expected behavior**
I want to be able to add ressources

**Additional context**
All the space for ECOBIO are in the same troubles

Thanks for your attention.

Agnès

**Comment by dmellet** [comment]
Hello Audrey,

We have changed the limit to create resources for a Space.
Now, you should be able to create as much resources as you want for the ECOBIO spaces

Sorry for the inconvenience

Damien

**Comment by AGareil** [comment]
Bonjour Damien,

Merci / Thanks !

Ca remarche !

Agnès

**Comment by AGareil** [comment]
résolu

**Comment by AGareil** [comment]
Bonjour,

L'erreur est réapparue aujourd'hui.
Impossible de rajouter des ressources, 

Merci,

Agnès

**Comment by dmellet** [comment]
Bonjour,

Je viens de réappliquer la mise à jour sur le serveur.
Il ne devrait plus y avoir de problème pour rajouter plus de ressources.

Damien
