### ISSUE TITLE
User role profile self-inactivation

### ISSUE THREAD

**Issue by OlivierCollin** [bgo-bioimagerie/platformmanager#76]
Some users systematically go back to inactive status and no longer have access to the reservation system.
When the profiles are switched back to user status it works for a time but the problem will appear again.

**Comment by abretaud** [comment]
> Il y a un script dans l’outil qui se lance a chaque fois qu’un admin de plateforme se connecte.
> Le script fait le ménage sur les utilisateurs qui n’ont pas d’activité depuis un certain temps (1 an sans réservé ou date de fin de contrat dépassée)
> 
> Ce script se trouve dans Modules/core/Controller/CoreconnectscriptController.php, lignes 24 à 28
> Il faudrait voir pourquoi il désactive trop de comptes, ou sinon l’enlever.

**Comment by OlivierCollin** [comment]
The test is conclusive, disabling the test stops the self-inactivation. 
Now we have to understand why the script does not function properly...

**Comment by osallou** [comment]
also test 1 year with connecting....

**Comment by OlivierCollin** [comment]
OK. See you next year...  ;-)

**Comment by osallou** [comment]
cli-pfm.php integrates an option to deactivate users, could be in cron

Need to check in code on what is done exactly and conditions
