### ISSUE TITLE
Statistics module - web page error 

### ISSUE THREAD

**Issue by OlivierCollin** [bgo-bioimagerie/platformmanager#77]
When asking for global statistics for a facility,  the web browser returns a "file not found error". 

Example:
Firefox ne peut trouver le fichier à l’adresse https://pfm.genouest.org/statisticsglobal/1.

**Comment by abretaud** [comment]
The problem was that the Zip php module was missing in the docker image. Fixed in https://github.com/bgo-bioimagerie/docker-platformmanager/commit/a919248934b540fd9427c167cc57b785d3caed09
pfm.genouest.org was updated
