### ISSUE TITLE
Quotes (devis) give a blank page

### ISSUE THREAD

**Issue by abretaud** [bgo-bioimagerie/platformmanager#79]
When clicking on Devis/Quote for a platform, we get a completely blank page, with no error.

**Comment by abretaud** [comment]
It used to work, but was broken before migrating to genouest (when merging several platformmanager instances)

**Comment by osallou** [comment]
@abretaud can't reproduce on dev, I could create and generate a devis

**Comment by abretaud** [comment]
you can't reproduce because I fixed it :)

**Comment by osallou** [comment]
still an issue on dev, sending you details

**Comment by abretaud** [comment]
Updated on pfm.genouest.org
