### ISSUE TITLE
User deletion

### ISSUE THREAD

**Issue by abretaud** [bgo-bioimagerie/platformmanager#81]
We should be able to delete some users, we couldn't find a way to do it

**Comment by dosli** [comment]
The same issue. Please, could you delete the users lbachelot and lperrot?

**Comment by abretaud** [comment]
There is some code there: https://github.com/bgo-bioimagerie/platformmanager/blob/master/Modules/core/Controller/CoreusersController.php#L174

It seems to be callable from this page: https://pfm-dev.genouest.org/coreusers/ but no link point to it

In the configuration (Administration> Core) one can choose if users are deletable by admin or users. It's admin at the moment. It stores it in param "who_can_delete_user" but it's never used anywhere.

TODO:
- check that it works (impact on invoices/quotes/booking/...?)
- add a link somewhere, at least for the admin
- check if we should give access to users or only admin
- make sure "who_can_delete_user" setting is checked before deleting

**Comment by abretaud** [comment]
I've just added a "Users" link in the administration menu, pointing to coreusers. Access is restricted to instance admin.
Deletion works. Some data are still in the db after deletion, but it doesn't break pages. For example reservations are still there, but written as "unknown".
We can use it, but only for redundant users or to solve blocked situation.
`who_can_delete_user` is not used, leaving as is until rework on the user management

The page was hidden as it was designed for non-multitenant version = platform owner could delete their users. Now we don't want platform owner A to delete users that are using platform B. Needs refactoring, will open another issue for that.

**Comment by osallou** [comment]
with multi-tenant, users can join or leave a space

space owner can force user leave (to be checked)

User is not deleted, only removed from user space

Space admin should be able to delete a user (and this would remove any user_pending or space role related data)

**Comment by gaetanHerve** [comment]
When space admins want to delete a user linked to a space and/or specific items (like resources or bookings), they should be warned by an alert window asking for validation and detailing (in a nutshell ?) to what the user to delete is attached.
If, despite that, space admins choose to delete user, repercussions on items it is linked to must be handled.

**Comment by osallou** [comment]
I am updating models for security etc...
After that objects will not be deleted but only tagged as deleted to avoid side effects and missing relations. This will also allow to revert operation if needed (manual op by superadmin)

Real deletion of user shoulf be done by superadmin only and only if user not in a space.

**Comment by gaetanHerve** [comment]
Ok. So, to solve this issue, I'm just going to add a check to avoid super admin deleting any user member of a space, with an alert window to inform super admin.
