### ISSUE TITLE
Web interface translation

### ISSUE THREAD

**Issue by abretaud** [bgo-bioimagerie/platformmanager#82]
We couldn't find a way to switch the interface to english

**Comment by OlivierCollin** [comment]
We should maybe consider an internationalization of the interface.

**Comment by chdiot** [comment]
Do you mean that actually there is no english interface?

**Comment by OlivierCollin** [comment]
It seems so. In the configuration part of the application, there is no menu or configuration tool to do this.

**Comment by chdiot** [comment]
:/

**Comment by OlivierCollin** [comment]
Changing the language preferences in the web browser, allows to switch to english. 
That means that international users will use english by default but french users will have a localized interface.
