### ISSUE TITLE
Shift in microscopes booking times

### ISSUE THREAD

**Issue by xavpinson** [bgo-bioimagerie/platformmanager#85]
Since today (29/05/2018) all microscope booking times on the MRic Photonics section have been shifted 2 hours forward. For example a microscope originally booked from 2pm to 4 pm now wrongly appears booked from 4 pm to 6 pm.

**Comment by OlivierCollin** [comment]
Hello Xavier, 
Do you know if this issue concerns only MRic Photonics or if other facilities also experiment this issue ?

**Comment by osallou** [comment]
it may be a host (container) time issue.
@abretaud , time in container is Tue May 29 14:25:29 UTC 2018 while on host  Tue May 29 16:25:11 CEST 2018

**Comment by xavpinson** [comment]
Impaccell is also affected. It seems to be global although I can't check the others.

**Comment by osallou** [comment]
@xavpinson could you specify exactly which booking is wrong in MRic Photonics ? (person who reserved at which time)

**Comment by xavpinson** [comment]
All of them :)
The whole schedule is shifted.

**Comment by osallou** [comment]
in database, they are recorded at the shown schedule. so problem is at reservation time. we updated to fix statistics and other issues the timezone. We need to see what is going on

**Comment by abretaud** [comment]
It's related to this change: https://github.com/bgo-bioimagerie/docker-platformmanager/commit/6c43e278917272a1b67c63b20450da4559c6abd6

**Comment by osallou** [comment]
@xavpinson , problem seems to be solved, reservations are shown as expected, can you confirm?

**Comment by xavpinson** [comment]
Yes it looks ok now. Thanks!

**Comment by osallou** [comment]
@xavpinson  can you test with a new reservation? (to checks new ones are ok too)

**Comment by xavpinson** [comment]
@osallou Just tested. Everything seems normal.

**Comment by osallou** [comment]
perfect, thanks
