### ISSUE TITLE
Docker or not docker

### ISSUE THREAD

**Issue by chdiot** [bgo-bioimagerie/platformmanager#86]
hello GenOuesters,
I'm potentially a new user and I would like to know the better way to install PFM, the zip archive or the docker?
This is not clear to me

**Comment by chdiot** [comment]
Very reactive Anthony.
Thanks a lot

**Comment by abretaud** [comment]
I've updated the doc to run a dockerized instance on https://github.com/bgo-bioimagerie/docker-platformmanager if you want to test

**Comment by chdiot** [comment]
Thanks again Anthony. I close this issue.
