### ISSUE TITLE
Ressources

### ISSUE THREAD

**Issue by pgripon** [bgo-bioimagerie/platformmanager#88]
En tant qu'administrateur d'un domaine (L3 Biosit) je ne vois apparaître dans l'outil "Ressources" que les ressources de ce domaine nouvellement créées. Les anciennes ressources, bien qu'apparaissant dans l'outil "Calendrier" comme dans l'outil "Calendrier configuration" ou même dans l'outil "Statistiques" n'apparaissent pas dans l'outil "Ressource", ce qui empêche toute modification.

**Comment by pgripon** [comment]
De plus l'outil "facturation" ne semble prendre en compte que la ressource nouvellement créée, apparaissant donc dans l'outil "ressources" Du coup cette nouvelle ressource a remplacé les anciennes ressources dans les anciens relevés à envoyer de l'outil facturation.

**Comment by osallou** [comment]
nous allons essayer de reproduire cela

**Comment by osallou** [comment]
le problème semble lié à votre domaine, car il n'apparait pas sur d'autres domaines (du moins celui que j'ai testé), cela semble être nu problème avec les catégories

**Comment by osallou** [comment]
il n'y a en effet aucune catégorie liée à votre domaine (sur la base de test, donc ne contient pas vos nouvelles données)

**Comment by pgripon** [comment]
Ce problème ne s'était pas posé jusqu'à cette année, les ressources apparaissaient normalement, la facturation ne posait pas de soucis. IL est vraisemblable qu'il n'y avait pas de catégories de définies, seules les ressources l'étant. A l'origine tout avait été défini sur un autre logiciel puis il y a eu transfert.

**Comment by osallou** [comment]
il n'y avait visiblement pas de categories en effet. Celle qui sont ajoutées marchent bien, mais les anciennes ressources ne sont pas liées avec elles.
