### ISSUE TITLE
Facturation globale

### ISSUE THREAD

**Issue by pgripon** [bgo-bioimagerie/platformmanager#89]
Bonjour,
Si la facturation par responsable a été possible un moment avec une ressource nouvellement créée elle est maintenant devenue impossible, aucun relevé n'est créé. De plus la facturation globale du L3 est impossible, le logiciel pointe sur une page blanche (https://pfm.genouest.org/invoiceglobal/5).

**Comment by OlivierCollin** [comment]
Merci pour ce retour. Est-il possible de préciser la temporalité des choses ? 
Qu'entendez-vous par "un moment" ?

**Comment by abretaud** [comment]
Un problème fortement similaire a été remonté par des gens de Nantes, et Sylvain a fourni ce patch qui semble corriger le problème : https://github.com/bgo-bioimagerie/platformmanager/commit/6ed40333422f069b1c5209d00aa7db22f1ace0c2
Je viens de l'appliquer sur pfm.genouest.org
@pgripon peux-tu tester et nous dire si le problème est résolu ?

**Comment by pgripon** [comment]
Merci, je vois avec nos informaticiens et je te tiens au courant

**Comment by OlivierCollin** [comment]
Est-ce que les tests sont concluants ?

**Comment by pgripon** [comment]
@OlivierCollin  Quels tests? Si tu souhaites que j'installe le patch moi-même et que je le teste, il va falloir me former ou me donner des instructions très précises. Le seul langage de programmation que j'ai appris à utiliser et ça fait un bail, c'est le fortran! ;-)
Sinon je viens d'essayer d'établir un relevé, rien de nouveau, ça ne marche toujours pas.

**Comment by OlivierCollin** [comment]
Anthony a déjà appliqué le patch sur pfm.genouest.org. Il semble donc que cela ne corrige pas le problème rencontré, hélas.... 
Sinon, par curiosité, quels sont les informaticiens que tu devais consulter ?

**Comment by pgripon** [comment]
Un certain Olivier notamment ;-)

**Comment by OlivierCollin** [comment]
Je crois voir qui c'est ;-)

**Comment by osallou** [comment]
il manque en effet des choses ds le code, il n'y a plus de "responsible".

**Comment by osallou** [comment]
@pgripon  j'ai modifié le code pour gérer cela (le code a visiblement fait disparaitre cette fonctionnalité à un moment), et cela a l'air bon maintenant, mais il est possible que d'autres "menus" aient le meme problème.
JE vois bien apparaitre des factures maintenant, mais pouvez vous vérifier qu'elles sont "correctes" ?

**Comment by osallou** [comment]
@abretaud j'ai pushé le fix ds develop

**Comment by pgripon** [comment]
@osallou Merci pour tes efforts. Les seules factures qui apparaissent dans mon module "invoice" sous l'onglet 2018 sont celles faites en 2017. Elles ont toujours été là depuis leur création. Par contre il m'est toujours impossible de facturer quoi que ce soit. :-(
Un autre problème qui n'est pas résolu et est particulièrement gênant c'est le fait que le module ressources ne voit pas les ressources créées auparavant et qui apparaissent pourtant dans les modules statistiques et calendrier

**Comment by osallou** [comment]
pour les "anciennes" resources, c'est normal car elles n'étaient pas (et ne le sont toujours pas) associées à des catégories existantes. Du coup elles pointents vers quelque chose qui n'existe pas. Les nouvelles resources qui sont elles bien associées à une catégorie ne posent pas de problème.

pour les nouvelles facturations, comment cela se fait-il  ? (Facturation -> Nouveau relevé -> et un choix de début/fin de période c'est cela ? J'ai vu en effet que cela était vide pour l'onglet 2019, des factures sont censées apparaitre par rapport à vos data ?
Le problème que nous avons ici est que cette fonctionnalité ne fonctionne clairement pas dans le code que nous avons récupéré.... :-(

**Comment by osallou** [comment]
@pgripon 
après qq tests sur la plateforme de test, j'arrive à générer des factures pour de nouvelles resources, et affectant bien les resources/reservations.

le problème est  lié au fait que vos réservations sont affectées à des resources qui ne sont pas associées à des catégories existante

**Comment by osallou** [comment]
si vous créer les categories, je peux faire apparaitre temporairement les resources manquantes (actuellement, si pas de match, elles n'apparaissent pas). Vous pourrez alors afffecter chacune d'entre elles à une categorie que vous aurez préalablement crée.

**Comment by pgripon** [comment]
@osallou 
Plateform-Manager n'est pas accessible ce matin, néanmoins cela fait pas loin de 2 semaines que j'ai créé 3 catégories (PSM, ULTRA et MICRO). De plus à ce même moment j'ai créé une ressource fictive pour tester la facturation. Quand j'écris que la facturation ne fonctionne pas, c'est qu'elle ne fonctionne ni avec les anciennes ressources (ne comportant pas de catégorie)  ni avec la ressource nouvellement créée.

**Comment by osallou** [comment]
puis-je tester la génération de facture afin d'évaluer ce qui ne va pas ? (car sur la plateforme de test je n'ai pas eu de soucis)

**Comment by pgripon** [comment]
@osallou Bien sûr!

**Comment by pgripon** [comment]
Je ne sais pas en quoi consiste la plateforme de test mais il est clair que d'une part  la facturation du L3 fonctionnait bien en 2017 et ne fonctionne pas en 2018, et que d'autre part la facturation des autres plateformes ne semble pas poser de problème en ce moment.

**Comment by osallou** [comment]
pour ce qui est des "anciennes" réservations, le problème est lié au fait qu'elles ne sont pas associées à des catagories existantes, ce n'est pas le cas d'autres platformes.
Pour les "nouvelles" réservation avec la resource de test qui, elle, est associée à une catégorie, la facture est bien générée, c'est un problème d'affichage. Le module n'affiche que les factures générées entre les 2018-11-01 et 2019-05-31 (à la date d'aujourd'hui). Je ne connais pas la raison de cette contrainte (j'investigue)

**Comment by osallou** [comment]
je viens de comprendre pour les dates, c'est ce que vous avez défini dans la partie administration du module de facturation (invoice)
