### ISSUE TITLE
Plateform-Manager indisponible depuis ce matin

### ISSUE THREAD

**Issue by pgripon** [bgo-bioimagerie/platformmanager#90]
Bonjour, 
Pour des raisons inconnues le logiciel plateform-Manager est inaccessible depuis ce matin. La page qui s'ouvre porte le message suivant:
503 - Service temporairement indisponible ou en maintenance
Le service est en maintenance.
Veuillez ré-essayer dans quelques minutes.

**Comment by osallou** [comment]
j'y accède pourtant normalement  https://pfm.genouest.org

**Comment by OlivierCollin** [comment]
Bonjour Philippe, 
Chez nous, cela tourne bien. 
As-tu essayé de rafraîchir le cache de ton navigateur  ?
