### ISSUE TITLE
shift des slots de réservations 

### ISSUE THREAD

**Issue by sdutertre** [bgo-bioimagerie/platformmanager#91]
bonjour,
nous avons eu de nouveau un shift de réservations (2 h plus tôt) (cf issue #85). Ce qui est perturbant cette fois c'est que cela concerne seulement certaines réservations de certaines ressources. Les réservations ont été faites par le même utilisateur et je pense le même jour. J'ai décalé à la main ces slots. Pouvez-vous me prévenir si en résolvant le bug ces créneaux sont de nouveau décalés. 
voici la copie d'écran:
![image](https://user-images.githubusercontent.com/19782757/41352607-3c60bb16-6f1a-11e8-8afc-27b45e21f306.png)

**Comment by osallou** [comment]
Le pb doit etre lie au pb precedent suite a une mise a jour. Si cela est effectivement le cas, les slots en question seront redecales lors de la resolution.
Nous allons verifier cela

**Comment by osallou** [comment]
Ce qui m'etonne est un shift uniquement sur certaines resa. Est ce lie a un utilisteur, une resource particuliere?

**Comment by abretaud** [comment]
@osallou Peut-être que l'image en prod n'était pas à jour, dans le doute j'ai fait un `docker-compose pull` qui a récupéré une nouvelle image.
@sdutertre est-ce que les horaires sont bons actuellement ? Peux-tu faire un test ?

**Comment by sdutertre** [comment]
oui les horaires sont bons mais n'ont pas changés par rapport à ma modification manuelle

**Comment by osallou** [comment]
si les resa ont été modifiées manuellement, ces modifs ne sont pas rectifiées, pouvez vous essayer une resa de test pour voir si la resa est correcte?

**Comment by sdutertre** [comment]
Les réservations sont modifiés a postériori (suite sans doute à des mises à jour). On avait eu ce problème lors de la migration. J'ai testé une réservation et je n'ai pas de souci de décalage.

**Comment by osallou** [comment]
Je propose alors de clore le pb, et vous le re ouvrirez si le pb se pose à
nouveau


> .
>

**Comment by sdutertre** [comment]
peut-être un élément de réponse; Un utilisateur lambda ne peut pas normalement réserver dans le passé et ne peut réserver que là ou apparaissent des croix bleues (cf copie écran). Il y a un décalage entre le temps du site et le temps réel (il est 17h 15 et l'utilisateur peut réserver dans le passé à 15h30).
![image](https://user-images.githubusercontent.com/19782757/41421296-c6e25b14-6ff6-11e8-9b95-75c164328dde.png)
