### ISSUE TITLE
Plateforme manager inaccessible depuis ce matin

### ISSUE THREAD

**Issue by Fleurisson** [bgo-bioimagerie/platformmanager#92]
Bonjour,

Pour des raisons inconnues le logiciel plateform-Manager est inaccessible depuis ce matin. La page qui s'ouvre porte le message suivant:
503 - Service temporairement indisponible ou en maintenance
Le service est en maintenance.
Veuillez ré-essayer dans quelques minutes.

Romain platforme APEX NANTES

**Comment by osallou** [comment]
Je viens d'essayer et je n'ai pas de probleme d'acces depuis l'exterieur
Vous accedez a https://pfm.genouest.org?

**Comment by Fleurisson** [comment]
Bonjour Olivier,

Pour préciser notre demande, le site pour  plateforme manager n'est pas le même, car nous somme la plateforme APEX de Nantes.

je vous est transférer le liens pour que vous testiez

https://bioimagerie.univ-rennes1.fr/apex/connection/

Romain

**Comment by osallou** [comment]
Ok, mais nous ne occupons pas de ce site, je ne sais pas qui en est
responsable.
Nous gérons uniquement le site pfm.genouest.org

Le lun. 2 juil. 2018 à 18:19, Fleurisson <notifications@github.com> a
écrit :

**Comment by Fleurisson** [comment]
Bonjour Olivier,
Je suis Laurence Dubreil responsable de la composante Bio-imagerie de la plateforme APEX INRA Oniris située à Nantes. Notre plateforme Manager est hébergé à Rennes et notre ancien contact était Sylvain Prigent Biogenouest. J'avais compris que vous allliez prendre le relaie comme pour la plateforme MRic, c'est Stéphanie Dutertre qui m'a indiqué la démarche à suivre c'est pour cela que nous vous avons contacté. Merci par avance pour votre aide.

**Comment by osallou** [comment]
Bonjour, je suggère de passer en mode "privé" pour discuter de cela, vous pouvez m'envoyer un mail directement.

**Comment by OlivierCollin** [comment]
Il y a eu une coupure d'électricité sur le site qui héberge la machine bioimagerie.univ-rennes1.fr. 
Stéphanie va regarder cela.

**Comment by OlivierCollin** [comment]
Site opérationnel : https://bioimagerie.univ-rennes1.fr/apex/

**Comment by Fleurisson** [comment]
Bonjour Olivier,
Merci pour la remise en service
Bonne fin de journée 
Romain
