### ISSUE TITLE
Installation troubles

### ISSUE THREAD

**Issue by cmonjeau** [bgo-bioimagerie/platformmanager#93]
With @OlivierCollin, we've observed some issues at the install of platform-manager using docker.

1. In `Config/conf.ini`, replace "Core" by "core"
2. In `Modules/core/Model/CoreAdminMenu.php`, replace CreateTable() by __construct()
3. Core theme files are not in `data/` repository after install. css are not accessible by web server.
4. The step `http://your_url.com/update` does not work (403 Forbidden)
5. When I make a  `http://your_url.com/coreupdate`, I have an error:
`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'platform_manager.ec_j_user_responsible' doesn't exist
`

**Comment by osallou** [comment]
Wht are update and coreupdzte for?

Le jeu. 19 juil. 2018 à 16:17, MONJEAUD Cyril <notifications@github.com> a
écrit :

**Comment by cmonjeau** [comment]
http://your_url.com/update will initialize the database for all the modules listed in the config file (see the documentation).

http://your_url.com/coreupdate is launch after clicking on the update button in the web interface.

**Comment by cmonjeau** [comment]
I don't know. I just click the button and I have an error.

**Comment by osallou** [comment]
fixed, @abretaud  is looking to merge my updates

**Comment by abretaud** [comment]
FYI there's a default admin account created on a new instance: see http://bgo-bioimagerie.github.io/platformmanager/install.html near "First: change the admin password!"
