### ISSUE TITLE
Pb  statistiques utilisateurs H2P2

### ISSUE THREAD

**Issue by Pbellaud** [bgo-bioimagerie/platformmanager#97]
Bonjour, 
Lorsque nous faisons les statistiques : /liste des autorisations / categories / exemple scanner de lames  :
nous observons  qq erreurs sur le fichier excel 
-Allain Coralie : est inactive, mais elle apparait quand même
son compte client : Loreal olivier ( enregistré etablissement : Numecan et c'est  noté : INSERM 1241  ancien nom de l'équipe.
-Il manque des d'utilisateurs ex : 
Cahu Armelle (derniere réservation le 31 Aout)

Ps : un utilisateur qui n'a pas utilisé un équipement sur H2P2 depuis un an devient inactif et ne devrait plus apparaitre  sur le listing .
  Je vous remercie
Cordialement 
Pascale

**Comment by osallou** [comment]
concernant le compte client, le nom de l'équipe a changé, mais lors de la réservation peut être était-ce encore l'ancien nom? (la réservation aurait enregistré le nom de l'équipe au moment de la réservation)

**Comment by osallou** [comment]
concernant coralie, dans la table des authorization, elle est marquée comme active (bien que son status soit inactive). Il semble que le fait qu'une personne change de status principal ne modifie pas ses authorisations. C'est pourquoi elle reste affichée ds les stats. Il faudrait lui retirer ses autorisations.

**Comment by osallou** [comment]
j'ai modifié le code pour faire apparait les gens n'ayant pas de unit/lab définit ds les réservations, faisant apparaitre armelle et d'autre personnes. Merci de confirmer que c'est ok pour que je "valide" le code

**Comment by Pbellaud** [comment]
le listing nous convient,  le code peut être validé.
Le problème de la liste responsable qui n'est pas complète, vient peut être du fait que maintenant les responsables sont enregistrés en client .

**Comment by osallou** [comment]
code mis à jour
